POST https://coral-test2.banachtechnology.com/api/buildabet/placeBet
Content-Type: application/json

{
    "obEventId": 0,
    "selectionIds": [
        0
    ],
    "freeBetIds": [
        0
    ],
    "obUserToken": "string",
    "obUserId": "string",
    "ipAddress": "string",
    "channel": "string",
    "stake": 1.100000023841858,
    "userDecimalPrice": 1.100000023841858,
    "userPriceNum": 0,
    "userPriceDen": 0
}

###
