export const LOTTO_VALUES = {
    id: '5e6f2f85c9e77c000118b4cc',
    updatedBy: '54905d04a49acf605d645271',
    updatedAt: 'test',
    createdBy: 'test',
    createdAt: 'test',
    updatedByUserName: 'test',
    createdByUserName: 'test',
    brand: 'bma',
    label: 'label',
    infoMessage: 'message',
    nextLink: 'link',
    bannerLink: 'banner link',
    bannerText: 'banner text',
    ssMappingId: '1',
    svgId: 'lotto-49',
    sortOrder: 0,
    enabled: false,
    svgFilename: {
        filename: '',
        path: '',
        size: null,
        filetype: '',
        originalname: '',
      }
}