GET http://localhost:8080/silks/teamtalk/9695931
Origin: https://invictus.coral.co.uk
Referer: https://invictus.coral.co.uk/horse-racing/featured
###

GET http://localhost:8080/silks/racingpost/154380,1859,1859b,217366,260058,272082,39010,49845,49845b,49845c,55336
Origin: https://invictus.coral.co.uk
Referer: https://invictus.coral.co.uk/horse-racing/featured
###

GET http://localhost:8080/silks/racingpost/154380,1859,1859b,217366,260058,272082,39010,49845,49845b,49845c
Origin: https://invictus.coral.co.uk
Referer: https://invictus.coral.co.uk/horse-racing/featured
###

GET http://localhost:8080/silks/racingpost/154380,1859,1859b,217366,260058,272082,39010,49845,49845b,49845c,55338
Origin: https://invictus.coral.co.uk
Referer: https://invictus.coral.co.uk/horse-racing/featured
###
