clone:
  depth: full
pipelines:

  default:
    - step:
        name: build
        image: azul/zulu-openjdk:17.0.5
        caches:
          - gradle
          - gradlewrapper
        script:
          - chmod +x ./gradlew
          - ./gradlew spotlessApply
          - ./gradlew test build
    - step:
        name: test
        image: azul/zulu-openjdk:17.0.5
        caches:
          - sonarcloud
        script:
          - chmod +x ./gradlew
          - ./gradlew spotlessApply
          - ./gradlew test sonarqube --watch-fs
            -Dsonar.coverage.exclusions=**/*Config.java,**/*Client.java,src/main/java/com/ladbrokescoral/reactions/health/**/*,src/main/java/com/ladbrokescoral/reactions/ReactionsApplication.java


  pull-requests:
    '**':
      - step:
          name: build
          image: azul/zulu-openjdk:17.0.5
          script:
            - chmod +x ./gradlew
            - ./gradlew spotlessApply
            - ./gradlew test build

      - step:
          name: test
          image: azul/zulu-openjdk:17.0.5
          script:
            - chmod +x ./gradlew
            - ./gradlew test sonarqube
              -Dsonar.pullrequest.key=$BITBUCKET_PR_ID
              -Dsonar.pullrequest.base=$BITBUCKET_PR_DESTINATION_BRANCH
              -Dsonar.pullrequest.branch=$BITBUCKET_BRANCH
              -Dsonar.coverage.exclusions=**/*Config.java,**/*Client.java,src/main/java/com/ladbrokescoral/reactions/health/**/*,src/main/java/com/ladbrokescoral/reactions/ReactionsApplication.java




definitions:
  caches:
    sonarcloud: ~/.sonar/cache
    gradlewrapper: ~/.gradle/wrapper
