POST https://coral-test2.banachtechnology.com/api/buildabet/placeBet
Content-Type: application/json

{
    "obEventId": 0,
    "selectionIds": [
        0
    ],
    "freeBetIds": [
        0
    ],
    "obUserToken": "string",
    "obUserId": "string",
    "ipAddress": "string",
    "channel": "e",
    "stake": 2,
    "userPriceNum": 11,
    "userPriceDen": 10
}

###