export const NEXT_RACES_HOME_CONSTANTS = {
   WIDGET: 'widget',
   HORSE_RACING: 'HORSE_RACING',
   HANDICAPS: 'handicaps',
   KEY_NOT_FOUND:'KEY_NOT_FOUND',
   RACECARD: 'Racecard',
   GREYHOUNDS: 'GREYHOUNDS',
   SB_SEEALL:'sb.seeAll',
   UNAMED_FAVOURITE:'unnamed favourite',
   UNAMED_2ND_FAVOURITE:'unnamed 2nd favourite',
   PRICE_LOWER_cASE:'price',
   UNNAMED: 'Unnamed',
   PRICE_CAMEL_CASE:'Price',
   TRACKEVENT: 'trackEvent',
   RACE_CARD:'race card',
   GREYHOUNDS_LOWERCASE:'greyhounds',
   HORSE_RACING_LOWERCASE:'horse racing',
   SORT_BY_PRICE:'sort by - price',
   SORT_BY_RACECARD:'sort by - racecard',
   SHOW_INFO: 'Show Info',
   HIDE_INFO : 'Hide Info',
  };