version: 1
disable_existing_loggers: True
loggers:
  behave_logger:
    level: INFO
    handlers: [console]
  crlat_ob_client:
    propagate: True
    level: ERROR
    handlers: [console]
formatters:
  default:
    format: '%(asctime)s.%(msecs)03d: %(levelname)-8s %(name)s.%(module)s.%(funcName)-10s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    level: INFO
