export const category = {
  'id': '5555c32a02a83bb989cbedf8',
  'hasEvents': true,
  'matchesTabEnabled': true,
  'inplayTabEnabled': false,
  'competitionTabEnabled': false,
  'couponsTabEnabled': true,
  'outrightsTabEnabled': true,
  'specialsTabEnabled': true,
  'highlightCarouselEnabled': false,
  'surfaceBetsEnabled': false,
  'quickLinkEnabled': false,
  'inplayEnabled': false,
  'inplaySportModule': {
    'enabled': false,
    'inplayCount': 10
  },
  'filename': '56d26bb6d3d6bfcffafb0f90a995a1f1.png',
  'uriMedium': '',
  'uriLarge': '',
  'uriSmall': '',
  'widthLarge': 96,
  'widthMedium': 32,
  'widthSmall': 104,
  'heightLarge': 96,
  'heightMedium': 32,
  'heightSmall': 104,
  'uriLargeIcon': '',
  'uriMediumIcon': '',
  'uriSmallIcon': '',
  'alt': '',
  'imageTitle': 'American Football',
  'categoryId': 1,
  'ssCategoryCode': 'AMERICAN_FOOTBALL',
  'targetUri': 'sport/american-football',
  'disabled': false,
  'showInPlay': true,
  'showInHome': true,
  'showInAZ': true,
  'path': 'public/images/uploads',
  'isTopSport': true,
  'inApp': true,
  'showScoreboard': false,
  'scoreBoardUrl': null,
  'svg': '',
  'svgId': '#ujmlahvywv',
  'targetUriCopy': 'sport/american-football',
  'sportName': 'sport/american-football',
  'relUri': false,
  'iconClass': '',
  'categoryCode': '',
  'displayOrder': 0,
  'uri': '',
  'hidden': false,
  'isActive': true,
  'brand': ''
};
export const menuItem = {
  "id": "6231b3646fbb3a352321abd8",
  "alt": "",
  "imageTitle": "Fanzone",
  "categoryId": 160,
  "ssCategoryCode": "FANZONE",
  "targetUri": "fanzone/sport-football/ArsenalFC/now-next",
  "disabled": false,
  "showInPlay": false,
  "showInHome": true,
  "showInAZ": true,
  "path": "",
  "isTopSport": true,
  "inApp": true,
  "showScoreboard": false,
  "scoreBoardUrl": "",
  "hasEvents": true,
  "svg": "",
  "svgId": "footballnew",
  "sortOrder": -2.125,
  "sportConfig": {
      "config": {
          "title": "Fanzone",
          "name": "sportfootball",
          "path": "sport-football",
          "tier": 0,
          "oddsCardHeaderType": "",
          "request": {
              "categoryId": "160",
              "siteChannels": "M",
              "marketsCount": true,
              "dispSortName": [
                  ""
              ],
              "dispSortNameIncludeOnly": [
                  ""
              ],
              "marketTemplateMarketNameIntersects": ""
          },
          "isOutrightSport": false,
          "isMultiTemplateSport": false
      }
  },
  "targetUriCopy": "fanzone/sport-football/ArsenalFC/now-next",
  "sportName": "fanzone/sport-football/ArsenalFC/now-next",
  "relUri": false,
  "iconClass": "",
  "targetUriParts": [
      "/",
      "fanzone",
      "sport-football",
      "ArsenalFC",
      "now-next"
  ]
}
