class LEVELS:
    COUPON = 'coupon'
    CLASS = 'class'
    EVENT = 'event'
    TYPE = 'type'
    MARKET = 'market'
    OUTCOME = 'outcome'
    POOL = 'pool'
    LOTTERY = 'lottery'


class ATTRIBUTES:
    SITE_CHANNELS = 'siteChannels'
    CATEGORY_ID = 'categoryId'
    CLASS_ID = 'classId'
    ID = 'id'
    TYPE_NAME = 'typeName'
    TYPE_ID = 'typeId'
    NAME = 'name'
    TYPE = 'type'
    IS_STARTED = 'isStarted'
    IS_ACTIVE = 'isActive'
    IS_LIVE_NOW_EVENT = 'isLiveNowEvent'
    EVENT_STATUS_CODE = 'eventStatusCode'
    EVENT_SORT_CODE = 'eventSortCode'
    OUTCOME_STATUS_CODE = 'outcomeStatusCode'
    MARKET_STATUS_CODE = 'marketStatusCode'
    TEMPLATE_MARKET_NAME = 'templateMarketName'
    COLLECTION_NAMES = 'collectionNames'
    DRILLDOWN_TAG_NAMES = 'drilldownTagNames'
    PROVIDER = 'provider'
    TYPE_FLAG_CODES = 'typeFlagCodes'
    START_TIME = 'startTime'
    SUSPEND_AT_TIME = 'suspendAtTime'
    IS_FINISHED = 'isFinished'
    IS_RESULTED = 'isResulted'
    CASHOUT_AVAIL = 'cashoutAvail'
    IS_EACH_WAY_AVAILABLE = 'isEachWayAvailable'
    IS_GP_AVAILABLE = 'isGpAvailable'
    DISP_SORT_NAME = 'dispSortName'
    NCAST_TYPE_CODES = 'ncastTypeCodes'
    PRICE_TYPE_CODES = 'priceTypeCodes'
    IS_MARKET_BET_IN_RUN = 'isMarketBetInRun'
    RAW_IS_OFF_CODE = 'rawIsOffCode'
    RUNNER_NUMBER = 'runnerNumber'
    HAS_OPEN_DRAW = 'hasOpenDraw'
    HAS_OPEN_EVENT = 'hasOpenEvent'


class OPERATORS:
    # Unary Ops
    IS_TRUE = 'isTrue'
    IS_FALSE = 'isFalse'
    IS_NULL = 'isNull'
    IS_NOT_NULL = 'isNotNull'
    IS_EMPTY = 'isEmpty'
    IS_NOT_EMPTY = 'isNotEmpty'
    # Binary Ops
    EQUALS = 'equals'
    NOT_EQUALS = 'notEquals'
    LESS_THAN = 'lessThan'
    GREATER_THAN = 'greaterThan'
    LESS_THAN_OR_EQUAL = 'lessThanOrEqual'
    GREATER_THAN_OR_EQUAL = 'greaterThanOrEqual'
    CONTAINS = 'contains'
    NOT_CONTAINS = 'notContains'
    IN = 'in'
    NOT_IN = 'notIn'
    INTERSECTS = 'intersects'
    NOT_INTERSECTS = 'notIntersects'
