clone:
  depth: full
pipelines:

  default:
    - step:
        name: build
        image: azul/zulu-openjdk:17.0.5
        caches:
          - gradle
          - gradlewrapper
        script:
          - chmod +x ./gradlew
          - ./gradlew spotlessApply
          - ./gradlew test build -x audit
    - step:
        name: test
        image: azul/zulu-openjdk:17.0.5
        caches:
          - sonarcloud
        script:
          - chmod +x ./gradlew
          - ./gradlew spotlessApply
          - ./gradlew test sonarqube --watch-fs
            -Dsonar.coverage.exclusions=src/main/java/com/entain/oxygen/configuration/**/*.java,src/main/java/com/entain/oxygen/util/**/*.java,src/main/java/com/entain/oxygen/router/UserStableRouter.java,src/main/java/com/entain/oxygen/handler/UserStableHandler.java


  pull-requests:
    '**':
      - step:
          name: build
          image: azul/zulu-openjdk:17.0.5
          script:
            - chmod +x ./gradlew
            - ./gradlew spotlessApply
            - ./gradlew test build -x audit

      - step:
          name: test
          image: azul/zulu-openjdk:17.0.5
          script:
            - chmod +x ./gradlew
            - ./gradlew spotlessApply
            - ./gradlew test sonarqube --watch-fs
              -Dsonar.pullrequest.key=$BITBUCKET_PR_ID
              -Dsonar.pullrequest.base=$BITBUCKET_PR_DESTINATION_BRANCH
              -Dsonar.pullrequest.branch=$BITBUCKET_BRANCH
              -Dsonar.coverage.exclusions=src/main/java/com/entain/oxygen/configuration/**/*.java,src/main/java/com/entain/oxygen/util/**/*.java,src/main/java/com/entain/oxygen/router/UserStableRouter.java,src/main/java/com/entain/oxygen/handler/UserStableHandler.java

definitions:
  caches:
    sonarcloud: ~/.sonar/cache
    gradlewrapper: ~/.gradle/wrapper
