cms:
  base.url: https://cms-prd0.coralsports.prod.cloud.ladbrokescoral.com/
  brand: bma

siteServer.base.url: https://ss-aka-ori.coral.co.uk/
stats.center.url: https://spark-br.symphony-solutions.eu/

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
