cms:
  base.url: https://cms-api-ui-tst0.coralsports.nonprod.cloud.ladbrokescoral.com
  brand: ladbrokes

siteServer.base.url: https://tst2-backoffice-lcm.ladbrokes.com
stats.center.url: https://spark-br.symphony-solutions.eu/

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
