spring:
  redis:
    password: D2D2D9FBB87079F58F2FE3C4B367006C695D63FD
    sentinel:
      master: master
      nodes:  AT1T5XACOD674.dbz.unix:26388,AT1T5XACOD675.dbz.unix:26388,AT1T5XACOD678.dbz.unix:26388



siteServer:
  baseUrl: https://ss-tst2.coral.co.uk/

liveserv:
  url: https://push-tst2.coral.co.uk/push



df:
  baseUrl: https://cd-dev1.api.datafabric.dev.aws.ladbrokescoral.com
  apiKey: CD11beae13fa47459ba472e0b743822846
  loggingLevel: BASIC

masterlock:
  aws:
      dynamo.lock-table-name: CR-MSLOCKTABLE-DEV

app:
  nextRaces:
    timePeriodMinutes: 15
