import { ClubPromo, Fanzone, FzPreferences, IFanzoneNewSeason, IFzOptinEmail, Syc, INewSignPosting, IPopUp } from '@app/client/private/models/fanzone.model';

export const FANZONE_DETAILS = {
    active: 'Active',
    create: 'Create Fanzone',
    launchbanner: 'Launch Banner',
    fanzoneName: 'Fanzone Name',
    launchBannerUrl: 'Launch Banner URL',
    launchBannerUrlDesktop: 'Launch Banner URL for Desktop',
    launchBannerDescription: 'Launch Banner Description',
    ctaButton: 'CTA Button text',
    fanzoneDetails: 'Fanzone Details',
    teamId: 'Team ID',
    openBetId: 'Open Bet ID',
    fanzoneBanner: 'Fanzone Banner',
    fanzoneBannerDesktop: 'Fanzone Banner for Desktop',
    assetManagementLink: 'Asset Management Link',
    fanzoneDescription: 'Fanzone Description',
    primaryCompetitionId: 'Primary Competition ID',
    secondaryCompetitionId: 'Secondary Competition ID',
    clubIds: 'Club IDs',
    hexColorCode: 'Fanzone Widget Color',
    is21stOrUnlistedFanzoneTeam: '21st Team / Unlisted Fanzone Team',
};

export const FANZONE_ADDITIONAL = {
    fanzone: 'Fanzone',
    showNownNext: 'Show Now & Next',
    nextGamesLabel: 'Next Games Label',
    outRightsLabel: 'Outrights Label',
    premierLeagueLabel: 'Premier League Label',
    showCompetitionTable: 'Show Competition Table',
    showstats: 'Show Stats',
    showClubs: 'Show Clubs',
    showGames: 'Show Fanzone Games',
    showMenuInSportsRibbon: 'Show Menu in Sports Ribbon',
    showMenuInA_Z: 'Show Menu in A-Z',
    showLaunchBannerInHome: 'Show Launch Banner Home',
    showLaunchBannerInFootball: 'Show Launch Banner Football Page',
    showSlotRivals: 'Show Fanzone Slot Rivals',
    showScratchCards: 'Show Fanzone Scratch cards',
    showBetsBasedOnOtherFans :'Show Bets Based on Other Fanzone Team',
    showBetsBasedOnYourTeam : 'Show Bets Based On Your Team'   
};

export const FANZONE_LIST = {
    fanzonePage: 'Fanzone Page',
    createFanzone: 'Create Fanzone',
    searchForFanzone: 'Search For Fanzone'
};

export const FANZONE_CLUB = {
    active: 'Active',
    bannerLink: 'Banner Image Link',
    club: 'Fanzone Clubs',
    createClubPromotion: 'Create Club Promotion',
    description: 'Description',
    title: 'Title',
    saveClubs: 'Save Club'
};

export const SYC_POPUP_CONST = {
    sycHeading: 'SYC Pop Up Details',
    sycPopUpTitle: 'SYC Pop Up Title',
    sycPopUpDescription: 'SYC Pop Up Description',
    sycImage: 'SYC Pop Up Image Manager Name',
    remindLater: 'Remind Me Later CTA',
    remindLaterHideDays: 'No. of Days to Remind Later',
    okCTA: 'OK CTA',
    dontShowAgain: 'Don\'t Show Me This Again CTA',
    create: 'Create SYC Pop Up',
    update: 'Update SYC Pop Up',
    seasonDetails: 'Current Season Details',
    seasonStartDate: 'Current Season Start Date *',
    seasonEndDate: 'Current Season End Date *',
};

export const FZ_COMING_BACK_CONST = {
    id: '',
    brand: '',
    createdBy: '',
    createdAt: '',
    updatedBy: '',
    updatedAt: '',
    updatedByUserName: '', 
    createdByUserName: '',
    fzComingBackHeading: 'Fanzone Coming Soon',
    fzComingBackTitle: 'Title',
    fzComingBackDescription: 'Description',
    fzComingBackOKCTA: 'OK CTA',
    fzComingBackDisplayFromDays:'No of days before season starts',
    fzComingBackBgImage: 'Background image',
    active: 'Active',
    fzComingBackBadgeUrl: 'Badge Url'
}
export const FZ_NEW_SEASON_CONST: IFanzoneNewSeason = {
    id: '',
    brand: '',
    createdBy: '',
    createdAt: '',
    updatedBy: '',
    updatedAt: '',
    updatedByUserName: '', 
    createdByUserName: '',
    fzNewSeasonHeading: 'Fanzone On Vacation',
    fzNewSeasonTitle: 'Title',
    fzNewSeasonDescription: 'Description',
    fzNewSeasonBgImageDesktop: 'Background Image Desktop',
    fzNewSeasonBgImageMobile: 'Background Image Mobile',
    fzNewSeasonBadgeDesktop: 'Badge Desktop',
    fzNewSeasonBadgeMobile: 'Badge Mobile',
    fzNewSeasonLightningDesktop: 'Lightning Desktop',
    fzNewSeasonLightningMobile: 'Lightning Mobile'
}

export const SYC_SELECT_CONST = {
    sycHeading: 'SYC Page Details',
    sycPopUpCTAHeading: 'SYC Page Pop Up CTA\'s',
    sycPopUpTitles: 'SYC Page Pop Up Headers',
    sycPopUpMessages: 'SYC Page Pop Up Messages',
    sycTitle: 'SYC Page Title',
    sycDescription: 'SYC Description',
    sycConfirmCTA: 'Confirm',
    sycChangeCTA: 'Select Different Team',
    sycExitCTA: 'Exit',
    sycLoginCTA: 'Login',
    sycCancelCTA: 'Cancel',
    sycThankYouTitle: 'Thank You',
    sycConfirmTitle: 'Confirm',
    sycNoTeamSelectionTitle: 'I Don\'t Support',
    sycConfirmMsgMobile: 'Confirm for Mobile Device',
    sycConfirmMsgDesktop: 'Confirm for Desktop',
    sycPreLoginTeamSelectionMsg: 'Confirm for Not Logged In User',
    sycPreLoginNoTeamSelectionMsg: 'Confirm for Pre-Login No Team Selection',
    customTeamNameText: 'Confirm for No Team Selection',
    customTeamNameDescription: 'Description for No Team Selection',
    thankYouMsg: 'Thank You for No Team Selection',
    changeTeamTimePeriodMsg: 'Change Team Error Message',
    daysToChangeTeam: 'Days to Change Team',
};

export const FANZONE_OPTIN_EMAIL = {
    optinEmailHeading: 'Fanzone Optin Email',
    fanzoneEmailPopupTitle: 'Optin Email Pop Up Title',
    fanzoneEmailPopupDescription: 'Optin Email Pop Up Description',
    fanzoneEmailPopupOptIn: 'Opt In CTA',
    fanzoneEmailPopupRemindMeLater: 'Remind Me Later CTA',
    fanzoneEmailPopupDontShowThisAgain: 'Don\'t Show Me This Again CTA',
    create: 'Create Optin Email Pop Up',
    update: 'Update Optin Email Pop Up',
    seasonDetails: 'Current Season Details',
    seasonStartDate: 'Current Season Start Date *',
    seasonEndDate: 'Current Season End Date *',
};

export const FANZONE: Fanzone = {
    id: '',
    brand: '',
    active: true,
    launchBannerUrl: '',
    name: '',
    teamId: '',
    openBetID: '',
    fanzoneBanner: '',
    assetManagementLink: '',
    primaryCompetitionId: '',
    secondaryCompetitionId: '',
    clubIds: '',
    location: '',
    fanzoneConfiguration: {
        showNowNext: true,
        showStats: true,
        showClubs: true,
        sportsRibbon: true,
        atozMenu: true,
        homePage: true,
        footballHome: true,
        launchBannerUrlDesktop: '',
        fanzoneBannerDesktop: '',
        showBetsBasedOnYourTeam: true,
        showBetsBasedOnOtherFans: true,
    },
    nextGamesLbl: '',
    outRightsLbl: '',
    premierLeagueLbl: '',
    createdBy: '',
    createdByUserName: '',
    updatedBy: '',
    updatedByUserName: '',
    createdAt: '',
    updatedAt: '',
    is21stOrUnlistedFanzoneTeam: false,
};

export const CLUB: ClubPromo = {
    id: '',
    brand: '',
    active: true,
    title: '',
    bannerLink: '',
    description: '',
    validityPeriodStart: '',
    validityPeriodEnd: '',
    createdBy: '',
    createdByUserName: '',
    updatedBy: '',
    updatedByUserName: '',
    createdAt: '',
    updatedAt: '',
};

export const PREFERENCES_CONST = {
    active: 'Active',
    preferenceHeading: 'Fanzone Preference Center',
    pcDescription: 'Description',
    prefName: 'Preference Name',
    prefKey: 'Key Map Name',
    subscribeText: 'Un-Subscribe/Resign Text',
    ctaText: 'Submit Button Text',
    confirmText: 'Confirm Preferences Text',
    confirmCTA: 'Confirm CTA',
    exitCTA: 'Exit CTA',
    notificationPopupTitle: 'Notifications',
    unsubscribeTitle: 'Unsubscribe',
    notificationDescriptionDesktop: 'Desktop Notifications Info Message',
    unsubscribeDescription: 'Unsubscribe Message',
    pushPreferenceCentreTitle: 'Push Preference Center Title',
    optInCTA: 'Opt In CTA',
    noThanksCTA: 'No Thanks CTA',
    genericTeamNotificationTitle: '21st tile Notifications Title',
    genericTeamNotificationDescription: '21st tile Notifications Info Message',

}

export const SYC: Syc = {
    id: '',
    brand: '',
    pageName: '',
    sycPopUpTitle: '',
    sycPopUpDescription: '',
    sycImage: '',
    okCTA: '',
    remindLater: '',
    remindLaterHideDays: '',
    dontShowAgain: '',
    seasonStartDate: '',
    seasonEndDate: '',
    sycTitle: '',
    sycThankYouTitle: '',
    sycDescription: '',
    customTeamNameText: '',
    customTeamNameDescription: '',
    sycLoginCTA: '',
    sycConfirmCTA: '',
    sycChangeCTA: '',
    sycExitCTA: '',
    sycCancelCTA: '',
    sycConfirmTitle: '',
    sycNoTeamSelectionTitle: '',
    thankYouMsg: '',
    sycPreLoginTeamSelectionMsg: '',
    sycPreLoginNoTeamSelectionMsg: '',
    sycConfirmMsgMobile: '',
    sycConfirmMsgDesktop: '',
    changeTeamTimePeriodMsg: '',
    daysToChangeTeam: null,
    createdBy: '',
    createdByUserName: '',
    updatedBy: '',
    updatedByUserName: '',
    createdAt: '',
    updatedAt: '',
};

export const PREFERENCES: FzPreferences = {
    id: '',
    brand: '',
    createdBy: '',
    createdByUserName: '',
    updatedBy: '',
    updatedByUserName: '',
    createdAt: '',
    updatedAt: '',
    active: true,
    pcDescription: '',
    pcKeys: [],
    ctaText: '',
    subscribeText: '',
    confirmText: '',
    confirmCTA: '',
    exitCTA: '',
    notificationPopupTitle: '',
    unsubscribeTitle: '',
    notificationDescriptionDesktop: '',
    unsubscribeDescription: '',
    pushPreferenceCentreTitle: '',
    optInCTA: '',
    noThanksCTA: ''
}

export const NEWSIGNPOSTING:INewSignPosting = {
    pageName: '',
    active: true,
    newSignPostingIcon: '',
    startDate: '',
    endDate: '',
    id: '',
    brand: '',
    createdBy:'',
    createdAt: '',
    updatedBy:'',
    updatedAt:'',
    updatedByUserName:'',
    createdByUserName: ''
};

export const NEWSIGNPOSTING_CONST = {
    newSignPostingDetails: 'New Sign Posting Details',
    active: 'Active',
    newSignPostingIcon: null,
    startDate: 'New Sign Posting Start Date *',
    endDate: 'New Sign Posting End Date *',
};

export const FZ_POPUP:IPopUp = {
    pageName: '',
    title: '',
    description:'',
    closeCTA: '',
    playCTA: '',
    id: '',
    brand: '',
    createdBy:'',
    createdAt: '',  
    updatedBy:'',
    updatedAt:'',
    updatedByUserName:'',
    createdByUserName: ''
};

export const FZ_POPUP_CONST = {
    fzPopUpHeading: 'New Gaming Pop Up Details',
    title: 'Pop Up Title',
    description: 'Pop Up Description',
    closeCTA: 'Close CTA',
    playCTA: 'Play CTA'
};

export const OPTIN_EMAIL: IFzOptinEmail = {
    id: '',
    brand: '',
    pageName: '',
    createdBy: '',
    createdByUserName: '',
    updatedBy: '',
    updatedByUserName: '',
    createdAt: '',
    updatedAt: '',
    fanzoneEmailPopupTitle: '',
    fanzoneEmailPopupDescription: '',
    fanzoneEmailPopupOptIn: '',
    fanzoneEmailPopupRemindMeLater: '',
    fanzoneEmailPopupDontShowThisAgain: ''
}
