export const TopSportsConstants = {
    TOP_SPORTS: 'Top Sports',
    CREATE_NEW_TOPSPORTS: 'Create Top Sports',
    EDIT_TOP_SPORTS: 'Edit Top Sport:',
    SAVE_CHANGES: 'Save Changes',
    CREATE_TOP_SPORT: 'Create Top Sport',
    THRESHOLD_VALUE: 'Threshold value',
    DESKTOP_IMAGE_ID: 'Desktop Image ID',
    MOBILE_IMAGE_ID: 'Mobile Image ID',
    REVERT_CHANGES: 'Revert Changes',
    SIGNPOSTING: 'Signposting',
    ERROR_MESSAGE: '*This property should not exceed 100 characters',
    REMOVE: 'Remove',
    SPORT_NAME: 'Sport Name',
    THRESHOLD_TYPE: 'Threshold type',
    DECIMAL: 'Decimal',
    FRACTION: 'Fraction',
    REDIRECTION_URL: 'Redirection URL'
}

export const defaultTopSportsData = {
    id: '',
    createdBy: '',
    createdByUserName: '',
    updatedBy: '',
    updatedByUserName: '',
    createdAt: '',
    updatedAt: '',
    sortOrder: 0,
    brand: 'bma',
    sportsName: '',
    desktopImageId: '',
    mobileImageId: '',
    stockImageURL: '',
    signposting: '',
    isTopSports: true,
    topSports: true,
}