export const banners = [
    {
        Id: "{20274BEA-2016-4EA2-974B-C627440DEB46}",
        active: true,
        altText: "Reds Sportsbook",
        bannerStatus: true,
        brand: "ladbrokes",
        fetchpriority: "high",
        imgUrl: "https://scmedia.cms.test.env.works/$-$/fe905c3b065b4dd390f2e2e29080cfac.jpg",
        index: 0,
        introductorytext: "test banner 21st march",
        itemName: "21st%20march%20banner",
        link: "https://qa23.sports.ladbrokes.com/virtual-sports/sports/horse-racing/epsom-downs",
        subtitle: "",
        target: "",
        tcLink: "https://qa23.sports.ladbrokes.com/virtual-sports/sports/horse-racing/epsom-downs",
        tcTarget: "",
        tcText: "18+ terms and conditions",
        title: "virtual test banner",
        tracked: true,
    }, {
        Id: "{32CA7A3E-D96F-45A8-B89C-DDE3B9794559}",
        altText: "UFC 283",
        bannerStatus: true,
        brand: "ladbrokes",
        fetchpriority: "high",
        imgUrl: "https://scmedia.cms.test.env.works/$-$/43f6e1b94ea24b21a5dad25df95efa10.jpg",
        index: 1,
        introductorytext: "",
        itemName: "testpvirtuals",
        link: "https://qa23.sports.ladbrokes.com/virtual-sports/sports/greyhounds/",
        subtitle: "",
        target: "_self",
        tcLink: "https://qa23.sports.ladbrokes.com/virtual-sports/sports/greyhounds/",
        tcTarget: "",
        tcText: "",
        title: ""
    }
]