
class Lotto(object):
    """
    src/app/lazy-modules/locale/translations/en-US/lotto.lang.ts
    """
    LOTTO = 'Lotto'
    LOTTERY = 'Lottery'
    MARKETS = 'More Markets'
    OPTIONS = 'Options'
    BOOSTER_BALL = 'Include Bonus Ball?'
    HOW_LONG = 'How Long Would You Like To Play For?:'
    LUCKY_5 = 'Lucky 5'
    ODDS = 'Odds'
    STAKE = 'Stake'
    DRAW = 'Select Draw'
    BACK = 'Back'
    DAYS = 'Days,'
    HOURS = 'Hours,'
    MINUTES = 'Minutes'
    DAY = 'Day,'
    HOUR = 'Hour,'
    MINUTE = 'Minute'
    UPTO = '- bet until'
    FINISHED = ' Bet was finished at '
    CHOOSE = 'Choose Your Lucky Numbers Below'
    LUCKYDIP = 'Choose your lucky dip'
    SERVER_ERROR = 'Server is unavailable at the moment, please try again later.'
    ERROR_SERVICE_DEPARTMENT_MESSAGE = 'If this problem persists, contact our '
    ERROR_SERVICE_DEPARTMENT_LINK = 'Customer Service Department'
    RELOAD = 'Reload'

    DRAW_TIME = 'Draw date:'
    BET_TYPE_DESC = 'Bet Type:'
    BET_SELECTIONS = 'Bet Selections:'
    BET_ODDS = 'Bet Odds:'
    BET_STAKE = 'Stake:'
    TOTAL_STAKE = 'Total Stake:'
    BET_POTENTIAL_WINS = 'Potential return:'
    BET_PLACED = 'Bet Placed:'
    LOTTO_RECEIPT = 'Bet Receipt'
    DONE = 'Done'

    MATCH = 'Match (%match)'

    STRAIGHT = 'Straight'
    COMBO = 'Combo'
    RESULTS = 'Results'

    ERROR = 'Error'
    WARNING = 'Warning!'

    INTERNAL_ERROR = 'Internal error occurred'
    EVENT_ERROR = 'Event not found'
    VALIDATION_ERROR = 'Please select a draw.'
    BET_ERROR = 'Bet error occurred'
    NO_FUNDS = 'Insufficient Funds to place a bet'

    WEEK = '1 Week'
    TWO_WEEKS = '2 Weeks'
    THREE_WEEKS = '3 Weeks'
    FOUR_WEEKS = '4 Weeks'
    PLACE_BET = 'Place bet for '
    CONFIRM = 'Confirm ?'
    RESET = 'Reset Numbers'
    SAVE_FAV = 'Save to Favourites'

    BY_LOTTO = 'By Lotto'
    BY_TIME = 'By Time'
    TODAY = 'Today'
    YESTERDAY = 'Yesterday'
    BONUS_BALL = 'Bonus Ball'
    LOAD_MORE = 'Load More'

    SUBSCRIPTION_MESSAGE = 'Other subscribed lines for these draws will appear in your my bets area within the next 24hrs.'