
class Olympics(object):
    """
    src/app/lazy-modules/locale/translations/en-US/ol.lang.ts
    """
    OLYMPICS = 'Olympics'
    ARCHERY = 'Archery'
    ATHLETICS = 'Athletics'
    BADMINTON = 'Badminton'
    BASKETBALL = 'Basketball'
    BEACHVOLLEYBALL = 'Beach Volleyball'
    BEACHSOCCER = 'Beach Soccer'
    BOXING = 'Boxing'
    CANOEING = 'Canoeing'
    CYCLING = 'Cycling'
    DIVING = 'Diving'
    ESPORTS = 'Esports'
    EQUESTRIAN = 'Equestrian'
    FENCING = 'Fencing'
    FOOTBALL = 'Football'
    GAA = 'GAA'
    GOLF = 'Golf'
    GYMNASTICS = 'Gymnastics'
    HANDBALL = 'Handball'
    HOCKEY = 'Hockey'
    JUDO = 'Judo'
    MODERNPENTATHLON = 'Modern Pentathlon'
    OLYMPIC__SPECIALS = 'Olympic Specials'
    ROWING = 'Rowing'
    RUGBYUNION = 'Rugby Union'
    SAILING = 'Sailing'
    SHOOTING = 'Shooting'
    SPORTMULTIPLES = 'Sport Multiples'
    SWIMMING = 'Swimming'
    SYNCHRONISEDSWIMMING = 'Syn Swimming'
    TABLETENNIS = 'Table Tennis'
    TAEKWONDO = 'Taekwondo'
    TENNIS = 'Tennis'
    TRIATHLON = 'Triathlon'
    VOLLEYBALL = 'Volleyball'
    WATERPOLO = 'Water Polo'
    WINTERSPORTS = 'Winter Sports'
    WEIGHTLIFTING = 'Weight Lifting'
    WRESTLING = 'Wrestling'