version: 1
disable_existing_loggers: False
loggers:
  crlat_gvc_wallet_client:
    level: INFO
    handlers: [console]
formatters:
  default:
    format: '%(asctime)s.%(msecs)03d: %(levelname)-8s %(name)s.%(module)s.%(funcName)-10s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class : logging.StreamHandler
    formatter: default
    level : DEBUG
