//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 09:48:45 PM EEST 
//


package com.egalacoral.api.ws.identity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for idpRequestType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="idpRequestType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="verifycredential"/>
 *     &lt;enumeration value="authenticate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "idpRequestType")
@XmlEnum
public enum IdpRequestType {

    @XmlEnumValue("verifycredential")
    VERIFYCREDENTIAL("verifycredential"),
    @XmlEnumValue("authenticate")
    AUTHENTICATE("authenticate");
    private final String value;

    IdpRequestType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IdpRequestType fromValue(String v) {
        for (IdpRequestType c: IdpRequestType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
