export const onboardingConstants = {
    Onboarding_Betpack : 'Onboarding Betpack',
    Onboarding : 'Onboarding',
    Onboarding_Images : 'Onboarding Images',
    Active : 'Active',
    Create_Onboarding_Betpack : 'Add Image',
    Save_Changes : 'Save Changes',
    Create_Onboarding_Image : 'Create Onboarding Image',
    Image_Type : 'Image Type*',
    BetReview : 'BetReview',
    Upload_Image : 'Upload Image*',
    Upload_Image_File : 'Upload Image',
    Remove_Image : 'Remove Image',
    Uploaded_Image_Label : 'Uploaded Image Label*',
    Next_CTA_Button_Label : 'Next CTA Button Label*',
    Add : 'Add',
    Revert_Changes : 'Revert Changes',
    Error_Massage : '*This property should not exceed 50 characters',
    Edit_Onboarded_Image : 'Edit Onboarded Image:',
    Remove : 'Remove',
    Start_Date_Error: 'Start Date cannot be past date than current date',
    Start_Date_Change: 'Start Date cannot be modified after bet pack starts',
    End_Date_Error: 'End date should be greater than start date'
};
