export const RULES_MOCK: string = `<!-- Five A Side Rules Area -->
<div class="five-a-side-rules"><!-- Rules Link --> <a class="rules-btn" style="float: right; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; text-decoration: none; width: 32px; margin: 4px 0 15px 0; font-size: 12px; font-weight: 500; color: #007aff;" title="Rules">Rules</a> <!-- Header-->
<p class="terms-rules-header" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; margin: 4px 0 12px 0; font-size: 18px; font-weight: bold; color: #e3e3e3;">5-A-Side Leaderboard</p>
<!-- Rules information Section 1 -->
<div id="rules-container">
<div class="rules-parent" style="background-color: #1a2532; padding: 8px; border-radius: 4px;">
<div class="rules-info-1" style="display: flex; margin-top: 15px; margin-bottom: 15px; align-items: center; justify-content: center;">
<p class="icon-content" style="width: 15%;"><img src="http:/cms-dev0.ladbrokes.com/cms/images/uploads/wysiwyg_uploads/staticblocks/6024cf10c08d9a0f8db8db65/0d4af52f-25d7-4e26-9f16-6ce985d1052f.svg" alt="coins" width="30" height="30" /></p>
<p class="text-content min-amount" style="width: 85%; font-size: 13px; letter-spacing: -0.16px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #e3e3e3;">Place a minimum &pound;{minAmount} 5-A-Side bet with 5 players</p>
</div>
<!-- Rules information Section 2 -->
<div class="rules-info-2" style="display: flex; margin-bottom: 15px; align-items: center; justify-content: center;">
<p class="icon-content" style="width: 15%; margin-bottom: 0px;"><img src="http:/cms-dev0.ladbrokes.com/cms/images/uploads/wysiwyg_uploads/staticblocks/6024cf10c08d9a0f8db8db65/3dc7ec7a-a8b8-488a-b332-3d6c5d47b1b9.svg" alt="Users" width="30" height="30" /></p>
<p class="text-content" style="width: 85%; font-size: 13px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; letter-spacing: -0.16px; color: #e3e3e3;">Teams are ranked by the highest to lowest priced winning bets, then all losing bets by highest percentage complete</p>
</div>
<!-- Rules information Section 3 -->
<div class="rules-info-3" style="display: flex; margin-bottom: 15px; align-items: center; justify-content: center;">
<p class="icon-content" style="width: 15%;"><img src="http:/cms-dev0.ladbrokes.com/cms/images/uploads/wysiwyg_uploads/staticblocks/6024cf10c08d9a0f8db8db65/350b6b55-5acb-44f7-992c-0c89815f709f.svg" alt="Ranking" width="30" height="30" /></p>
<div class="text-content" style="width: 85%;">
<p class="entries-per-user" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 13px; letter-spacing: -0.16px; color: #e3e3e3;"><span class="user-entries-normal">Maximum {maxUserEntries} entries per user</span> (<span class="user-entries-bold" style="font-weight: bold;">{betsPlaced}/{maxUserEntries}</span>)</p>
<p class="total-entries" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 13px; letter-spacing: -0.16px; color: #e3e3e3;"><span class="total-entries-normal">Maximum {maxContestEntries} total entries</span> (<span class="total-entries-bold" style="font-weight: bold;">{currentContestEntries}/{maxContestEntries}</span>)</p>
</div>
</div>
</div>
</div>
<!-- Build team Action -->
<div class="build-btn" style="font-weight: bold; font-size: 15px; height: 44px; color: #ffffff; border-radius: 2px; background-color: #8bbd23; text-align: center; text-transform: uppercase; cursor: pointer; line-height: 44px; margin-top: 10px;">Build a Team</div>
<div style="display: flex; align-items: center; justify-content: center; margin-top: 24px;"><span class="return-to-lobby" style="cursor: pointer; font-family: Roboto; font-size: 12px; font-weight: bold; font-stretch: condensed; font-style: normal; line-height: normal; letter-spacing: normal; color: #007aff;">RETURN TO LOBBY</span></div>
</div>`;

export const CONTEST_DATA = {
    'id': '6048b84f4ee96965f34b5aa6',
    'createdBy': '54905d04a49acf605d645271',
    'createdByUserName': 'test.admin@coral.co.uk',
    'updatedBy': '5645b8a220bd9e0800afdc57',
    'updatedByUserName': 'qa@coral.co.uk',
    'createdAt': '2021-02-03T12:40:50.906Z',
    'updatedAt': '2021-02-11T08:46:48.909Z',
    'sortOrder': -11.0,
    'generatedId': '10037',
    'name': 'contesttwo',
    'icon': null,
    'startDate': '2021-02-03T12:40:45.423Z',
    'event': null,
    'entryStake': '3',
    'isFreeBetsAllowed': true,
    'prizePool': {
        'cash': '24',
        'firstPlace': '100',
        'freeBets': null,
        'vouchers': '20',
        'summary': null,
        'tickets': '20',
        'totalPrizes': '234'
    },
    'contestPrizes': null,
    'sponsorText': null,
    'sponsorLogo': null,
    'size': 1000,
    'teams': 6,
    'description': null,
    'blurb': `<p>England host Scotland in the Battle of Britain with a place in the last 16 up for grabs for the winner.
     The Scots will be out for revenge after a 3-0 thrashing back in 2019.</p>`,
    'entryConfirmationText': null,
    'nextContestId': null,
    'display': true,
    'brand': 'ladbrokes'
};

export const USER_SHOWDOWN_DATA = {
    "id": "61f653b221b3106474a6550f",
    "name": "1722516 - Stale data 30/1",
    "startDate": "2022-01-30T08:59:50.836Z",
    "utcStartDate": "2022-01-30T08:59:50Z",
    "event": "1722516",
    "entryStake": "0.1",
    "contestSize": 150,
    "userContestSize": 49,
    "entriesSize": "0",
    "size": "150",
    "teams": "50",
    "description": "description",
    "eventDetails": {
      "id": "1722516",
      'categoryCode': 'FOOTBALL',
      'categoryName': '|Football|',
      'className': 'Football Auto Test',
      'typeName': '2. Autotest League',
      "sequenceId": 15,
      'name': 'England v Scotland',
      "startTime": "10:30 10th March 2021",
      "clock": {
        "clockTime": "95:47",
        "lastUpdate": "2022-04-14T13:49:59.933Z",
        "periodCode": "FINISH",
        "clockSeconds": 5747,
        "lastUpdateSecs": 1649944199,
        "startTimeSecs": 1647007597,
        "clockRunning": false
      },
      "scores": {
        "home": {
          "name": "Manchester United FC",
          "score": 12
        },
        "away": {
          "name": "Southampton FC",
          "score": 11
        }
      },
      "started": true,
      "regularTimeFinished": false
    },
    "entries": [
      {
        "updatedAt": "2022-01-30T10:57:52.354+00:00",
        "id": "2147618576",
        "contestId": "61f653b221b3106474a6550f",
        "index": 0,
        "userId": "testgvcld_pooji",
        "eventId": "1722516",
        "receiptId": "O/300076231/0000149",
        "outcomeIds": [
          "149174491",
          "149174519",
          "149174522",
          "149174520",
          "149174521"
        ],
        "stake": "0.1",
        "odd": 0,
        "voided": false,
        "priceNum": "40",
        "priceDen": "1",
        "overallProgressPct": 0,
        "counterFlag": true,
        "legs": [
          {
            "updatedAt": "2022-02-07T00:46:33.259+00:00",
            "outcomeId": "149174491",
            "sequenceId": "3",
            "voided": false,
            "eventId": "1722516",
            "outcomeName": "MARTIAL TO HAVE 20 OR MORE PASSES",
            "optaStatValue": "45",
            "statValue": ">=20",
            "progressPct": 100,
            "marketName": "BUILD YOUR BET PLAYER TOTAL PASSES",
            "homeAway": "away",
            "teamName": "Man Utd",
            "contestantId": "6eqit8ye8aomdsrrq0hk3v7gh",
            "playerId": "3ikhefktnj44ys7rqjzr5q09h",
            "statCategory": "Passes",
            "marketId": "40564106"
          },
          {
            "updatedAt": "2022-02-07T00:46:33.302+00:00",
            "outcomeId": "149174519",
            "sequenceId": "3",
            "voided": false,
            "eventId": "1722516",
            "outcomeName": "DALOT TO HAVE 2 OR MORE TACKLES",
            "optaStatValue": "0",
            "statValue": ">=2",
            "progressPct": 0,
            "marketName": "BUILD YOUR BET PLAYER TOTAL TACKLES",
            "homeAway": "away",
            "teamName": "Man Utd",
            "contestantId": "6eqit8ye8aomdsrrq0hk3v7gh",
            "playerId": "3f3jcsa7gk6in9fskp9w5a5t5",
            "statCategory": "Tackles",
            "marketId": "40564107"
          },
          {
            "outcomeId": "149174520",
            "sequenceId": "0",
            "voided": false,
            "eventId": "1722516",
            "outcomeName": "A. ARMSTRONG TO HAVE 2 OR MORE SHOTS",
            "statValue": ">=2",
            "progressPct": 0,
            "marketName": "BUILD YOUR BET PLAYER TOTAL SHOTS",
            "contestantId": "d5ydtvt96bv7fq04yqm2w2632",
            "playerId": "dusjrdiyxfadenwx4pjr7catx",
            "statCategory": "Shots",
            "marketId": "40564108"
          },
          {
            "updatedAt": "2022-01-30T12:07:33.744+00:00",
            "outcomeId": "149174521",
            "sequenceId": "6",
            "voided": false,
            "eventId": "1722516",
            "outcomeName": "WALKER-PETERS TO HAVE 1 OR MORE ASSISTS",
            "optaStatValue": "0",
            "statValue": ">=1",
            "progressPct": 0,
            "marketName": "BUILD YOUR BET PLAYER TOTAL ASSISTS",
            "homeAway": "away",
            "teamName": "Southampton FC",
            "contestantId": "d5ydtvt96bv7fq04yqm2w2632",
            "playerId": "2uiza5b6fbum38chxtvmnkzqh",
            "statCategory": "Assists",
            "marketId": "40564109"
          },
          {
            "outcomeId": "149174522",
            "sequenceId": "0",
            "voided": false,
            "eventId": "1722516",
            "outcomeName": "M. KOVÁŘ TO CONCEDE 2 OR MORE GOALS",
            "statValue": ">=2",
            "progressPct": 0,
            "marketName": "BUILD YOUR BET PLAYER TOTAL GOALS CONCEDED",
            "contestantId": "6eqit8ye8aomdsrrq0hk3v7gh",
            "playerId": "cs4aca71qkt1ru20ppmi6djl6",
            "statCategory": "GoalConceded",
            "marketId": "40564112"
          }
        ]
      },
      {
        "updatedAt": "2022-01-30T10:57:52.357+00:00",
        "id": "2147618583",
        "contestId": "61f653b221b3106474a6550f",
        "index": 0,
        "userId": "testgvcld_pooji",
        "eventId": "1722516",
        "receiptId": "O/300076231/0000151",
        "outcomeIds": [
          "149174511",
          "149174531",
          "149174530",
          "149174508",
          "149174505"
        ],
        "stake": "0.1",
        "odd": 0,
        "voided": false,
        "priceNum": "13",
        "priceDen": "2",
        "overallProgressPct": 0,
        "counterFlag": true,
        "legs": [
          {
            "updatedAt": "2022-01-30T12:07:33.797+00:00",
            "outcomeId": "149174505",
            "sequenceId": "6",
            "voided": false,
            "eventId": "1722516",
            "outcomeName": "C. ADAMS TO HAVE 20 OR MORE PASSES",
            "optaStatValue": "10",
            "statValue": ">=20",
            "progressPct": 50,
            "marketName": "BUILD YOUR BET PLAYER TOTAL PASSES",
            "homeAway": "away",
            "teamName": "Southampton FC",
            "contestantId": "d5ydtvt96bv7fq04yqm2w2632",
            "playerId": "59ujnkvl7rlffomi2bqpsmbpx",
            "statCategory": "Passes",
            "marketId": "40564106"
          },
          {
            "outcomeId": "149174508",
            "sequenceId": "0",
            "voided": false,
            "eventId": "1722516",
            "outcomeName": "A. ARMSTRONG TO HAVE 25 OR MORE PASSES",
            "statValue": ">=25",
            "progressPct": 0,
            "marketName": "BUILD YOUR BET PLAYER TOTAL PASSES",
            "contestantId": "d5ydtvt96bv7fq04yqm2w2632",
            "playerId": "dusjrdiyxfadenwx4pjr7catx",
            "statCategory": "Passes",
            "marketId": "40564106"
          },
          {
            "outcomeId": "149174511",
            "sequenceId": "0",
            "voided": false,
            "eventId": "1722516",
            "outcomeName": "VAN DE BEEK TO HAVE 2 OR MORE SHOTS",
            "statValue": ">=2",
            "progressPct": 0,
            "marketName": "BUILD YOUR BET PLAYER TOTAL SHOTS",
            "contestantId": "6eqit8ye8aomdsrrq0hk3v7gh",
            "playerId": "6gruusc463fdln5uz1uzhne8l",
            "statCategory": "Shots",
            "marketId": "40564108"
          },
          {
            "outcomeId": "149174530",
            "sequenceId": "0",
            "voided": false,
            "eventId": "1722516",
            "outcomeName": "SANCHO TO HAVE 40 OR MORE PASSES",
            "statValue": ">=40",
            "progressPct": 0,
            "marketName": "BUILD YOUR BET PLAYER TOTAL PASSES",
            "contestantId": "6eqit8ye8aomdsrrq0hk3v7gh",
            "playerId": "cv8egyrq9dlfgeamk6b7fdgq1",
            "statCategory": "Passes",
            "marketId": "40564106"
          },
          {
            "updatedAt": "2022-01-30T12:07:33.591+00:00",
            "outcomeId": "149174531",
            "sequenceId": "6",
            "voided": false,
            "eventId": "1722516",
            "outcomeName": "D.HENDERSON TO KEEP A CLEAN SHEET - NO",
            "statValue": ">=1",
            "progressPct": -1,
            "marketName": "BUILD YOUR BET PLAYER TO KEEP A CLEAN SHEET",
            "homeAway": "home",
            "teamName": "Manchester United FC",
            "contestantId": "6eqit8ye8aomdsrrq0hk3v7gh",
            "playerId": "5z8ycnd0smdkumi5fgtzf7c9h",
            "statCategory": "GoalConceded",
            "marketId": "40564110"
          }
        ]
      }
    ],
    "isInvitationalContest": false,
    "isPrivateContest": false
  } as any;
  
export const USER_SHOWDOWN_DATA_NULL = {
    'contestDto': {
        'id': '601a99d2a3a4e26cc6696eb4',
        'createdBy': '54905d04a49acf605d645271',
        'createdByUserName': 'test.admin@coral.co.uk',
        'updatedBy': '5645b8a220bd9e0800afdc57',
        'updatedByUserName': 'qa@coral.co.uk',
        'createdAt': '2021-02-03T12:40:50.906Z',
        'updatedAt': '2021-02-11T08:46:48.909Z',
        'sortOrder': -11.0,
        'generatedId': '10037',
        'name': 'contesttwo',
        'icon': null,
        'startDate': '2021-02-03T12:40:45.423Z',
        'event': null,
        'entryStake': '3',
        'isFreeBetsAllowed': true,
        'prizePool': {
            'cash': '24',
            'firstPlace': '100',
            'freeBets': null,
            'vouchers': '20',
            'summary': null,
            'tickets': '20',
            'totalPrizes': '234'
        },
        'contestPrizes': null,
        'sponsorText': null,
        'sponsorLogo': null,
        'size': 1000,
        'teams': 6,
        'description': '',
        'blurb': `<p>England host Scotland in the Battle of Britain with a place in the last 16 up for grabs for the winner.
         The Scots will be out for revenge after a 3-0 thrashing back in 2019.</p>`,
        'entryConfirmationText': null,
        'nextContestId': null,
        'display': true,
        'brand': 'ladbrokes',
        'events': []
    },
    userContestSize: 0,
    contestSize: 500
} as any;

export const USER_SHOWDOWN_DATA_NO_DISPLAY = {
    'contestDto': {
        'id': '601a99d2a3a4e26cc6696eb4',
        'createdBy': '54905d04a49acf605d645271',
        'createdByUserName': 'test.admin@coral.co.uk',
        'updatedBy': '5645b8a220bd9e0800afdc57',
        'updatedByUserName': 'qa@coral.co.uk',
        'createdAt': '2021-02-03T12:40:50.906Z',
        'updatedAt': '2021-02-11T08:46:48.909Z',
        'sortOrder': -11.0,
        'generatedId': '10037',
        'name': 'contesttwo',
        'icon': null,
        'startDate': '2021-02-03T12:40:45.423Z',
        'event': null,
        'entryStake': '3',
        'isFreeBetsAllowed': true,
        'prizePool': {
            'cash': '24',
            'firstPlace': '100',
            'freeBets': null,
            'vouchers': '20',
            'summary': null,
            'tickets': '20',
            'totalPrizes': '234'
        },
        'contestPrizes': null,
        'sponsorText': null,
        'sponsorLogo': null,
        'size': 1000,
        'teams': 6,
        'description': '',
        'blurb': `<p>England host Scotland in the Battle of Britain with a place in the last 16 up for grabs for the winner.
         The Scots will be out for revenge after a 3-0 thrashing back in 2019.</p>`,
        'entryConfirmationText': null,
        'nextContestId': null,
        'display': false,
        'brand': 'ladbrokes',
        'events': []
    },
    'prizeMap': {
      cash: '1000',
      totalPrizes: 4,
      prizeMap: {
        '1': [{
            id: '602bda9afd5fbd33fa5174d1',
            createdBy: 'string',
            createdByUserName: null,
            updatedBy: 'string',
            updatedByUserName: null,
            createdAt: '2021-02-16T14:45:46.751Z',
            updatedAt: '2021-02-16T14:45:46.751Z',
            contestId: '602bcf5c95f74d1c927e9595',
            type: 'cash',
            value: '10',
            text: '',
            icon: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            signPosting: {
              filename: '',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            percentageOfField: 'string',
            numberOfEntries: '1-100',
            brand: 'bma',
          },
          {
            id: '602bda9afd5fbd33fa5174d1',
            createdBy: 'string',
            createdByUserName: null,
            updatedBy: 'string',
            updatedByUserName: null,
            createdAt: '2021-02-16T14:45:46.751Z',
            updatedAt: '2021-02-16T14:45:46.751Z',
            contestId: '602bcf5c95f74d1c927e9595',
            type: 'freebet',
            value: '10',
            text: '',
            icon: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            signPosting: {
              filename: '',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            percentageOfField: 'string',
            numberOfEntries: '1-100',
            brand: 'bma',
          },
          {
            id: '602bda9afd5fbd33fa5174d1',
            createdBy: 'string',
            createdByUserName: null,
            updatedBy: 'string',
            updatedByUserName: null,
            createdAt: '2021-02-16T14:45:46.751Z',
            updatedAt: '2021-02-16T14:45:46.751Z',
            contestId: '602bcf5c95f74d1c927e9595',
            type: 'ticket',
            value: '10',
            text: '',
            icon: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            signPosting: {
              filename: '',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            percentageOfField: 'string',
            numberOfEntries: '1-100',
            brand: 'bma',
          },
          {
            id: '602bda9afd5fbd33fa5174d1',
            createdBy: 'string',
            createdByUserName: null,
            updatedBy: 'string',
            updatedByUserName: null,
            createdAt: '2021-02-16T14:45:46.751Z',
            updatedAt: '2021-02-16T14:45:46.751Z',
            contestId: '602bcf5c95f74d1c927e9595',
            type: 'voucher',
            value: '10',
            text: '',
            icon: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            signPosting: {
              filename: '',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            percentageOfField: 'string',
            numberOfEntries: '1-100',
            brand: 'bma',
          },
        ],
        '1-100': [{
            id: '602bda9afd5fbd33fa5174d1',
            createdBy: 'string',
            createdByUserName: null,
            updatedBy: 'string',
            updatedByUserName: null,
            createdAt: '2021-02-16T14:45:46.751Z',
            updatedAt: '2021-02-16T14:45:46.751Z',
            contestId: '602bcf5c95f74d1c927e9595',
            type: 'cash',
            value: '10',
            text: '',
            icon: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            signPosting: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            percentageOfField: 'string',
            numberOfEntries: '1-100',
            brand: 'bma',
          },
          {
            id: '602bda9afd5fbd33fa5174d1',
            createdBy: 'string',
            createdByUserName: null,
            updatedBy: 'string',
            updatedByUserName: null,
            createdAt: '2021-02-16T14:45:46.751Z',
            updatedAt: '2021-02-16T14:45:46.751Z',
            contestId: '602bcf5c95f74d1c927e9595',
            type: 'freebet',
            value: '10',
            text: '',
            icon: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            signPosting: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            percentageOfField: 'string',
            numberOfEntries: '1-100',
            brand: 'bma',
          },
          {
            id: '602bda9afd5fbd33fa5174d1',
            createdBy: 'string',
            createdByUserName: null,
            updatedBy: 'string',
            updatedByUserName: null,
            createdAt: '2021-02-16T14:45:46.751Z',
            updatedAt: '2021-02-16T14:45:46.751Z',
            contestId: '602bcf5c95f74d1c927e9595',
            type: 'ticket',
            value: '10',
            text: '',
            icon: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            signPosting: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            percentageOfField: 'string',
            numberOfEntries: '1-100',
            brand: 'bma',
          },
          {
            id: '602bda9afd5fbd33fa5174d1',
            createdBy: 'string',
            createdByUserName: null,
            updatedBy: 'string',
            updatedByUserName: null,
            createdAt: '2021-02-16T14:45:46.751Z',
            updatedAt: '2021-02-16T14:45:46.751Z',
            contestId: '602bcf5c95f74d1c927e9595',
            type: 'voucher',
            value: '10',
            text: '',
            icon: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            signPosting: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            percentageOfField: 'string',
            numberOfEntries: '1-100',
            brand: 'bma',
          },
        ],
        '2': [{
            id: '602bda9afd5fbd33fa5174d1',
            createdBy: 'string',
            createdByUserName: null,
            updatedBy: 'string',
            updatedByUserName: null,
            createdAt: '2021-02-16T14:45:46.751Z',
            updatedAt: '2021-02-16T14:45:46.751Z',
            contestId: '602bcf5c95f74d1c927e9595',
            type: 'cash',
            value: '',
            text: 'this is text',
            icon: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            signPosting: {
              filename: '',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            percentageOfField: 'string',
            numberOfEntries: '1-100',
            brand: 'bma',
          },
          {
            id: '602bda9afd5fbd33fa5174d1',
            createdBy: 'string',
            createdByUserName: null,
            updatedBy: 'string',
            updatedByUserName: null,
            createdAt: '2021-02-16T14:45:46.751Z',
            updatedAt: '2021-02-16T14:45:46.751Z',
            contestId: '602bcf5c95f74d1c927e9595',
            type: 'freebet',
            value: '',
            text: 'this is text',
            icon: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            signPosting: {
              filename: '',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            percentageOfField: 'string',
            numberOfEntries: '1-100',
            brand: 'bma',
          },
          {
            id: '602bda9afd5fbd33fa5174d1',
            createdBy: 'string',
            createdByUserName: null,
            updatedBy: 'string',
            updatedByUserName: null,
            createdAt: '2021-02-16T14:45:46.751Z',
            updatedAt: '2021-02-16T14:45:46.751Z',
            contestId: '602bcf5c95f74d1c927e9595',
            type: 'ticket',
            value: '',
            text: 'this is text',
            icon: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            signPosting: {
              filename: '',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            percentageOfField: 'string',
            numberOfEntries: '1-100',
            brand: 'bma',
          },
          {
            id: '602bda9afd5fbd33fa5174d1',
            createdBy: 'string',
            createdByUserName: null,
            updatedBy: 'string',
            updatedByUserName: null,
            createdAt: '2021-02-16T14:45:46.751Z',
            updatedAt: '2021-02-16T14:45:46.751Z',
            contestId: '602bcf5c95f74d1c927e9595',
            type: 'voucher',
            value: '',
            text: 'this is text',
            icon: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            signPosting: {
              filename: '',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            percentageOfField: 'string',
            numberOfEntries: '1-100',
            brand: 'bma',
          },
        ],
        '3': [{
            id: '602bda9afd5fbd33fa5174d1',
            createdBy: 'string',
            createdByUserName: null,
            updatedBy: 'string',
            updatedByUserName: null,
            createdAt: '2021-02-16T14:45:46.751Z',
            updatedAt: '2021-02-16T14:45:46.751Z',
            contestId: '602bcf5c95f74d1c927e9595',
            type: 'cash',
            value: '',
            text: 'this is text',
            icon: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            signPosting: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            percentageOfField: 'string',
            numberOfEntries: '1-100',
            brand: 'bma',
          },
          {
            id: '602bda9afd5fbd33fa5174d1',
            createdBy: 'string',
            createdByUserName: null,
            updatedBy: 'string',
            updatedByUserName: null,
            createdAt: '2021-02-16T14:45:46.751Z',
            updatedAt: '2021-02-16T14:45:46.751Z',
            contestId: '602bcf5c95f74d1c927e9595',
            type: 'freebet',
            value: '',
            text: 'this is text',
            icon: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            signPosting: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            percentageOfField: 'string',
            numberOfEntries: '1-100',
            brand: 'bma',
          },
          {
            id: '602bda9afd5fbd33fa5174d1',
            createdBy: 'string',
            createdByUserName: null,
            updatedBy: 'string',
            updatedByUserName: null,
            createdAt: '2021-02-16T14:45:46.751Z',
            updatedAt: '2021-02-16T14:45:46.751Z',
            contestId: '602bcf5c95f74d1c927e9595',
            type: 'ticket',
            value: '',
            text: 'this is text',
            icon: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            signPosting: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            percentageOfField: 'string',
            numberOfEntries: '1-100',
            brand: 'bma',
          },
          {
            id: '602bda9afd5fbd33fa5174d1',
            createdBy: 'string',
            createdByUserName: null,
            updatedBy: 'string',
            updatedByUserName: null,
            createdAt: '2021-02-16T14:45:46.751Z',
            updatedAt: '2021-02-16T14:45:46.751Z',
            contestId: '602bcf5c95f74d1c927e9595',
            type: 'voucher',
            value: '',
            text: 'this is text',
            icon: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            signPosting: {
              filename: '67f282ab-a986-4205-872c-b3f391a23d5f.svg',
              originalname: 'string',
              path: 'string',
              size: 'string',
              filetype: 'string',
              svgId: 'string',
            },
            percentageOfField: 'string',
            numberOfEntries: '1-100',
            brand: 'bma',
          },
        ],
      },
    },
    userContestSize: 0,
    contestSize: 500
} as any;
export const CONTEST_DTO_NULL = {
    userContestSize: 0,
    contestSize: 0
} as any;
