'use strict';

/* tslint-disable quote-props */

export const lotteriesConfig = {
  tst: {
    '1': { country: 'Ireland', inConnect: true, color: '#85d947' },
    '2': { country: 'Ireland', inConnect: true, color: '#85d947' },
    '3': { country: 'UK', limits: 2, inConnect: true, color: 'multi' },
    '4': { country: 'UK', limits: 2, inConnect: true, color: 'multi' },
    '5': { country: 'Spainish', inConnect: true, color: '#4497ec' },
    '6': { country: 'USA', inConnect: true, color: '#4497ec' },
    '7': { country: 'UK', excluded: true },
    '8': { country: 'USA', inConnect: true, color: '#4497ec' },
    '9': { country: 'Spainish', inConnect: true, color: '#4497ec' },
    '10': { country: 'Daily Millions', limits: 4, inConnect: true, color: '#85d947' },
    '11': { country: 'Daily Millions', limits: 4, inConnect: true, color: '#85d947' },
    '12': { country: 'Singapore' },
    '13': { country: 'Singapore' },
    '14': { country: 'France' },
    '15': { country: 'Hong Kong' },
    '16': { country: 'Hong Kong' },
    '17': { country: 'Australia' },
    '18': { country: 'Australia' },
    '19': { country: 'German' },
    '20': { country: 'German', excluded: true },
    '21': { country: 'Canadian' },
    '22': { country: 'Canadian' },
    '23': { country: 'Greek' },
    '24': { country: 'UK' },
    '25': { country: 'UK' },
    '26': { country: 'UK', excluded: true },
    '27': { country: 'UK', excluded: true },
    '28': { country: 'Euro' }
  },
  prod: {
    '1': { country: 'Ireland', inConnect: true, color: '#85d947' },
    '2': { country: 'Ireland', inConnect: true, color: '#85d947' },
    '3': { country: 'UK', limits: 2, inConnect: true, color: 'multi' },
    '4': { country: 'UK', limits: 2, inConnect: true, color: 'multi' },
    '5': { country: 'Spainish', inConnect: true, color: '#4497ec' },
    '6': { country: 'USA', inConnect: true, color: '#4497ec' },
    '7': { country: 'UK', excluded: true },
    '8': { country: 'USA', inConnect: true, color: '#4497ec' },
    '9': { country: 'Spainish', inConnect: true, color: '#4497ec' },
    '10': { country: 'Daily Millions', limits: 4, inConnect: true, color: '#85d947' },
    '11': { country: 'Daily Millions', limits: 4, inConnect: true, color: '#85d947' },
    '12': { country: 'Singapore' },
    '13': { country: 'Singapore' },
    '14': { country: 'France' },
    '15': { country: 'Hong Kong' },
    '16': { country: 'Hong Kong' },
    '17': { country: 'Australia' },
    '18': { country: 'Australia' },
    '19': { country: 'German' },
    '20': { country: 'German', excluded: true },
    '21': { country: 'Canadian' },
    '22': { country: 'Canadian' },
    '23': { country: 'Greek' },
    '24': { country: 'UK' },
    '25': { country: 'UK' },
    '26': { country: 'UK', excluded: true },
    '27': { country: 'UK', excluded: true },
    '28': { country: 'Euro' }
  }
};
