//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 09:40:42 PM EEST 
//


package com.egalacoral.api.betservice;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * 
 * 				TODO
 * 			
 * 
 * <p>Java class for bet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="externalRef" type="{http://schema.products.sportsbook.openbet.com/bet}externalRef" maxOccurs="4" minOccurs="0"/>
 *         &lt;element name="betslipRef" type="{http://schema.openbet.com/core}entityRef" minOccurs="0"/>
 *         &lt;element name="errorRef" type="{http://schema.openbet.com/core}entityRef" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="externalBetStatus" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="system" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="externalReceipt" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="system" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="receipt" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="linkedToBet" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="betLinkRef" type="{http://schema.openbet.com/core}entityRef" minOccurs="0"/>
 *                   &lt;element name="betRef" type="{http://schema.openbet.com/core}entityRef"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="linkedFromBet" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="betLinkRef" type="{http://schema.openbet.com/core}entityRef" minOccurs="0"/>
 *                   &lt;element name="betRef" type="{http://schema.openbet.com/core}entityRef"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="linkedPreviousBet" type="{http://schema.openbet.com/core}entityRef" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="betOfferRef" type="{http://schema.openbet.com/core}entityRef" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="betTypeRef" type="{http://schema.openbet.com/core}entityRef"/>
 *         &lt;element name="stake" type="{http://schema.products.sportsbook.openbet.com/bet}betStake"/>
 *         &lt;element name="freebetRedeemed" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="freebetRef" type="{http://schema.openbet.com/core}entityRef"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="passThroughBet" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="systemRef" type="{http://schema.openbet.com/core}entityRef"/>
 *                   &lt;element name="currencyRef" type="{http://schema.openbet.com/core}entityRef"/>
 *                   &lt;element name="hedgedBet" type="{http://schema.products.sportsbook.openbet.com/bet}bet" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="stake" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="payout" maxOccurs="2" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="returns" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="transactionRef" type="{http://schema.openbet.com/core}entityRef" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="timeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                           &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="systemAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="potential" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                 &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                 &lt;attribute name="winnings" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                 &lt;attribute name="refunds" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                 &lt;attribute name="bonus" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                 &lt;attribute name="legType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="lines" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="legComposition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="number" type="{http://schema.openbet.com/core}nonNegativeInt" />
 *                 &lt;attribute name="win" type="{http://schema.openbet.com/core}nonNegativeInt" />
 *                 &lt;attribute name="lose" type="{http://schema.openbet.com/core}nonNegativeInt" />
 *                 &lt;attribute name="void" type="{http://schema.openbet.com/core}nonNegativeInt" />
 *                 &lt;attribute name="push" type="{http://schema.openbet.com/core}nonNegativeInt" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="override" type="{http://schema.products.sportsbook.openbet.com/betcommon}override" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="freebet" type="{http://schema.products.sportsbook.openbet.com/betcommon}freebet" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="coupon" type="{http://schema.products.sportsbook.openbet.com/betcommon}coupon" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="cashoutValue" type="{http://schema.products.sportsbook.openbet.com/bet}cashoutValue" minOccurs="0"/>
 *         &lt;element name="partialCashout" type="{http://schema.products.sportsbook.openbet.com/bet}partialCashout" minOccurs="0"/>
 *         &lt;element name="cashoutBetDelayId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="betInfo" type="{http://schema.products.sportsbook.openbet.com/bet}slipPlacementInfo" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="legRef" type="{http://schema.openbet.com/core}entityRef" maxOccurs="unbounded"/>
 *           &lt;element name="leg" type="{http://schema.products.sportsbook.openbet.com/betcommon}leg" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://schema.openbet.com/core}entityAttrGroup"/>
 *       &lt;attribute name="receipt" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="outcomesChecked" type="{http://schema.openbet.com/core}yesNo" default="N" />
 *       &lt;attribute name="isOffer" type="{http://schema.openbet.com/core}yesNo" default="N" />
 *       &lt;attribute name="isSettled" type="{http://schema.openbet.com/core}yesNo" default="N" />
 *       &lt;attribute name="isCashedOut" type="{http://schema.openbet.com/core}yesNo" default="N" />
 *       &lt;attribute name="isFunded" type="{http://schema.openbet.com/core}yesNo" default="N" />
 *       &lt;attribute name="isReferred" type="{http://schema.openbet.com/core}yesNo" default="N" />
 *       &lt;attribute name="isParked" type="{http://schema.openbet.com/core}yesNo" default="N" />
 *       &lt;attribute name="isCancelled" type="{http://schema.openbet.com/core}yesNo" default="N" />
 *       &lt;attribute name="isConfirmed" type="{http://schema.openbet.com/core}yesNo" default="N" />
 *       &lt;attribute name="settleDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="settledHow" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="timeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="offerExpiresAt" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="confirmationExpectedAt" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bet", propOrder = {
    "externalRef",
    "betslipRef",
    "errorRef",
    "externalBetStatus",
    "externalReceipt",
    "linkedToBet",
    "linkedFromBet",
    "linkedPreviousBet",
    "betOfferRef",
    "betTypeRef",
    "stake",
    "freebetRedeemed",
    "passThroughBet",
    "payout",
    "lines",
    "override",
    "freebet",
    "coupon",
    "cashoutValue",
    "partialCashout",
    "cashoutBetDelayId",
    "betInfo",
    "legRef",
    "leg"
})
public class Bet
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected List<ExternalRef> externalRef;
    protected EntityRef betslipRef;
    protected List<EntityRef> errorRef;
    protected List<ExternalBetStatus> externalBetStatus;
    protected List<ExternalReceipt> externalReceipt;
    protected LinkedToBet linkedToBet;
    protected LinkedFromBet linkedFromBet;
    protected List<EntityRef> linkedPreviousBet;
    protected List<EntityRef> betOfferRef;
    @XmlElement(required = true)
    protected EntityRef betTypeRef;
    @XmlElement(required = true)
    protected BetStake stake;
    protected List<FreebetRedeemed> freebetRedeemed;
    protected List<PassThroughBet> passThroughBet;
    protected List<Payout> payout;
    protected Lines lines;
    protected List<Override> override;
    protected List<Freebet> freebet;
    protected List<Coupon> coupon;
    protected CashoutValue cashoutValue;
    protected PartialCashout partialCashout;
    protected String cashoutBetDelayId;
    protected SlipPlacementInfo betInfo;
    protected List<EntityRef> legRef;
    protected List<Leg> leg;
    @XmlAttribute
    protected String receipt;
    @XmlAttribute
    protected YesNo outcomesChecked;
    @XmlAttribute
    protected YesNo isOffer;
    @XmlAttribute
    protected YesNo isSettled;
    @XmlAttribute
    protected YesNo isCashedOut;
    @XmlAttribute
    protected YesNo isFunded;
    @XmlAttribute
    protected YesNo isReferred;
    @XmlAttribute
    protected YesNo isParked;
    @XmlAttribute
    protected YesNo isCancelled;
    @XmlAttribute
    protected YesNo isConfirmed;
    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar settleDate;
    @XmlAttribute
    protected String settledHow;
    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStamp;
    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar offerExpiresAt;
    @XmlAttribute
    protected String confirmationExpectedAt;
    @XmlAttribute
    protected String id;
    @XmlAttribute
    protected String documentId;
    @XmlAttribute
    protected String provider;
    @XmlAttribute
    protected String addr;
    @XmlAttribute
    protected String version;
    @XmlAttribute
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger ordering;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the externalRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExternalRef }
     * 
     * 
     */
    public List<ExternalRef> getExternalRef() {
        if (externalRef == null) {
            externalRef = new ArrayList<ExternalRef>();
        }
        return this.externalRef;
    }

    public boolean isSetExternalRef() {
        return ((this.externalRef!= null)&&(!this.externalRef.isEmpty()));
    }

    public void unsetExternalRef() {
        this.externalRef = null;
    }

    /**
     * Gets the value of the betslipRef property.
     * 
     * @return
     *     possible object is
     *     {@link EntityRef }
     *     
     */
    public EntityRef getBetslipRef() {
        return betslipRef;
    }

    /**
     * Sets the value of the betslipRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityRef }
     *     
     */
    public void setBetslipRef(EntityRef value) {
        this.betslipRef = value;
    }

    public boolean isSetBetslipRef() {
        return (this.betslipRef!= null);
    }

    /**
     * Gets the value of the errorRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the errorRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErrorRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityRef }
     * 
     * 
     */
    public List<EntityRef> getErrorRef() {
        if (errorRef == null) {
            errorRef = new ArrayList<EntityRef>();
        }
        return this.errorRef;
    }

    public boolean isSetErrorRef() {
        return ((this.errorRef!= null)&&(!this.errorRef.isEmpty()));
    }

    public void unsetErrorRef() {
        this.errorRef = null;
    }

    /**
     * Gets the value of the externalBetStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalBetStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalBetStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExternalBetStatus }
     * 
     * 
     */
    public List<ExternalBetStatus> getExternalBetStatus() {
        if (externalBetStatus == null) {
            externalBetStatus = new ArrayList<ExternalBetStatus>();
        }
        return this.externalBetStatus;
    }

    public boolean isSetExternalBetStatus() {
        return ((this.externalBetStatus!= null)&&(!this.externalBetStatus.isEmpty()));
    }

    public void unsetExternalBetStatus() {
        this.externalBetStatus = null;
    }

    /**
     * Gets the value of the externalReceipt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalReceipt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalReceipt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExternalReceipt }
     * 
     * 
     */
    public List<ExternalReceipt> getExternalReceipt() {
        if (externalReceipt == null) {
            externalReceipt = new ArrayList<ExternalReceipt>();
        }
        return this.externalReceipt;
    }

    public boolean isSetExternalReceipt() {
        return ((this.externalReceipt!= null)&&(!this.externalReceipt.isEmpty()));
    }

    public void unsetExternalReceipt() {
        this.externalReceipt = null;
    }

    /**
     * Gets the value of the linkedToBet property.
     * 
     * @return
     *     possible object is
     *     {@link LinkedToBet }
     *     
     */
    public LinkedToBet getLinkedToBet() {
        return linkedToBet;
    }

    /**
     * Sets the value of the linkedToBet property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkedToBet }
     *     
     */
    public void setLinkedToBet(LinkedToBet value) {
        this.linkedToBet = value;
    }

    public boolean isSetLinkedToBet() {
        return (this.linkedToBet!= null);
    }

    /**
     * Gets the value of the linkedFromBet property.
     * 
     * @return
     *     possible object is
     *     {@link LinkedFromBet }
     *     
     */
    public LinkedFromBet getLinkedFromBet() {
        return linkedFromBet;
    }

    /**
     * Sets the value of the linkedFromBet property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkedFromBet }
     *     
     */
    public void setLinkedFromBet(LinkedFromBet value) {
        this.linkedFromBet = value;
    }

    public boolean isSetLinkedFromBet() {
        return (this.linkedFromBet!= null);
    }

    /**
     * Gets the value of the linkedPreviousBet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linkedPreviousBet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinkedPreviousBet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityRef }
     * 
     * 
     */
    public List<EntityRef> getLinkedPreviousBet() {
        if (linkedPreviousBet == null) {
            linkedPreviousBet = new ArrayList<EntityRef>();
        }
        return this.linkedPreviousBet;
    }

    public boolean isSetLinkedPreviousBet() {
        return ((this.linkedPreviousBet!= null)&&(!this.linkedPreviousBet.isEmpty()));
    }

    public void unsetLinkedPreviousBet() {
        this.linkedPreviousBet = null;
    }

    /**
     * Gets the value of the betOfferRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the betOfferRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBetOfferRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityRef }
     * 
     * 
     */
    public List<EntityRef> getBetOfferRef() {
        if (betOfferRef == null) {
            betOfferRef = new ArrayList<EntityRef>();
        }
        return this.betOfferRef;
    }

    public boolean isSetBetOfferRef() {
        return ((this.betOfferRef!= null)&&(!this.betOfferRef.isEmpty()));
    }

    public void unsetBetOfferRef() {
        this.betOfferRef = null;
    }

    /**
     * Gets the value of the betTypeRef property.
     * 
     * @return
     *     possible object is
     *     {@link EntityRef }
     *     
     */
    public EntityRef getBetTypeRef() {
        return betTypeRef;
    }

    /**
     * Sets the value of the betTypeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityRef }
     *     
     */
    public void setBetTypeRef(EntityRef value) {
        this.betTypeRef = value;
    }

    public boolean isSetBetTypeRef() {
        return (this.betTypeRef!= null);
    }

    /**
     * Gets the value of the stake property.
     * 
     * @return
     *     possible object is
     *     {@link BetStake }
     *     
     */
    public BetStake getStake() {
        return stake;
    }

    /**
     * Sets the value of the stake property.
     * 
     * @param value
     *     allowed object is
     *     {@link BetStake }
     *     
     */
    public void setStake(BetStake value) {
        this.stake = value;
    }

    public boolean isSetStake() {
        return (this.stake!= null);
    }

    /**
     * Gets the value of the freebetRedeemed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the freebetRedeemed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFreebetRedeemed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FreebetRedeemed }
     * 
     * 
     */
    public List<FreebetRedeemed> getFreebetRedeemed() {
        if (freebetRedeemed == null) {
            freebetRedeemed = new ArrayList<FreebetRedeemed>();
        }
        return this.freebetRedeemed;
    }

    public boolean isSetFreebetRedeemed() {
        return ((this.freebetRedeemed!= null)&&(!this.freebetRedeemed.isEmpty()));
    }

    public void unsetFreebetRedeemed() {
        this.freebetRedeemed = null;
    }

    /**
     * Gets the value of the passThroughBet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the passThroughBet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPassThroughBet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PassThroughBet }
     * 
     * 
     */
    public List<PassThroughBet> getPassThroughBet() {
        if (passThroughBet == null) {
            passThroughBet = new ArrayList<PassThroughBet>();
        }
        return this.passThroughBet;
    }

    public boolean isSetPassThroughBet() {
        return ((this.passThroughBet!= null)&&(!this.passThroughBet.isEmpty()));
    }

    public void unsetPassThroughBet() {
        this.passThroughBet = null;
    }

    /**
     * Gets the value of the payout property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payout property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayout().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Payout }
     * 
     * 
     */
    public List<Payout> getPayout() {
        if (payout == null) {
            payout = new ArrayList<Payout>();
        }
        return this.payout;
    }

    public boolean isSetPayout() {
        return ((this.payout!= null)&&(!this.payout.isEmpty()));
    }

    public void unsetPayout() {
        this.payout = null;
    }

    /**
     * Gets the value of the lines property.
     * 
     * @return
     *     possible object is
     *     {@link Lines }
     *     
     */
    public Lines getLines() {
        return lines;
    }

    /**
     * Sets the value of the lines property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lines }
     *     
     */
    public void setLines(Lines value) {
        this.lines = value;
    }

    public boolean isSetLines() {
        return (this.lines!= null);
    }

    /**
     * Gets the value of the override property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the override property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOverride().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Override }
     * 
     * 
     */
    public List<Override> getOverride() {
        if (override == null) {
            override = new ArrayList<Override>();
        }
        return this.override;
    }

    public boolean isSetOverride() {
        return ((this.override!= null)&&(!this.override.isEmpty()));
    }

    public void unsetOverride() {
        this.override = null;
    }

    /**
     * Gets the value of the freebet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the freebet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFreebet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Freebet }
     * 
     * 
     */
    public List<Freebet> getFreebet() {
        if (freebet == null) {
            freebet = new ArrayList<Freebet>();
        }
        return this.freebet;
    }

    public boolean isSetFreebet() {
        return ((this.freebet!= null)&&(!this.freebet.isEmpty()));
    }

    public void unsetFreebet() {
        this.freebet = null;
    }

    /**
     * Gets the value of the coupon property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coupon property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoupon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Coupon }
     * 
     * 
     */
    public List<Coupon> getCoupon() {
        if (coupon == null) {
            coupon = new ArrayList<Coupon>();
        }
        return this.coupon;
    }

    public boolean isSetCoupon() {
        return ((this.coupon!= null)&&(!this.coupon.isEmpty()));
    }

    public void unsetCoupon() {
        this.coupon = null;
    }

    /**
     * Gets the value of the cashoutValue property.
     * 
     * @return
     *     possible object is
     *     {@link CashoutValue }
     *     
     */
    public CashoutValue getCashoutValue() {
        return cashoutValue;
    }

    /**
     * Sets the value of the cashoutValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link CashoutValue }
     *     
     */
    public void setCashoutValue(CashoutValue value) {
        this.cashoutValue = value;
    }

    public boolean isSetCashoutValue() {
        return (this.cashoutValue!= null);
    }

    /**
     * Gets the value of the partialCashout property.
     * 
     * @return
     *     possible object is
     *     {@link PartialCashout }
     *     
     */
    public PartialCashout getPartialCashout() {
        return partialCashout;
    }

    /**
     * Sets the value of the partialCashout property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartialCashout }
     *     
     */
    public void setPartialCashout(PartialCashout value) {
        this.partialCashout = value;
    }

    public boolean isSetPartialCashout() {
        return (this.partialCashout!= null);
    }

    /**
     * Gets the value of the cashoutBetDelayId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCashoutBetDelayId() {
        return cashoutBetDelayId;
    }

    /**
     * Sets the value of the cashoutBetDelayId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCashoutBetDelayId(String value) {
        this.cashoutBetDelayId = value;
    }

    public boolean isSetCashoutBetDelayId() {
        return (this.cashoutBetDelayId!= null);
    }

    /**
     * Gets the value of the betInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SlipPlacementInfo }
     *     
     */
    public SlipPlacementInfo getBetInfo() {
        return betInfo;
    }

    /**
     * Sets the value of the betInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SlipPlacementInfo }
     *     
     */
    public void setBetInfo(SlipPlacementInfo value) {
        this.betInfo = value;
    }

    public boolean isSetBetInfo() {
        return (this.betInfo!= null);
    }

    /**
     * Gets the value of the legRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the legRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLegRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityRef }
     * 
     * 
     */
    public List<EntityRef> getLegRef() {
        if (legRef == null) {
            legRef = new ArrayList<EntityRef>();
        }
        return this.legRef;
    }

    public boolean isSetLegRef() {
        return ((this.legRef!= null)&&(!this.legRef.isEmpty()));
    }

    public void unsetLegRef() {
        this.legRef = null;
    }

    /**
     * Gets the value of the leg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the leg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLeg().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Leg }
     * 
     * 
     */
    public List<Leg> getLeg() {
        if (leg == null) {
            leg = new ArrayList<Leg>();
        }
        return this.leg;
    }

    public boolean isSetLeg() {
        return ((this.leg!= null)&&(!this.leg.isEmpty()));
    }

    public void unsetLeg() {
        this.leg = null;
    }

    /**
     * Gets the value of the receipt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceipt() {
        return receipt;
    }

    /**
     * Sets the value of the receipt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceipt(String value) {
        this.receipt = value;
    }

    public boolean isSetReceipt() {
        return (this.receipt!= null);
    }

    /**
     * Gets the value of the outcomesChecked property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getOutcomesChecked() {
        if (outcomesChecked == null) {
            return YesNo.N;
        } else {
            return outcomesChecked;
        }
    }

    /**
     * Sets the value of the outcomesChecked property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setOutcomesChecked(YesNo value) {
        this.outcomesChecked = value;
    }

    public boolean isSetOutcomesChecked() {
        return (this.outcomesChecked!= null);
    }

    /**
     * Gets the value of the isOffer property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getIsOffer() {
        if (isOffer == null) {
            return YesNo.N;
        } else {
            return isOffer;
        }
    }

    /**
     * Sets the value of the isOffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setIsOffer(YesNo value) {
        this.isOffer = value;
    }

    public boolean isSetIsOffer() {
        return (this.isOffer!= null);
    }

    /**
     * Gets the value of the isSettled property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getIsSettled() {
        if (isSettled == null) {
            return YesNo.N;
        } else {
            return isSettled;
        }
    }

    /**
     * Sets the value of the isSettled property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setIsSettled(YesNo value) {
        this.isSettled = value;
    }

    public boolean isSetIsSettled() {
        return (this.isSettled!= null);
    }

    /**
     * Gets the value of the isCashedOut property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getIsCashedOut() {
        if (isCashedOut == null) {
            return YesNo.N;
        } else {
            return isCashedOut;
        }
    }

    /**
     * Sets the value of the isCashedOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setIsCashedOut(YesNo value) {
        this.isCashedOut = value;
    }

    public boolean isSetIsCashedOut() {
        return (this.isCashedOut!= null);
    }

    /**
     * Gets the value of the isFunded property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getIsFunded() {
        if (isFunded == null) {
            return YesNo.N;
        } else {
            return isFunded;
        }
    }

    /**
     * Sets the value of the isFunded property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setIsFunded(YesNo value) {
        this.isFunded = value;
    }

    public boolean isSetIsFunded() {
        return (this.isFunded!= null);
    }

    /**
     * Gets the value of the isReferred property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getIsReferred() {
        if (isReferred == null) {
            return YesNo.N;
        } else {
            return isReferred;
        }
    }

    /**
     * Sets the value of the isReferred property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setIsReferred(YesNo value) {
        this.isReferred = value;
    }

    public boolean isSetIsReferred() {
        return (this.isReferred!= null);
    }

    /**
     * Gets the value of the isParked property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getIsParked() {
        if (isParked == null) {
            return YesNo.N;
        } else {
            return isParked;
        }
    }

    /**
     * Sets the value of the isParked property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setIsParked(YesNo value) {
        this.isParked = value;
    }

    public boolean isSetIsParked() {
        return (this.isParked!= null);
    }

    /**
     * Gets the value of the isCancelled property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getIsCancelled() {
        if (isCancelled == null) {
            return YesNo.N;
        } else {
            return isCancelled;
        }
    }

    /**
     * Sets the value of the isCancelled property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setIsCancelled(YesNo value) {
        this.isCancelled = value;
    }

    public boolean isSetIsCancelled() {
        return (this.isCancelled!= null);
    }

    /**
     * Gets the value of the isConfirmed property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getIsConfirmed() {
        if (isConfirmed == null) {
            return YesNo.N;
        } else {
            return isConfirmed;
        }
    }

    /**
     * Sets the value of the isConfirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setIsConfirmed(YesNo value) {
        this.isConfirmed = value;
    }

    public boolean isSetIsConfirmed() {
        return (this.isConfirmed!= null);
    }

    /**
     * Gets the value of the settleDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSettleDate() {
        return settleDate;
    }

    /**
     * Sets the value of the settleDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSettleDate(XMLGregorianCalendar value) {
        this.settleDate = value;
    }

    public boolean isSetSettleDate() {
        return (this.settleDate!= null);
    }

    /**
     * Gets the value of the settledHow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettledHow() {
        return settledHow;
    }

    /**
     * Sets the value of the settledHow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettledHow(String value) {
        this.settledHow = value;
    }

    public boolean isSetSettledHow() {
        return (this.settledHow!= null);
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStamp(XMLGregorianCalendar value) {
        this.timeStamp = value;
    }

    public boolean isSetTimeStamp() {
        return (this.timeStamp!= null);
    }

    /**
     * Gets the value of the offerExpiresAt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOfferExpiresAt() {
        return offerExpiresAt;
    }

    /**
     * Sets the value of the offerExpiresAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOfferExpiresAt(XMLGregorianCalendar value) {
        this.offerExpiresAt = value;
    }

    public boolean isSetOfferExpiresAt() {
        return (this.offerExpiresAt!= null);
    }

    /**
     * Gets the value of the confirmationExpectedAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfirmationExpectedAt() {
        return confirmationExpectedAt;
    }

    /**
     * Sets the value of the confirmationExpectedAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfirmationExpectedAt(String value) {
        this.confirmationExpectedAt = value;
    }

    public boolean isSetConfirmationExpectedAt() {
        return (this.confirmationExpectedAt!= null);
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    public boolean isSetId() {
        return (this.id!= null);
    }

    /**
     * Gets the value of the documentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentId() {
        return documentId;
    }

    /**
     * Sets the value of the documentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentId(String value) {
        this.documentId = value;
    }

    public boolean isSetDocumentId() {
        return (this.documentId!= null);
    }

    /**
     * Gets the value of the provider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvider() {
        if (provider == null) {
            return "OpenBet";
        } else {
            return provider;
        }
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvider(String value) {
        this.provider = value;
    }

    public boolean isSetProvider() {
        return (this.provider!= null);
    }

    /**
     * Gets the value of the addr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddr() {
        return addr;
    }

    /**
     * Sets the value of the addr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddr(String value) {
        this.addr = value;
    }

    public boolean isSetAddr() {
        return (this.addr!= null);
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    public boolean isSetVersion() {
        return (this.version!= null);
    }

    /**
     * Gets the value of the ordering property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrdering() {
        return ordering;
    }

    /**
     * Sets the value of the ordering property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrdering(BigInteger value) {
        this.ordering = value;
    }

    public boolean isSetOrdering() {
        return (this.ordering!= null);
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="system" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ExternalBetStatus
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlAttribute(required = true)
        protected String system;
        @XmlAttribute
        protected String status;

        /**
         * Gets the value of the system property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSystem() {
            return system;
        }

        /**
         * Sets the value of the system property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSystem(String value) {
            this.system = value;
        }

        public boolean isSetSystem() {
            return (this.system!= null);
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        public boolean isSetStatus() {
            return (this.status!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="system" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="receipt" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ExternalReceipt
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlAttribute(required = true)
        protected String system;
        @XmlAttribute
        protected String receipt;

        /**
         * Gets the value of the system property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSystem() {
            return system;
        }

        /**
         * Sets the value of the system property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSystem(String value) {
            this.system = value;
        }

        public boolean isSetSystem() {
            return (this.system!= null);
        }

        /**
         * Gets the value of the receipt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReceipt() {
            return receipt;
        }

        /**
         * Sets the value of the receipt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReceipt(String value) {
            this.receipt = value;
        }

        public boolean isSetReceipt() {
            return (this.receipt!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="freebetRef" type="{http://schema.openbet.com/core}entityRef"/>
     *       &lt;/sequence>
     *       &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "freebetRef"
    })
    public static class FreebetRedeemed
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(required = true)
        protected EntityRef freebetRef;
        @XmlAttribute
        protected BigDecimal amount;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Gets the value of the freebetRef property.
         * 
         * @return
         *     possible object is
         *     {@link EntityRef }
         *     
         */
        public EntityRef getFreebetRef() {
            return freebetRef;
        }

        /**
         * Sets the value of the freebetRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link EntityRef }
         *     
         */
        public void setFreebetRef(EntityRef value) {
            this.freebetRef = value;
        }

        public boolean isSetFreebetRef() {
            return (this.freebetRef!= null);
        }

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setAmount(BigDecimal value) {
            this.amount = value;
        }

        public boolean isSetAmount() {
            return (this.amount!= null);
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="legComposition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="number" type="{http://schema.openbet.com/core}nonNegativeInt" />
     *       &lt;attribute name="win" type="{http://schema.openbet.com/core}nonNegativeInt" />
     *       &lt;attribute name="lose" type="{http://schema.openbet.com/core}nonNegativeInt" />
     *       &lt;attribute name="void" type="{http://schema.openbet.com/core}nonNegativeInt" />
     *       &lt;attribute name="push" type="{http://schema.openbet.com/core}nonNegativeInt" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "legComposition"
    })
    public static class Lines
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        protected String legComposition;
        @XmlAttribute
        protected Integer number;
        @XmlAttribute
        protected Integer win;
        @XmlAttribute
        protected Integer lose;
        @XmlAttribute(name = "void")
        protected Integer _void;
        @XmlAttribute
        protected Integer push;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Gets the value of the legComposition property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLegComposition() {
            return legComposition;
        }

        /**
         * Sets the value of the legComposition property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLegComposition(String value) {
            this.legComposition = value;
        }

        public boolean isSetLegComposition() {
            return (this.legComposition!= null);
        }

        /**
         * Gets the value of the number property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getNumber() {
            return number;
        }

        /**
         * Sets the value of the number property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNumber(int value) {
            this.number = value;
        }

        public boolean isSetNumber() {
            return (this.number!= null);
        }

        public void unsetNumber() {
            this.number = null;
        }

        /**
         * Gets the value of the win property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getWin() {
            return win;
        }

        /**
         * Sets the value of the win property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setWin(int value) {
            this.win = value;
        }

        public boolean isSetWin() {
            return (this.win!= null);
        }

        public void unsetWin() {
            this.win = null;
        }

        /**
         * Gets the value of the lose property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getLose() {
            return lose;
        }

        /**
         * Sets the value of the lose property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setLose(int value) {
            this.lose = value;
        }

        public boolean isSetLose() {
            return (this.lose!= null);
        }

        public void unsetLose() {
            this.lose = null;
        }

        /**
         * Gets the value of the void property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getVoid() {
            return _void;
        }

        /**
         * Sets the value of the void property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setVoid(int value) {
            this._void = value;
        }

        public boolean isSetVoid() {
            return (this._void!= null);
        }

        public void unsetVoid() {
            this._void = null;
        }

        /**
         * Gets the value of the push property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getPush() {
            return push;
        }

        /**
         * Sets the value of the push property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPush(int value) {
            this.push = value;
        }

        public boolean isSetPush() {
            return (this.push!= null);
        }

        public void unsetPush() {
            this.push = null;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="betLinkRef" type="{http://schema.openbet.com/core}entityRef" minOccurs="0"/>
     *         &lt;element name="betRef" type="{http://schema.openbet.com/core}entityRef"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "betLinkRef",
        "betRef"
    })
    public static class LinkedFromBet
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        protected EntityRef betLinkRef;
        @XmlElement(required = true)
        protected EntityRef betRef;

        /**
         * Gets the value of the betLinkRef property.
         * 
         * @return
         *     possible object is
         *     {@link EntityRef }
         *     
         */
        public EntityRef getBetLinkRef() {
            return betLinkRef;
        }

        /**
         * Sets the value of the betLinkRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link EntityRef }
         *     
         */
        public void setBetLinkRef(EntityRef value) {
            this.betLinkRef = value;
        }

        public boolean isSetBetLinkRef() {
            return (this.betLinkRef!= null);
        }

        /**
         * Gets the value of the betRef property.
         * 
         * @return
         *     possible object is
         *     {@link EntityRef }
         *     
         */
        public EntityRef getBetRef() {
            return betRef;
        }

        /**
         * Sets the value of the betRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link EntityRef }
         *     
         */
        public void setBetRef(EntityRef value) {
            this.betRef = value;
        }

        public boolean isSetBetRef() {
            return (this.betRef!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="betLinkRef" type="{http://schema.openbet.com/core}entityRef" minOccurs="0"/>
     *         &lt;element name="betRef" type="{http://schema.openbet.com/core}entityRef"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "betLinkRef",
        "betRef"
    })
    public static class LinkedToBet
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        protected EntityRef betLinkRef;
        @XmlElement(required = true)
        protected EntityRef betRef;

        /**
         * Gets the value of the betLinkRef property.
         * 
         * @return
         *     possible object is
         *     {@link EntityRef }
         *     
         */
        public EntityRef getBetLinkRef() {
            return betLinkRef;
        }

        /**
         * Sets the value of the betLinkRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link EntityRef }
         *     
         */
        public void setBetLinkRef(EntityRef value) {
            this.betLinkRef = value;
        }

        public boolean isSetBetLinkRef() {
            return (this.betLinkRef!= null);
        }

        /**
         * Gets the value of the betRef property.
         * 
         * @return
         *     possible object is
         *     {@link EntityRef }
         *     
         */
        public EntityRef getBetRef() {
            return betRef;
        }

        /**
         * Sets the value of the betRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link EntityRef }
         *     
         */
        public void setBetRef(EntityRef value) {
            this.betRef = value;
        }

        public boolean isSetBetRef() {
            return (this.betRef!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="systemRef" type="{http://schema.openbet.com/core}entityRef"/>
     *         &lt;element name="currencyRef" type="{http://schema.openbet.com/core}entityRef"/>
     *         &lt;element name="hedgedBet" type="{http://schema.products.sportsbook.openbet.com/bet}bet" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="stake" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "systemRef",
        "currencyRef",
        "hedgedBet"
    })
    public static class PassThroughBet
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(required = true)
        protected EntityRef systemRef;
        @XmlElement(required = true)
        protected EntityRef currencyRef;
        protected Bet hedgedBet;
        @XmlAttribute
        protected BigDecimal stake;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Gets the value of the systemRef property.
         * 
         * @return
         *     possible object is
         *     {@link EntityRef }
         *     
         */
        public EntityRef getSystemRef() {
            return systemRef;
        }

        /**
         * Sets the value of the systemRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link EntityRef }
         *     
         */
        public void setSystemRef(EntityRef value) {
            this.systemRef = value;
        }

        public boolean isSetSystemRef() {
            return (this.systemRef!= null);
        }

        /**
         * Gets the value of the currencyRef property.
         * 
         * @return
         *     possible object is
         *     {@link EntityRef }
         *     
         */
        public EntityRef getCurrencyRef() {
            return currencyRef;
        }

        /**
         * Sets the value of the currencyRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link EntityRef }
         *     
         */
        public void setCurrencyRef(EntityRef value) {
            this.currencyRef = value;
        }

        public boolean isSetCurrencyRef() {
            return (this.currencyRef!= null);
        }

        /**
         * Gets the value of the hedgedBet property.
         * 
         * @return
         *     possible object is
         *     {@link Bet }
         *     
         */
        public Bet getHedgedBet() {
            return hedgedBet;
        }

        /**
         * Sets the value of the hedgedBet property.
         * 
         * @param value
         *     allowed object is
         *     {@link Bet }
         *     
         */
        public void setHedgedBet(Bet value) {
            this.hedgedBet = value;
        }

        public boolean isSetHedgedBet() {
            return (this.hedgedBet!= null);
        }

        /**
         * Gets the value of the stake property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getStake() {
            return stake;
        }

        /**
         * Sets the value of the stake property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setStake(BigDecimal value) {
            this.stake = value;
        }

        public boolean isSetStake() {
            return (this.stake!= null);
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="returns" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="transactionRef" type="{http://schema.openbet.com/core}entityRef" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="timeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *                 &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *                 &lt;attribute name="systemAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="potential" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *       &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *       &lt;attribute name="winnings" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *       &lt;attribute name="refunds" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *       &lt;attribute name="bonus" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *       &lt;attribute name="legType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "returns"
    })
    public static class Payout
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        protected List<Returns> returns;
        @XmlAttribute
        protected BigDecimal potential;
        @XmlAttribute
        protected BigDecimal max;
        @XmlAttribute
        protected BigDecimal winnings;
        @XmlAttribute
        protected BigDecimal refunds;
        @XmlAttribute
        protected BigDecimal bonus;
        @XmlAttribute
        protected String legType;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Gets the value of the returns property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the returns property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getReturns().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Returns }
         * 
         * 
         */
        public List<Returns> getReturns() {
            if (returns == null) {
                returns = new ArrayList<Returns>();
            }
            return this.returns;
        }

        public boolean isSetReturns() {
            return ((this.returns!= null)&&(!this.returns.isEmpty()));
        }

        public void unsetReturns() {
            this.returns = null;
        }

        /**
         * Gets the value of the potential property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPotential() {
            return potential;
        }

        /**
         * Sets the value of the potential property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPotential(BigDecimal value) {
            this.potential = value;
        }

        public boolean isSetPotential() {
            return (this.potential!= null);
        }

        /**
         * Gets the value of the max property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMax() {
            return max;
        }

        /**
         * Sets the value of the max property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMax(BigDecimal value) {
            this.max = value;
        }

        public boolean isSetMax() {
            return (this.max!= null);
        }

        /**
         * Gets the value of the winnings property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getWinnings() {
            return winnings;
        }

        /**
         * Sets the value of the winnings property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setWinnings(BigDecimal value) {
            this.winnings = value;
        }

        public boolean isSetWinnings() {
            return (this.winnings!= null);
        }

        /**
         * Gets the value of the refunds property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getRefunds() {
            return refunds;
        }

        /**
         * Sets the value of the refunds property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setRefunds(BigDecimal value) {
            this.refunds = value;
        }

        public boolean isSetRefunds() {
            return (this.refunds!= null);
        }

        /**
         * Gets the value of the bonus property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getBonus() {
            return bonus;
        }

        /**
         * Sets the value of the bonus property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setBonus(BigDecimal value) {
            this.bonus = value;
        }

        public boolean isSetBonus() {
            return (this.bonus!= null);
        }

        /**
         * Gets the value of the legType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLegType() {
            return legType;
        }

        /**
         * Sets the value of the legType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLegType(String value) {
            this.legType = value;
        }

        public boolean isSetLegType() {
            return (this.legType!= null);
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="transactionRef" type="{http://schema.openbet.com/core}entityRef" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="timeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *       &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal" />
         *       &lt;attribute name="systemAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "transactionRef"
        })
        public static class Returns
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            protected EntityRef transactionRef;
            @XmlAttribute
            protected String id;
            @XmlAttribute
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar timeStamp;
            @XmlAttribute
            protected BigDecimal amount;
            @XmlAttribute
            protected BigDecimal systemAmount;
            @XmlAnyAttribute
            private Map<QName, String> otherAttributes = new HashMap<QName, String>();

            /**
             * Gets the value of the transactionRef property.
             * 
             * @return
             *     possible object is
             *     {@link EntityRef }
             *     
             */
            public EntityRef getTransactionRef() {
                return transactionRef;
            }

            /**
             * Sets the value of the transactionRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link EntityRef }
             *     
             */
            public void setTransactionRef(EntityRef value) {
                this.transactionRef = value;
            }

            public boolean isSetTransactionRef() {
                return (this.transactionRef!= null);
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            public boolean isSetId() {
                return (this.id!= null);
            }

            /**
             * Gets the value of the timeStamp property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getTimeStamp() {
                return timeStamp;
            }

            /**
             * Sets the value of the timeStamp property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setTimeStamp(XMLGregorianCalendar value) {
                this.timeStamp = value;
            }

            public boolean isSetTimeStamp() {
                return (this.timeStamp!= null);
            }

            /**
             * Gets the value of the amount property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getAmount() {
                return amount;
            }

            /**
             * Sets the value of the amount property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setAmount(BigDecimal value) {
                this.amount = value;
            }

            public boolean isSetAmount() {
                return (this.amount!= null);
            }

            /**
             * Gets the value of the systemAmount property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getSystemAmount() {
                return systemAmount;
            }

            /**
             * Sets the value of the systemAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setSystemAmount(BigDecimal value) {
                this.systemAmount = value;
            }

            public boolean isSetSystemAmount() {
                return (this.systemAmount!= null);
            }

            /**
             * Gets a map that contains attributes that aren't bound to any typed property on this class.
             * 
             * <p>
             * the map is keyed by the name of the attribute and 
             * the value is the string value of the attribute.
             * 
             * the map returned by this method is live, and you can add new attribute
             * by updating the map directly. Because of this design, there's no setter.
             * 
             * 
             * @return
             *     always non-null
             */
            public Map<QName, String> getOtherAttributes() {
                return otherAttributes;
            }

        }

    }

}
