//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 09:40:42 PM EEST 
//


package com.egalacoral.api.betservice;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for externalRef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="externalRef">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.openbet.com/core}entityRef">
 *       &lt;attribute name="transient" type="{http://schema.openbet.com/core}yesNo" default="N" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "externalRef")
public class ExternalRef
    extends EntityRef
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "transient")
    protected YesNo _transient;

    /**
     * Gets the value of the transient property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getTransient() {
        if (_transient == null) {
            return YesNo.N;
        } else {
            return _transient;
        }
    }

    /**
     * Sets the value of the transient property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setTransient(YesNo value) {
        this._transient = value;
    }

    public boolean isSetTransient() {
        return (this._transient!= null);
    }

}
