//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 09:40:42 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schema.products.sportsbook.openbet.com/bet", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.egalacoral.api.betservice;
