//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 09:40:42 PM EEST 
//


package com.egalacoral.api.betservice;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for poolLeg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="poolLeg">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="poolRef" type="{http://schema.openbet.com/core}entityRef"/>
 *         &lt;element name="legPart" type="{http://schema.products.sportsbook.openbet.com/betcommon}legPart" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "poolLeg", namespace = "http://schema.products.sportsbook.openbet.com/betcommon", propOrder = {
    "poolRef",
    "legPart"
})
public class PoolLeg
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected EntityRef poolRef;
    @XmlElement(required = true)
    protected List<LegPart> legPart;

    /**
     * Gets the value of the poolRef property.
     * 
     * @return
     *     possible object is
     *     {@link EntityRef }
     *     
     */
    public EntityRef getPoolRef() {
        return poolRef;
    }

    /**
     * Sets the value of the poolRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityRef }
     *     
     */
    public void setPoolRef(EntityRef value) {
        this.poolRef = value;
    }

    public boolean isSetPoolRef() {
        return (this.poolRef!= null);
    }

    /**
     * Gets the value of the legPart property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the legPart property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLegPart().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LegPart }
     * 
     * 
     */
    public List<LegPart> getLegPart() {
        if (legPart == null) {
            legPart = new ArrayList<LegPart>();
        }
        return this.legPart;
    }

    public boolean isSetLegPart() {
        return ((this.legPart!= null)&&(!this.legPart.isEmpty()));
    }

    public void unsetLegPart() {
        this.legPart = null;
    }

}
