export const MyStableConstants = {
    myStable: 'My Stable',
    myStableConfigurations: 'My Stable Configurations',
    entryPoint: 'My Stable Entry Point',
    entryPointSVG: 'Entry Point SVG Icon',
    entryPointLabel: 'Entry Point Label',
    svgIconErrorMsg: 'This Property Should be filled',
    myStableLabelErrorMsg: 'Entry Point Label Should be filled',
    myStableLabelCharMsg: 'Entry Point Label Should not exceed 15 characters',
    editOrSave: 'Edit Or Save My Stable',
    editSvg: 'Edit Stable Svg Icon',
    editLabel: 'Edit Stable Label',
    editLabelErrorMsg: 'Edit Stable Label Should be filled',
    editLabelCharMsg: 'Entry Stable Label Should not exceed 15 characters',
    saveSvg: 'Save Stable Svg Icon',
    saveLabel: 'Save Stable Label',
    saveLabelErrorMsg: 'Save Stable Label Should be filled',
    saveLabelCharMsg: 'Save Stable Label Should not exceed 15 characters',
    editNoteSvg: 'Edit Note Svg Icon',
    bookmarkSvg: 'Bookmark Svg Icon',
    unbookmarkSvg: 'Unbookmark Svg Icon',
    inProgressSvg: 'InProgress Bookmark Svg Icon',
    emptyStable: 'Empty My Stable',
    emptyStableSvg: 'Empty Stable Svg Icon',
    emptyStableHeader: 'Empty Stable Header Label',
    emptyStableHeaderErrorMsg: 'Empty Stable Header Label Should be filled',
    emptyStableHeaderCharMsg: 'Empty Stable Header Label Should not exceed 30 characters',
    emptyStableMessage: 'Empty Stable Message Label',
    emptyStableMessageErrorMsg: 'Empty Stable Message Label Should be filled',
    emptyStableMessageCharMsg: 'Empty Stable Message Label Should not exceed 100 characters',
    emptyStableCtaLabel: 'Empty Stable CTA Label',
    emptyStableCtaLabelErrorMsg: 'Empty Stable CTA Label Should be filled',
    emptyStableCtaLabelCharMsg: 'Empty Stable CTA Label Should not exceed 30 characters',
    myStableSignposting: 'My Stable Signposting',
    SignpostingSvg: 'Signposting Svg Icon',
    noteSignpostingSvg: 'Notes Signposting Svg Icon',
    myStableTodayRunningHorseCarousel: 'Your Horses Running Today Carousel',
    carouselIcon: 'Carousel Icon',
    carouselText: 'Carousel Name',
    carouselTextErrorMsg: 'Carousel Name Should be filled',
    carouselTextCharMsg: 'Carousel Name Should not exceed 50 characters',
    myStablePopups: 'Tooltip Messages', 
    horseExceededMsg: 'Maximum Horses Exceed Message',
    horseExceededErrorMsg: 'Horse Exceeded Message Should be filled',
    horseExceededCharMsg: 'Horse Exceeded Message Should not exceed 100 characters',
    addStableMsg: 'Add To Stable Mybets Message',
    addStableCharMsg: 'Add To Stable Mybets Message Should not exceed 50 characters',
    crcRecommendations:'CRC Recommendations',
    crcLogoImage : 'Logo Svg Icon',
    crcBackgroundLabel: 'Background Label',
    crcBackgroundLabelErrorMsg: 'Background Label Should be filled',
    crcBackgroundLabelCharMsg: 'Background Label Should not exceed 100 characters',
    crcHorseSignposting: 'Horse Signposting Svg Icon',
    crcSaveAllText:'Save All Label',
    crcSaveAllTextErrorMsg: 'Save All Label Should be filled',
    crcSaveAllTextCharMsg: 'Save All Label Should not exceed 15 characters',
    crcWhiteBookmarkIcon:'Save Bookmark Svg Icon',
    crcBlackBookmarkIcon:'Bookmark Svg Icon',
    crcGotoRacingClubText:'Goto Racing Club Label',
    crcGotoRacingClubTextErrorMsg: 'Goto Racing Club Label Should be filled',
    crcGotoRacingClubTextCharMsg: 'Goto Racing Club Label Should not exceed 30 characters',
    crcGotoRacingClubUrl : 'Goto Racing Club Link',
    crcGotoRacingClubUrlErrorMsg: 'Goto Racing Club Link Should be filled',
    crcGotoRacingClubUrlCharMsg: 'Goto Racing Club Link Should not exceed 100 characters',
}