tst2:
  qa2:
    base_host_url: https://qa2.myaccount.coral.co.uk/
    labelhost: https://qa2.myaccount.coral.co.uk/en/api/
    mobileportal: https://qa2.myaccount.coral.co.uk/en/mobileportal/api/
    registration_prefix: 'ukmigct-'
    nickname_prefix: 'au-bma-'
    auth_username_prefix: 'cl_'
    deposit_user_api_tokens: http://api.bwin.com/v3/user/
    cashier_host: https://trunkia-coralcashier.ivycomptech.co.in/
    brand_id: CORAL
    product_id: SPORTSBOOK
    channel_id: MW
    in_shop_user_card_generation: https://tr-cl-gateway.ivycomptech.co.in/product/ums/service/player-management/operation/
  qa3:
    base_host_url: https://qa3.myaccount.coral.co.uk/
    labelhost: https://qa3.myaccount.coral.co.uk/en/api/
    mobileportal: https://qa3.myaccount.coral.co.uk/en/mobileportal/api/
    registration_prefix: 'ukmigct-'
    nickname_prefix: 'au-bma-'
    auth_username_prefix: 'cl_'
    deposit_user_api_tokens: http://api.bwin.com/v3/user/
    cashier_host: https://trunkia-coralcashier.ivycomptech.co.in/
    brand_id: CORAL
    product_id: SPORTSBOOK
    channel_id: MW
stg2:
  base_host_url: https://test.myaccount.coral.co.uk/
  labelhost: https://test.myaccount.coral.co.uk/en/api/
  mobileportal: https://test.myaccount.coral.co.uk/en/mobileportal/api/
  registration_prefix: 'ukmigct-'
  nickname_prefix: 'au-bma-'
  auth_username_prefix: 'cl_'
  deposit_user_api_tokens: http://api.bwin.com/v3/user/
  cashier_host: https://cashier.coral.co.uk.e7new.com/
  brand_id: CORAL
  product_id: SPORTSBOOK
  channel_id: MW
beta:
  base_host_url: https://beta-myaccount.coral.co.uk/
  labelhost: https://beta-myaccount.coral.co.uk/en/api/
  mobileportal: https://beta-myaccount.coral.co.uk/en/mobileportal/api/
  registration_prefix: 'testgvccl-'
  nickname_prefix: 'au-bma-'
  auth_username_prefix: 'cl_'
  deposit_user_api_tokens: http://api.bwin.com/v3/user/
  cashier_host: https://cashier.coral.co.uk/
  brand_id: CORAL
  product_id: SPORTSBOOK
  channel_id: MW
  in_shop_user_card_generation: https://cl-gateway.ivycomptech.co.in/product/ums/service/player-management/operation/
prod:
  base_host_url: https://myaccount.coral.co.uk/
  labelhost: https://myaccount.coral.co.uk/en/api/
  mobileportal: https://myaccount.coral.co.uk/en/mobileportal/api/
  registration_prefix: 'testgvccl-'
  nickname_prefix: 'au-bma-'
  auth_username_prefix: 'cl_'
  deposit_user_api_tokens: http://api.bwin.com/v3/user/
  cashier_host: https://cashier.coral.co.uk/
  brand_id: CORAL
  product_id: SPORTSBOOK
  channel_id: MW
  in_shop_user_card_generation: https://cl-gateway.ivycomptech.co.in/product/ums/service/player-management/operation/
