clone:
  depth: full
pipelines:

  default:
    - step:
        name: build
        image: openjdk:11
        caches:
          - gradle
          - gradlewrapper
        script:
          - ./gradlew test build
    - step:
        name: test
        image: openjdk:11
        caches:
          - sonarcloud
        script:
          - ./gradlew test sonarqube
              -Dsonar.coverage.exclusions=src/main/java/com/ladbrokescoral/oxygen/listeners/KafkaListener.java,src/main/java/com/ladbrokescoral/oxygen/configuration/*.java


  pull-requests:
    '**':
      - step:
          name: build
          image: openjdk:11
          script:
            - ./gradlew test build

      - step:
          name: test
          image: openjdk:11
          script:
            - ./gradlew test sonarqube
                -Dsonar.pullrequest.key=$BITBUCKET_PR_ID
                -Dsonar.pullrequest.base=$BITBUCKET_PR_DESTINATION_BRANCH
                -Dsonar.pullrequest.branch=$BITBUCKET_BRANCH
                -Dsonar.coverage.exclusions=src/main/java/com/ladbrokescoral/oxygen/listeners/KafkaListener.java,src/main/java/com/ladbrokescoral/oxygen/configuration/*.java

definitions:
  caches:
    sonarcloud: ~/.sonar/cache
    gradlewrapper: ~/.gradle/wrapper
