export const CONTESTS = [
  {
    inclusionList: ['UNIVERSAL','CRICKET'],
    id: '60091a9e9582605ff6896686',
    createdBy: '54905d04a49acf605d645271',
    createdByUserName: 'test.admin@coral.co.uk',
    updatedBy: '54905d04a49acf605d645271',
    updatedByUserName: 'test.admin@coral.co.uk',
    createdAt: '2021-01-21T06:09:34.087Z',
    updatedAt: '2021-01-21T09:51:14.538Z',
    sortOrder: 0,
    generatedId: '812002',
    name: 'string',
    icon: {
      filename: 'string',
      originalname: 'string',
      path: 'string',
      size: 'string',
      filetype: 'string',
    },
    startDate: new Date().toISOString(),
    contestId: null,
    entryStake: 'string',
    isFreeBetsAllowed: true,
    prizePool: null,
    payTable: [
      {
        type: 'string',
        value: 'string',
        text: 'string',
        icon: {
          filename: 'string',
          originalname: 'string',
          path: 'string',
          size: 'string',
          filetype: 'string',
        },
        signPosting: {
          filename: 'string',
          originalname: 'string',
          path: 'string',
          size: 'string',
          filetype: 'string',
        },
        percentageOfField: 'string',
        numberOfEntries: 'string',
      },
    ],
    sponsorText: 'string',
    sponsorLogo: {
      filename: 'string',
      originalname: 'string',
      path: 'string',
      size: 'string',
      filetype: 'string',
    },
    size: 'string',
    teams: 'string',
    description: null,
    blurb: null,
    entryConfirmationText: 'true',
    nextContestId: 'string',
    display: 'string',
    brand: 'string',
    isActive: null,
  },
  {
    id: '60091a9e9582605ff6896687',
    createdBy: '54905d04a49acf605d645271',
    createdByUserName: 'test.admin@coral.co.uk',
    updatedBy: '54905d04a49acf605d645271',
    updatedByUserName: 'test.admin@coral.co.uk',
    createdAt: '2021-01-21T06:09:34.087Z',
    updatedAt: '2021-01-21T09:51:14.538Z',
    sortOrder: 0,
    generatedId: '812002',
    name: 'string',
    icon: {
      filename: 'string',
      originalname: 'string',
      path: 'string',
      size: 'string',
      filetype: 'string',
    },
    startDate: 'string',
    contestId: null,
    entryStake: 'string',
    isFreeBetsAllowed: true,
    prizePool: null,
    payTable: [
      {
        type: 'string',
        value: 'string',
        text: 'string',
        icon: {
          filename: 'string',
          originalname: 'string',
          path: 'string',
          size: 'string',
          filetype: 'string',
        },
        signPosting: {
          filename: 'string',
          originalname: 'string',
          path: 'string',
          size: 'string',
          filetype: 'string',
        },
        percentageOfField: 'string',
        numberOfEntries: 'string',
      },
    ],
    sponsorText: 'string',
    sponsorLogo: {
      filename: 'string',
      originalname: 'string',
      path: 'string',
      size: 'string',
      filetype: 'string',
    },
    size: 'string',
    teams: 'string',
    description: null,
    blurb: null,
    entryConfirmationText: 'true',
    nextContestId: 'string',
    display: 'string',
    brand: 'string',
    isActive: null,
  },
  {
    id: '60091a9e9582605ff68966876',
    createdBy: '54905d04a49acf60d645271',
    createdByUserName: 'test.admin@coral.co.uk',
    updatedBy: '54905d04a49acf605d645271',
    updatedByUserName: 'test.admin@coral.co.uk',
    createdAt: '2021-01-21T06:09:34.087Z',
    updatedAt: '2021-01-21T09:51:14.538Z',
    sortOrder: 0,
    generatedId: '812002',
    name: 'string',
    icon: {
      filename: 'string',
      originalname: 'string',
      path: 'string',
      size: 'string',
      filetype: 'string',
    },
    startDate: 'string',
    contestId: null,
    entryStake: 'string',
    isFreeBetsAllowed: true,
    prizePool: null,
    payTable: [
      {
        type: 'string',
        value: 'string',
        text: 'string',
        icon: {
          filename: 'string',
          originalname: 'string',
          path: 'string',
          size: 'string',
          filetype: 'string',
        },
        signPosting: {
          filename: 'string',
          originalname: 'string',
          path: 'string',
          size: 'string',
          filetype: 'string',
        },
        percentageOfField: 'string',
        numberOfEntries: 'string',
      },
    ],
    sponsorText: 'string',
    sponsorLogo: {
      filename: 'string',
      originalname: 'string',
      path: 'string',
      size: 'string',
      filetype: 'string',
    },
    size: 'string',
    teams: 'string',
    description: null,
    blurb: null,
    entryConfirmationText: 'true',
    nextContestId: 'string',
    display: 'string',
    brand: 'string',
    isActive: null,
  }
] as any;

  export const CREATE_CONTEST_MOCK = {
    id: '60091a9e9582605ff6896686',
    createdBy: '54905d04a49acf605d645271',
    createdByUserName: 'test.admin@coral.co.uk',
    updatedBy: '54905d04a49acf605d645271',
    updatedByUserName: 'test.admin@coral.co.uk',
    createdAt: '2021-01-21T06:09:34.087Z',
    updatedAt: '2021-01-21T09:51:14.538Z',
    sortOrder: 0,
    generatedId: '812002',
    name: 'string',
    icon: {
      filename: 'string',
      originalname: 'string',
      path: 'string',
      size: 'string',
      filetype: 'string',
    },
    startDate: 'string',
    contestId: null,
    entryStake: 'string',
    isFreeBetsAllowed: true,
    prizePool: null,
    payTable: [
      {
        type: 'string',
        value: 'string',
        text: 'string',
        icon: {
          filename: 'string',
          originalname: 'string',
          path: 'string',
          size: 'string',
          filetype: 'string',
        },
        signPosting: {
          filename: 'string',
          originalname: 'string',
          path: 'string',
          size: 'string',
          filetype: 'string',
        },
        percentageOfField: 'string',
        numberOfEntries: 'string',
      },
    ],
    sponsorText: 'string',
    sponsorLogo: {
      filename: 'string',
      originalname: 'string',
      path: 'string',
      size: 'string',
      filetype: 'string',
    },
    size: 'string',
    teams: 'string',
    description: null,
    blurb: null,
    entryConfirmationText: 'true',
    nextContestId: 'string',
    display: 'string',
    brand: 'string',
    isActive: null,
  };

export const REORDER_MOCK = {
    id: '5fd20007eecbb12b1e9678a1',
    order: [
      '5fd20007eecbb12b1e9678a1',
      '5fd20021eecbb12b1e9678a3',
      '5fd775d551b2c11cb747e20c',
      '5fd99526be7df85d739c6f6d',
      '5fd775d551b2c11cb747e20b',
      '5fd775d651b2c11cb747e20d'
    ]
  };

export const REMOVE_CONTEST_MOCK =  ['60091a9e9582605ff6896686', '60091a9e9582605ff6896685'];
