#$ gradle bootBuildImage && docker-compose up | tee boot.log

version: '3.8'

services:

  zookeeper:
    container_name: featured_zoo
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: featured_kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    # volumes:
      # - /var/run/docker.sock:/var/run/docker.sock

  sports-featured-ms:
    container_name: sports-featured-ms
    # build: .
    image: sports-featured-ms:latest
    depends_on:
      - kafka
    ports:
      - "8088:8088"
      - "8081:8081"
    environment:
      server.port: 8088
      socket.websocket.port: 8081
      kafka.bootstrap-servers: kafka:9092
      logging.level.root: info
      logging.level.org.apache.kafka: error
      spring.profiles.active: LOCAL

  inplay-ms:
    container_name: inplay-ms
    # build: .
    image: inplay-ms:latest
    depends_on:
      - kafka
    ports:
      - "9088:9088"
      - "9081:9081"
    environment:
      server.port: 9088
      socket.websocket.port: 9081
      kafka.bootstrap-servers: kafka:9092
      logging.level.root: info
      logging.level.org.apache.kafka: error
      spring.profiles.active: LOCAL
