
export const PRE_OVERLAY = {
    INTRODUCTION_OVERLAY_ID: '#fiveaside-pre-event-tutorial',
    PRIZEPOOL_OVERLAY_ID : '#fiveaside-prizepool-tutorial',
    RULESAREA_OVERLAY_ID : '#fiveaside-rulesarea-tutorial',
    ENTRYAREA_OVERLAY_ID : '#fiveaside-entrybutton-tutorial',
    ANOTHERTEAM_OVERLAY_ID : '#fiveaside-buildanother-team',
    ANOTHERTEAM_ENTRIES_OVERLAY_ID : '#fiveaside-buildanother-team-entries',
    RULESBUTTON_OVERLAY_ID : '#fiveaside-rulesbutton-tutorial',
    LEFT : 'left',
    RIGHT : 'right',
    TOP : 'top',
    HEIGHT : 'height',
    WIDTH : 'width',
    BOTTOM : 'bottom',
    MOBILE_VIEW : 'mobile',
    PRIZE_POOL_CONTAINER : '.prize-pool-container',
    RECTANGLE_ID : '#rectangle',
    TOP_ARROW_CLASS : '.top-arrow',
    PRIZE_POOL_TEXT : '#prize-pool-text',
    GOTO_RULES_ID : '#go-to-rules',
    GOTO_ENTRY_ID : '#go-to-entry',
    RULES_ENTRY_AREA_CLASS : '.rules-entry-area',
    RULES_CONTAINER: '#rules-container',
    RULES_AREA_ID : '#rules-area',
    RULES_TOP_ARROW_CLASS : '.rules-top-arrow',
    RULES_AREA_TEXT_ID : '#rules-area-text',
    ENTRY_AREA_ID : '#entry-area',
    ENTRY_TOP_ARROW_CLASS : '.entry-top-arrow',
    ENTRY_AREA_TEXT_ID : '#entry-area-text',
    BUILD_BUTTON_CLASS : '.build-btn',
    GO_TORULES_BTN : '#go-to-rules-button',
    SIDE_ARROW_CLASS : '.side-arrow',
    FOCUS_CLASS: '.focus',
    ENTRY_AREA_ANOTHER_ID : '#entry-area-another',
    USER_ENTRY_ID : '#user-entry',
    ENTRY_AREA_ARROW : '#entry-area-arrow',
    GOTO_END_ID : '#go-to-end',
    REMOVE_CLASS : 'removeClass',
    ADD_CLASS : 'addClass',
    ACTIVE : 'active',
    CLASS : 'class',
    SET_STYLE : 'setStyle',
    ANOTHER_BUTTON_ARROW_ID : '#another-build-arrow',
    MY_ENTRIES_CLASS : '.my-entries',
    RULES_INFO_2 : '.rules-info-2',
    COUNTRY_FLAGS: '.country-flags',
    RULES_BTN: '.rules-btn',
    ENTRY_AREA_BTN_ID: '#entry-area-button',
    BORDER: 'border',
    RULES_BTN_AREA_ID: '#rules-button-area',
    RULES_INFO_3 : '.rules-info-3',
    BOX_SHADOW: 'box-shadow',
    Z_INDEX: 'z-index',
    TOP_BAR: 'top-bar',
    ENTRY_AREA_BOX: '#entry-area-box',
    ANOTHER_BUILD_ARROW_DOWN: '.another-build-arrow-down',
    ANOTHER_ENTRY_AREA_TEXT: '#another-entry-area-text',
    GO_TO_SECOND_HALF: '#go-to-second-half',
    ANOTHER_FOOTER_ID: '#another-footer',
    GO_TO_FINISH_ID: '#go-to-finish',
    ENTRY_AREA_NEW_ANOTHER_ID : '#entry-area-another-new'
  };
export const PRE_DOM_ELEMENT = {
  CONTEST_OVERLAY_CLASS_NAME: 'fiveaside-pre-overlay',
  INTRODUCTION_OVERLAY_ID: 'fiveaside-pre-event-tutorial',
  PRIZE:[PRE_OVERLAY.RECTANGLE_ID, PRE_OVERLAY.RECTANGLE_ID, PRE_OVERLAY.RECTANGLE_ID],
  TOP_WIDTH_HEIGHT:[PRE_OVERLAY.TOP, PRE_OVERLAY.WIDTH, PRE_OVERLAY.HEIGHT],
  TOP_WIDTH_HEIGHT_POSITION:[PRE_OVERLAY.TOP, PRE_OVERLAY.WIDTH, PRE_OVERLAY.HEIGHT, 'position'],
  TOP_WIDTH_HEIGHT_LEFT:[PRE_OVERLAY.TOP, PRE_OVERLAY.WIDTH, PRE_OVERLAY.HEIGHT, PRE_OVERLAY.LEFT],
  PRIZE_MODULE:[PRE_OVERLAY.TOP_ARROW_CLASS, PRE_OVERLAY.PRIZE_POOL_TEXT, PRE_OVERLAY.GOTO_RULES_ID],
  // eslint-disable-next-line max-len
  PRIZE_DOM:[PRE_OVERLAY.RECTANGLE_ID, PRE_OVERLAY.TOP_ARROW_CLASS, PRE_OVERLAY.PRIZE_POOL_TEXT, PRE_OVERLAY.GOTO_RULES_ID],
  PRIZE_DOM_RECT:[PRE_OVERLAY.LEFT, PRE_OVERLAY.BOTTOM, PRE_OVERLAY.BOTTOM, PRE_OVERLAY.BOTTOM],
  // eslint-disable-next-line max-len
  RULES_MODULE:[PRE_OVERLAY.RULES_TOP_ARROW_CLASS, PRE_OVERLAY.RULES_AREA_TEXT_ID, PRE_OVERLAY.GOTO_ENTRY_ID],
  TOP_HEIGHT_LEFT_WIDTH:[PRE_OVERLAY.TOP, PRE_OVERLAY.HEIGHT, PRE_OVERLAY.LEFT, PRE_OVERLAY.WIDTH],
  RULES_RECT:[PRE_OVERLAY.RULES_TOP_ARROW_CLASS, PRE_OVERLAY.RULES_AREA_TEXT_ID, PRE_OVERLAY.GOTO_ENTRY_ID],
  BOTTOM_TOP_TOP:[PRE_OVERLAY.BOTTOM, PRE_OVERLAY.TOP, PRE_OVERLAY.TOP],
  // eslint-disable-next-line max-len
  BUILD_BTN_MODULE:[PRE_OVERLAY.ENTRY_TOP_ARROW_CLASS, PRE_OVERLAY.ENTRY_AREA_TEXT_ID, PRE_OVERLAY.GO_TORULES_BTN],
  // eslint-disable-next-line max-len
  BUILD_BTN_RECT:[PRE_OVERLAY.ENTRY_TOP_ARROW_CLASS, PRE_OVERLAY.ENTRY_AREA_TEXT_ID, PRE_OVERLAY.GO_TORULES_BTN],
  BUILD_AREA_RECT:[PRE_OVERLAY.ANOTHER_BUILD_ARROW_DOWN, PRE_OVERLAY.ANOTHER_ENTRY_AREA_TEXT, PRE_OVERLAY.GO_TO_FINISH_ID]
};
