clone:
  depth: full
pipelines:

  default:
    - step:
        name: build
        image: azul/zulu-openjdk:17.0.5
        caches:
          - gradle
          - gradlewrapper
        script:
          - chmod +x gradlew
          - ./gradlew test build
    - step:
        name: test
        image: azul/zulu-openjdk:17.0.5
        caches:
          - sonarcloud
        script:
          - chmod +x gradlew
          - ./gradlew test sonarqube
           -Dsonar.coverage.exclusions=src/main/java/com/ladbrokescoral/oxygen/seo/configuration/*.java,src/main/java/com/ladbrokescoral/oxygen/seo/dto/*.java

  pull-requests:
    '**':
      - step:
          name: build
          image: azul/zulu-openjdk:17.0.5
          script:
            - chmod +x gradlew
            - ./gradlew test build


      - step:
          name: test
          image: azul/zulu-openjdk:17.0.5
          script:
            - chmod +x gradlew
            - ./gradlew test sonarqube
                -Dsonar.pullrequest.key=$BITBUCKET_PR_ID
                -Dsonar.pullrequest.base=$BITBUCKET_PR_DESTINATION_BRANCH
                -Dsonar.pullrequest.branch=$BITBUCKET_BRANCH
                -Dsonar.coverage.exclusions=src/main/java/com/ladbrokescoral/oxygen/seo/configuration/*.java,src/main/java/com/ladbrokescoral/oxygen/seo/dto/*.java

definitions:
  caches:
    sonarcloud: ~/.sonar/cache
    gradlewrapper: ~/.gradle/wrapper
