dev0:
  api_url: https://cms-dev0.coralsports.dev.cloud.ladbrokescoral.com/v1/api/
  public_api_url: https://cms-dev0.ladbrokes.com/cms/api/
dev1:
  api_url: https://cms-dev1.coralsports.dev.cloud.ladbrokescoral.com/v1/api/
  public_api_url: https://cms-dev1.ladbrokes.com/cms/api/
tst0:
  api_url: https://cms-tst0.coralsports.nonprod.cloud.ladbrokescoral.com/v1/api/
  public_api_url: https://cms-tst0.ladbrokes.com/cms/api/
tst1:
  api_url: https://cms-tst1.coralsports.nonprod.cloud.ladbrokescoral.com/v1/api/
  public_api_url: https://cms-tst1.ladbrokes.com/cms/api/
stg0:
  api_url: https://cms-stg0.coralsports.nonprod.cloud.ladbrokescoral.com/v1/api/
  public_api_url: https://cms-stg.ladbrokes.com/cms/api/
hlv0:
  api_url: https://cms-hlv0.coralsports.nonprod.cloud.ladbrokescoral.com/v1/api/
  public_api_url: https://cms-hl.ladbrokes.com/cms/api/
hlv1:
  api_url: https://cms-hlv1.coralsports.nonprod.cloud.ladbrokescoral.com/v1/api/
  public_api_url: https://cms-hlv1.ladbrokes.com/cms/api/
hlv2:
  api_url: https://cms-hlv2.coralsports.nonprod.cloud.ladbrokescoral.com/v1/api/
  public_api_url: https://cms-hl2.ladbrokes.com/cms/api/
prd0:
  api_url: https://cms-prd0.coralsports.prod.cloud.ladbrokescoral.com/v1/api/
  public_api_url: https://cms-prod.ladbrokes.com/cms/api/
# https://confluence.egalacoral.com/display/SPI/CMS-API+Endpoints