dev0:
  api_url: https://cms-dev0.coralsports.dev.cloud.ladbrokescoral.com/v1/api/
  public_api_url: https://cms-dev0.coral.co.uk/cms/api/
dev1:
  api_url: https://cms-dev1.coralsports.dev.cloud.ladbrokescoral.com/v1/api/
  public_api_url: https://cms-dev1.coral.co.uk/cms/api/
dev2:
  api_url: https://cms-dev2.coralsports.dev.cloud.ladbrokescoral.com/v1/api/
  public_api_url: https://cms-dev2.coral.co.uk/cms/api/
tst0:
  api_url: https://cms-tst0.coralsports.nonprod.cloud.ladbrokescoral.com/v1/api/
  public_api_url: https://cms-tst0.coral.co.uk/cms/api/
tst1:
  api_url: https://cms-tst1.coralsports.nonprod.cloud.ladbrokescoral.com/v1/api/
  public_api_url: https://cms-tst1.coral.co.uk/cms/api/
stg0:
  api_url: https://cms-stg0.coralsports.nonprod.cloud.ladbrokescoral.com/v1/api/
  public_api_url: https://cms-stg.coral.co.uk/cms/api/
hlv0:
  api_url: https://cms-hlv0.coralsports.nonprod.cloud.ladbrokescoral.com/v1/api/
  public_api_url: https://cms-hl.coral.co.uk/cms/api/
hlv1:
  api_url: https://cms-hlv1.coralsports.nonprod.cloud.ladbrokescoral.com/v1/api/
  public_api_url: https://cms-hlv1.coral.co.uk/cms/api/
hlv2:
  api_url: https://cms-hlv2.coralsports.nonprod.cloud.ladbrokescoral.com/v1/api/
  public_api_url: https://cms-hl2.coral.co.uk/cms/api/
prd0:
  api_url: https://cms-prd0.coralsports.prod.cloud.ladbrokescoral.com/v1/api/
  public_api_url: https://cms.coral.co.uk/cms/api/
# https://confluence.egalacoral.com/display/SPI/CMS-API+Endpoints
