import { Competition, Promotion, SportCategory } from '@root/app/client/private/models';

export const CREATE_PROMOTION_REQ_MOCK: Promotion = {
    title: 'Sample_Bet_Pack',
    promotionId: null,
    openBetId: '',
    popupTitle: '',
    promoKey: '16543',
    description: '<p>Bet Pack Enabler config sample description</p>\n<p> </p>\n<p> </p>\n<p><a class="btn btn-style1 full-width bet-pack-btn">BUY BET PACK</a></p>',
    vipLevelsInput: '',
    requestId: '',
    validityPeriodStart: '2021-09-15T12:00:55.075Z',
    validityPeriodEnd: '2021-09-16T12:00:55.075Z',
    showToCustomer: 'both',
    isSignpostingPromotion: false,
    id: '6141eb2e232c993d48cc3f81',
    updatedBy: '',
    updatedAt: '',
    createdBy: '',
    createdAt: '',
    title_brand: '',
    sortOrder: 0,
    heightMedium: 0,
    widthMedium: 0,
    uriMedium: 'sdsiuwqydiueydiew',
    htmlMarkup: '',
    promotionText: '',
    shortDescription: 'Bet Pack Promo Configs',
    vipLevels: [],
    lang: '',
    brand: 'bma',
    categoryId: [],
    disabled: false,
    updatedByUserName: '',
    createdByUserName: '',
    competitionId: [],
    useDirectFileUrl: false,
    betPack: {
        isBetPack: true,
        bodyText: 'Bet Pack Enabler',
        redirectUrl: 'http://localhost:4200',
        offerId: '123',
        triggerIds: '1234',
        betValue: '23',
        lowFundMessage: 'Sorry!! Low Funds',
        notLoggedinMessage: 'Please Log in !!',
        errorMessage: 'Errorr!!!'
    }
} as any;

export const SPORT_CATEGORY_MOCK: SportCategory[] = [
    {
        id: '5ad1aaef6b596e000a5b7233',
        sortOrder: 98,
        alt: 'Horse Racing',
        brand: 'bma',
        categoryId: 119,
        disabled: true,
        tier: 'UNTIED',
        filename: {
            filename: 'cfd435a2e2e7802fd01416aae0d7d37d.png',
            originalfilename: 'racing.png',
            path: 'public/images/uploads',
            size: 932,
            filetype: 'image/png'
        },
        heightMedium: 32,
        heightMediumIcon: 32,
        heightSmall: 104,
        heightSmallIcon: 20,
        icon: {
            filename: '15a8223dd39a458366203dc72713469b.png',
            originalfilename: 'racing.png',
            path: 'public/images/uploads',
            size: 932,
            filetype: 'image/png'
        },
        imageTitle: 'Grand National',
        inApp: false,
        isTopSport: false,
        key: null,
        lang: 'en',
        link: null,
        path: 'public/images/uploads',
        outrightSport: false,
        multiTemplateSport: false,
        oddsCardHeaderType: null,
        typeIds: null,
        dispSortNames: null,
        primaryMarkets: null,
        showInMenu: false,
        spriteClass: 'GrandNational',
        ssCategoryCode: 'Horse Racing',
        svg: null,
        svgFilename: null,
        svgId: 'icon-horse-racing',
        targetUri: 'http://localhost:4200',
        uriMedium: 'public/images/uploads/sport_category/medium/GrandNational.png',
        uriMediumIcon: 'public/images/uploads/sport_category/medium_icon/GrandNational.png',
        uriSmall: 'public/images/uploads/sport_category/small/GrandNational.png',
        uriSmallIcon: 'public/images/uploads/sport_category/small_icon/GrandNational.png',
        widthMedium: 32,
        widthMediumIcon: 32,
        widthSmall: 104,
        widthSmallIcon: 20,
        collectionType: '/sport_category/',
        showInAZ: false,
        showInHome: false,
        showInPlay: false,
        showScoreboard: false,
        heightLarge: 96,
        heightLargeIcon: 96,
        uriLarge: 'public/images/uploads/sport_category/large/GrandNational.png',
        widthLarge: 96,
        widthLargeIcon: 96,
        scoreBoardUri: null,
        inplayEnabled: false,
        highlightCarouselEnabled: true,
        quickLinkEnabled: true,
        inplaySportModule: {
            enabled: true,
            inplayCount: 23
        },
        createdBy: '5937d24f48fbad00051ef2e5',
        createdByUserName: null,
        updatedBy: '5b1506a5c9e77c000114dded',
        updatedByUserName: null,
        createdAt: '2018-04-14T07:17:03.512Z',
        updatedAt: '2021-07-21T19:34:02.794Z',
        isRealSport: () => false
    }] as any;

export const COMPETITIONS_MOCK: Competition[] = [{
    id: '606322c6b4ca436c99666a15',
    createdBy: '5bcd70b3c9e77c00019ee831',
    createdByUserName: null,
    updatedBy: '5645b8a220bd9e0800afdc57',
    updatedByUserName: null,
    createdAt: '2021-03-30T13:08:22.534Z',
    updatedAt: '2021-09-08T15:22:47.883Z',
    brand: 'bma',
    name: 'CompetitionTes',
    uri: 'http://localhost:4200',
    enabled: false,
    typeId: 1234,
    competitionTabs: [],
    competitionParticipants: []
}];
