GET https://coral-cms-api-dev1.symphony-solutions.eu/v1/api/dashboard/brand/bma?date=2018-02-20
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1NDkwNWQwNGE0OWFjZjYwNWQ2NDUyNzEiLCJleHAiOjE1MTkxMzQwMjZ9.uFQXZC2J0STgOUX9q9xiyiXGP7P72btjmOPDAtFC1rgGehOjJJFbrbjMQfVVUCjBpMbcdc2gNQmgilAp0H0cvw

###
