PUT http://localhost:8080/v1/api/maintenance-page/5a982272c9e77c00011c6f9b
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1NDkwNWQwNGE0OWFjZjYwNWQ2NDUyNzEiLCJleHAiOjE1MjkwNTI1MjR9.WRBIKc7YbqXY4Giyv9HC4Zu-Tv1_wYmE3-r55dZ25DiDXHZcvUerx5kgpNsfM-FlHb4GR88CFcwM7AQHbMU9yw
Content-Type: application/json

< maintance.json

###
