POST https://coral-cms-api-dev0.symphony-solutions.eu/v1/api/home-module/
accept:application/json
content-type:application/json
authorization:eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1NDkwNWQwNGE0OWFjZjYwNWQ2NDUyNzEiLCJleHAiOjE1MTk4MzM3OTV9.23FjSThgIZ8yMHCmfO1V89pWD0hrfxiPtVuxgXKY46q1VqiU0Dv3d2aRZMk9CyoA8Ij1MDQi-8O_YsJqVf8HHQ

< module.json

###
