POST http://localhost:8080/v1/api/odds-boost
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1YTk0MWRjM2M5ZTc3YzAwMDE3YzBkNDAiLCJleHAiOjE1NDE2NzgyMzB9.IAp_b359CADC-o-yHiAyTh8ibiTcBM5Y58sYG3LNdqwUF0u8Of72LmWm8UCGxlXkMj7MydnSLhqwBLGJEh5Iiw
Content-Type: application/json

< odds-boost.json

###

GET http://localhost:8080/v1/api/odds-boost/bma
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1YTk0MWRjM2M5ZTc3YzAwMDE3YzBkNDAiLCJleHAiOjE1NDE2OTEzMzJ9.3QUM26fyVH65Wcrx6dGZorDnbsw_FCx4dhfSzO2TQDKTPCy5xlVeWUWntyw_RiO-ntaV4LFR5EYYlAzb33syhg
Content-Type: application/json

###
