POST https://api.ccu.akamai.com/ccu/v2/queues/default
Authorization: Basic Y29yYWwuY2lAc3ltcGhvbnktc29sdXRpb25zLmV1OkRpRFdHQjJ1aVFtTWVFRDZnbmczYXlCcndDNzM2aQ==
Content-Type: application/json

< payload.json

###
