export const FREEBET_ERROR_STATUSES = [
  'SERVICE_ERROR',
  'VOUCHER_INVALID_LENGTH',
  'VOUCHER_INVALID',
  'VOUCHER_ALREADY_REDEEMED',
  'VOUCHER_CLAIMED_MAX',
  'VOUCHER_NOT_YET_VALID',
  'VOUCHER_PAST_VALID',
  'VOUCHER_NOT_REDEEMED',
  'VOUCHER_SERVER_ERROR',
  'VOUCHER_NO_DATA'
];
