//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.25 at 12:50:43 PM EEST 
//


package com.egalacoral.api.siteserv;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Event complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Event">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}error" minOccurs="0"/>
 *         &lt;sequence>
 *           &lt;choice maxOccurs="unbounded" minOccurs="0">
 *             &lt;element ref="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}market"/>
 *             &lt;element ref="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}eventPeriod"/>
 *             &lt;element ref="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}eventParticipant"/>
 *             &lt;element ref="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}eventFact"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *       &lt;/choice>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="eventStatusCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isActive" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obBoolean" />
 *       &lt;attribute name="isDisplayed" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obBoolean" />
 *       &lt;attribute name="displayOrder" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="siteChannels" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obSetOfStrings" />
 *       &lt;attribute name="eventSortCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="startTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="suspendAtTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="rawIsOffCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isStarted" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obBoolean" />
 *       &lt;attribute name="isResulted" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obBoolean" />
 *       &lt;attribute name="isFinished" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obBoolean" />
 *       &lt;attribute name="classId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="typeId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subTypeId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sportId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="raceNumber" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="streamAvailableInCountries" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obSetOfStrings" />
 *       &lt;attribute name="liveServChannels" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obSetOfStrings" />
 *       &lt;attribute name="liveServChildrenChannels" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obSetOfStrings" />
 *       &lt;attribute name="liveServLastMsgId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="categoryId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="categoryCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="categoryName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="className" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="classDisplayOrder" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="classSortCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="classFlagCodes" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obSetOfStrings" />
 *       &lt;attribute name="typeName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="typeDisplayOrder" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="typeFlagCodes" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obSetOfStrings" />
 *       &lt;attribute name="subTypeName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subTypeDisplayOrder" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="isOpenEvent" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obBoolean" />
 *       &lt;attribute name="isNext24HourEvent" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obBoolean" />
 *       &lt;attribute name="isLiveNowEvent" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obBoolean" />
 *       &lt;attribute name="isLiveNowOrFutureEvent" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obBoolean" />
 *       &lt;attribute name="drilldownTagNames" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obSetOfStrings" />
 *       &lt;attribute name="isAvailable" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obBoolean" />
 *       &lt;attribute name="mediaTypeCodes" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obSetOfStrings" />
 *       &lt;attribute name="venue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cashoutAvail" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="raceStage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Event", propOrder = {
    "error",
    "marketOrEventPeriodOrEventParticipant"
})
public class Event {

    protected Error error;
    @XmlElements({
        @XmlElement(name = "eventFact", type = EventFact.class),
        @XmlElement(name = "eventPeriod", type = EventPeriod.class),
        @XmlElement(name = "market", type = Market.class),
        @XmlElement(name = "eventParticipant", type = EventParticipant.class)
    })
    protected List<Object> marketOrEventPeriodOrEventParticipant;
    @XmlAttribute
    protected String id;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String eventStatusCode;
    @XmlAttribute
    protected String isActive;
    @XmlAttribute
    protected String isDisplayed;
    @XmlAttribute
    protected BigInteger displayOrder;
    @XmlAttribute
    protected String siteChannels;
    @XmlAttribute
    protected String eventSortCode;
    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startTime;
    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar suspendAtTime;
    @XmlAttribute
    protected String rawIsOffCode;
    @XmlAttribute
    protected String isStarted;
    @XmlAttribute
    protected String isResulted;
    @XmlAttribute
    protected String isFinished;
    @XmlAttribute
    protected String classId;
    @XmlAttribute
    protected String typeId;
    @XmlAttribute
    protected String subTypeId;
    @XmlAttribute
    protected String sportId;
    @XmlAttribute
    protected BigInteger raceNumber;
    @XmlAttribute
    protected String streamAvailableInCountries;
    @XmlAttribute
    protected String liveServChannels;
    @XmlAttribute
    protected String liveServChildrenChannels;
    @XmlAttribute
    protected String liveServLastMsgId;
    @XmlAttribute
    protected String categoryId;
    @XmlAttribute
    protected String categoryCode;
    @XmlAttribute
    protected String categoryName;
    @XmlAttribute
    protected String className;
    @XmlAttribute
    protected BigInteger classDisplayOrder;
    @XmlAttribute
    protected String classSortCode;
    @XmlAttribute
    protected String classFlagCodes;
    @XmlAttribute
    protected String typeName;
    @XmlAttribute
    protected BigInteger typeDisplayOrder;
    @XmlAttribute
    protected String typeFlagCodes;
    @XmlAttribute
    protected String subTypeName;
    @XmlAttribute
    protected BigInteger subTypeDisplayOrder;
    @XmlAttribute
    protected String isOpenEvent;
    @XmlAttribute
    protected String isNext24HourEvent;
    @XmlAttribute
    protected String isLiveNowEvent;
    @XmlAttribute
    protected String isLiveNowOrFutureEvent;
    @XmlAttribute
    protected String drilldownTagNames;
    @XmlAttribute
    protected String isAvailable;
    @XmlAttribute
    protected String mediaTypeCodes;
    @XmlAttribute
    protected String venue;
    @XmlAttribute
    protected String cashoutAvail;
    @XmlAttribute
    protected String raceStage;

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link Error }
     *     
     */
    public Error getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link Error }
     *     
     */
    public void setError(Error value) {
        this.error = value;
    }

    /**
     * Gets the value of the marketOrEventPeriodOrEventParticipant property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the marketOrEventPeriodOrEventParticipant property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarketOrEventPeriodOrEventParticipant().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventFact }
     * {@link EventPeriod }
     * {@link Market }
     * {@link EventParticipant }
     * 
     * 
     */
    public List<Object> getMarketOrEventPeriodOrEventParticipant() {
        if (marketOrEventPeriodOrEventParticipant == null) {
            marketOrEventPeriodOrEventParticipant = new ArrayList<Object>();
        }
        return this.marketOrEventPeriodOrEventParticipant;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the eventStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventStatusCode() {
        return eventStatusCode;
    }

    /**
     * Sets the value of the eventStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventStatusCode(String value) {
        this.eventStatusCode = value;
    }

    /**
     * Gets the value of the isActive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsActive() {
        return isActive;
    }

    /**
     * Sets the value of the isActive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsActive(String value) {
        this.isActive = value;
    }

    /**
     * Gets the value of the isDisplayed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsDisplayed() {
        return isDisplayed;
    }

    /**
     * Sets the value of the isDisplayed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsDisplayed(String value) {
        this.isDisplayed = value;
    }

    /**
     * Gets the value of the displayOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDisplayOrder() {
        return displayOrder;
    }

    /**
     * Sets the value of the displayOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDisplayOrder(BigInteger value) {
        this.displayOrder = value;
    }

    /**
     * Gets the value of the siteChannels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteChannels() {
        return siteChannels;
    }

    /**
     * Sets the value of the siteChannels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteChannels(String value) {
        this.siteChannels = value;
    }

    /**
     * Gets the value of the eventSortCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventSortCode() {
        return eventSortCode;
    }

    /**
     * Sets the value of the eventSortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventSortCode(String value) {
        this.eventSortCode = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTime(XMLGregorianCalendar value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the suspendAtTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSuspendAtTime() {
        return suspendAtTime;
    }

    /**
     * Sets the value of the suspendAtTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSuspendAtTime(XMLGregorianCalendar value) {
        this.suspendAtTime = value;
    }

    /**
     * Gets the value of the rawIsOffCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRawIsOffCode() {
        return rawIsOffCode;
    }

    /**
     * Sets the value of the rawIsOffCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRawIsOffCode(String value) {
        this.rawIsOffCode = value;
    }

    /**
     * Gets the value of the isStarted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsStarted() {
        return isStarted;
    }

    /**
     * Sets the value of the isStarted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsStarted(String value) {
        this.isStarted = value;
    }

    /**
     * Gets the value of the isResulted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsResulted() {
        return isResulted;
    }

    /**
     * Sets the value of the isResulted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsResulted(String value) {
        this.isResulted = value;
    }

    /**
     * Gets the value of the isFinished property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsFinished() {
        return isFinished;
    }

    /**
     * Sets the value of the isFinished property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsFinished(String value) {
        this.isFinished = value;
    }

    /**
     * Gets the value of the classId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassId() {
        return classId;
    }

    /**
     * Sets the value of the classId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassId(String value) {
        this.classId = value;
    }

    /**
     * Gets the value of the typeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * Sets the value of the typeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeId(String value) {
        this.typeId = value;
    }

    /**
     * Gets the value of the subTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubTypeId() {
        return subTypeId;
    }

    /**
     * Sets the value of the subTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubTypeId(String value) {
        this.subTypeId = value;
    }

    /**
     * Gets the value of the sportId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSportId() {
        return sportId;
    }

    /**
     * Sets the value of the sportId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSportId(String value) {
        this.sportId = value;
    }

    /**
     * Gets the value of the raceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRaceNumber() {
        return raceNumber;
    }

    /**
     * Sets the value of the raceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRaceNumber(BigInteger value) {
        this.raceNumber = value;
    }

    /**
     * Gets the value of the streamAvailableInCountries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreamAvailableInCountries() {
        return streamAvailableInCountries;
    }

    /**
     * Sets the value of the streamAvailableInCountries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreamAvailableInCountries(String value) {
        this.streamAvailableInCountries = value;
    }

    /**
     * Gets the value of the liveServChannels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLiveServChannels() {
        return liveServChannels;
    }

    /**
     * Sets the value of the liveServChannels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLiveServChannels(String value) {
        this.liveServChannels = value;
    }

    /**
     * Gets the value of the liveServChildrenChannels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLiveServChildrenChannels() {
        return liveServChildrenChannels;
    }

    /**
     * Sets the value of the liveServChildrenChannels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLiveServChildrenChannels(String value) {
        this.liveServChildrenChannels = value;
    }

    /**
     * Gets the value of the liveServLastMsgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLiveServLastMsgId() {
        return liveServLastMsgId;
    }

    /**
     * Sets the value of the liveServLastMsgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLiveServLastMsgId(String value) {
        this.liveServLastMsgId = value;
    }

    /**
     * Gets the value of the categoryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * Sets the value of the categoryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryId(String value) {
        this.categoryId = value;
    }

    /**
     * Gets the value of the categoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryCode() {
        return categoryCode;
    }

    /**
     * Sets the value of the categoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryCode(String value) {
        this.categoryCode = value;
    }

    /**
     * Gets the value of the categoryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * Sets the value of the categoryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryName(String value) {
        this.categoryName = value;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

    /**
     * Gets the value of the classDisplayOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getClassDisplayOrder() {
        return classDisplayOrder;
    }

    /**
     * Sets the value of the classDisplayOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setClassDisplayOrder(BigInteger value) {
        this.classDisplayOrder = value;
    }

    /**
     * Gets the value of the classSortCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassSortCode() {
        return classSortCode;
    }

    /**
     * Sets the value of the classSortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassSortCode(String value) {
        this.classSortCode = value;
    }

    /**
     * Gets the value of the classFlagCodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassFlagCodes() {
        return classFlagCodes;
    }

    /**
     * Sets the value of the classFlagCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassFlagCodes(String value) {
        this.classFlagCodes = value;
    }

    /**
     * Gets the value of the typeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * Sets the value of the typeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeName(String value) {
        this.typeName = value;
    }

    /**
     * Gets the value of the typeDisplayOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTypeDisplayOrder() {
        return typeDisplayOrder;
    }

    /**
     * Sets the value of the typeDisplayOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTypeDisplayOrder(BigInteger value) {
        this.typeDisplayOrder = value;
    }

    /**
     * Gets the value of the typeFlagCodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeFlagCodes() {
        return typeFlagCodes;
    }

    /**
     * Sets the value of the typeFlagCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeFlagCodes(String value) {
        this.typeFlagCodes = value;
    }

    /**
     * Gets the value of the subTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubTypeName() {
        return subTypeName;
    }

    /**
     * Sets the value of the subTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubTypeName(String value) {
        this.subTypeName = value;
    }

    /**
     * Gets the value of the subTypeDisplayOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSubTypeDisplayOrder() {
        return subTypeDisplayOrder;
    }

    /**
     * Sets the value of the subTypeDisplayOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSubTypeDisplayOrder(BigInteger value) {
        this.subTypeDisplayOrder = value;
    }

    /**
     * Gets the value of the isOpenEvent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsOpenEvent() {
        return isOpenEvent;
    }

    /**
     * Sets the value of the isOpenEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsOpenEvent(String value) {
        this.isOpenEvent = value;
    }

    /**
     * Gets the value of the isNext24HourEvent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsNext24HourEvent() {
        return isNext24HourEvent;
    }

    /**
     * Sets the value of the isNext24HourEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsNext24HourEvent(String value) {
        this.isNext24HourEvent = value;
    }

    /**
     * Gets the value of the isLiveNowEvent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsLiveNowEvent() {
        return isLiveNowEvent;
    }

    /**
     * Sets the value of the isLiveNowEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsLiveNowEvent(String value) {
        this.isLiveNowEvent = value;
    }

    /**
     * Gets the value of the isLiveNowOrFutureEvent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsLiveNowOrFutureEvent() {
        return isLiveNowOrFutureEvent;
    }

    /**
     * Sets the value of the isLiveNowOrFutureEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsLiveNowOrFutureEvent(String value) {
        this.isLiveNowOrFutureEvent = value;
    }

    /**
     * Gets the value of the drilldownTagNames property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrilldownTagNames() {
        return drilldownTagNames;
    }

    /**
     * Sets the value of the drilldownTagNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrilldownTagNames(String value) {
        this.drilldownTagNames = value;
    }

    /**
     * Gets the value of the isAvailable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsAvailable() {
        return isAvailable;
    }

    /**
     * Sets the value of the isAvailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsAvailable(String value) {
        this.isAvailable = value;
    }

    /**
     * Gets the value of the mediaTypeCodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaTypeCodes() {
        return mediaTypeCodes;
    }

    /**
     * Sets the value of the mediaTypeCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaTypeCodes(String value) {
        this.mediaTypeCodes = value;
    }

    /**
     * Gets the value of the venue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVenue() {
        return venue;
    }

    /**
     * Sets the value of the venue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVenue(String value) {
        this.venue = value;
    }

    /**
     * Gets the value of the cashoutAvail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCashoutAvail() {
        return cashoutAvail;
    }

    /**
     * Sets the value of the cashoutAvail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCashoutAvail(String value) {
        this.cashoutAvail = value;
    }

    /**
     * Gets the value of the raceStage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRaceStage() {
        return raceStage;
    }

    /**
     * Sets the value of the raceStage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRaceStage(String value) {
        this.raceStage = value;
    }

}
