//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.25 at 12:50:43 PM EEST 
//


package com.egalacoral.api.siteserv;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ResultedOutcome complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResultedOutcome">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}error" minOccurs="0"/>
 *         &lt;sequence>
 *           &lt;choice maxOccurs="unbounded" minOccurs="0">
 *             &lt;element ref="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}resultedPrice"/>
 *             &lt;element ref="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}deadHeatReduction"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *       &lt;/choice>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="marketId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isDisplayed" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obBoolean" />
 *       &lt;attribute name="siteChannels" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obSetOfStrings" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="outcomeMeaningMajorCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="outcomeMeaningMinorCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="runnerNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="resultCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isResulted" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obBoolean" />
 *       &lt;attribute name="rawHandicapValue" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="rawHandicapScore" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="position" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="isFinished" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obBoolean" />
 *       &lt;attribute name="finishedAt" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="hasDeadHeatReduction" type="{http://schema.openbet.com/SiteServer/2.16/SSResponse.xsd}obBoolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResultedOutcome", propOrder = {
    "error",
    "resultedPriceOrDeadHeatReduction"
})
public class ResultedOutcome {

    protected Error error;
    @XmlElements({
        @XmlElement(name = "resultedPrice", type = ResultedPrice.class),
        @XmlElement(name = "deadHeatReduction", type = DeadHeatReduction.class)
    })
    protected List<Object> resultedPriceOrDeadHeatReduction;
    @XmlAttribute
    protected String id;
    @XmlAttribute
    protected String marketId;
    @XmlAttribute
    protected String isDisplayed;
    @XmlAttribute
    protected String siteChannels;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String outcomeMeaningMajorCode;
    @XmlAttribute
    protected String outcomeMeaningMinorCode;
    @XmlAttribute
    protected String runnerNumber;
    @XmlAttribute
    protected String resultCode;
    @XmlAttribute
    protected String isResulted;
    @XmlAttribute
    protected BigDecimal rawHandicapValue;
    @XmlAttribute
    protected BigInteger rawHandicapScore;
    @XmlAttribute
    protected BigInteger position;
    @XmlAttribute
    protected String isFinished;
    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar finishedAt;
    @XmlAttribute
    protected String hasDeadHeatReduction;

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link Error }
     *     
     */
    public Error getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link Error }
     *     
     */
    public void setError(Error value) {
        this.error = value;
    }

    /**
     * Gets the value of the resultedPriceOrDeadHeatReduction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resultedPriceOrDeadHeatReduction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResultedPriceOrDeadHeatReduction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResultedPrice }
     * {@link DeadHeatReduction }
     * 
     * 
     */
    public List<Object> getResultedPriceOrDeadHeatReduction() {
        if (resultedPriceOrDeadHeatReduction == null) {
            resultedPriceOrDeadHeatReduction = new ArrayList<Object>();
        }
        return this.resultedPriceOrDeadHeatReduction;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the marketId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketId() {
        return marketId;
    }

    /**
     * Sets the value of the marketId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketId(String value) {
        this.marketId = value;
    }

    /**
     * Gets the value of the isDisplayed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsDisplayed() {
        return isDisplayed;
    }

    /**
     * Sets the value of the isDisplayed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsDisplayed(String value) {
        this.isDisplayed = value;
    }

    /**
     * Gets the value of the siteChannels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteChannels() {
        return siteChannels;
    }

    /**
     * Sets the value of the siteChannels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteChannels(String value) {
        this.siteChannels = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the outcomeMeaningMajorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutcomeMeaningMajorCode() {
        return outcomeMeaningMajorCode;
    }

    /**
     * Sets the value of the outcomeMeaningMajorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutcomeMeaningMajorCode(String value) {
        this.outcomeMeaningMajorCode = value;
    }

    /**
     * Gets the value of the outcomeMeaningMinorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutcomeMeaningMinorCode() {
        return outcomeMeaningMinorCode;
    }

    /**
     * Sets the value of the outcomeMeaningMinorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutcomeMeaningMinorCode(String value) {
        this.outcomeMeaningMinorCode = value;
    }

    /**
     * Gets the value of the runnerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunnerNumber() {
        return runnerNumber;
    }

    /**
     * Sets the value of the runnerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunnerNumber(String value) {
        this.runnerNumber = value;
    }

    /**
     * Gets the value of the resultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultCode(String value) {
        this.resultCode = value;
    }

    /**
     * Gets the value of the isResulted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsResulted() {
        return isResulted;
    }

    /**
     * Sets the value of the isResulted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsResulted(String value) {
        this.isResulted = value;
    }

    /**
     * Gets the value of the rawHandicapValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRawHandicapValue() {
        return rawHandicapValue;
    }

    /**
     * Sets the value of the rawHandicapValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRawHandicapValue(BigDecimal value) {
        this.rawHandicapValue = value;
    }

    /**
     * Gets the value of the rawHandicapScore property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRawHandicapScore() {
        return rawHandicapScore;
    }

    /**
     * Sets the value of the rawHandicapScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRawHandicapScore(BigInteger value) {
        this.rawHandicapScore = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPosition(BigInteger value) {
        this.position = value;
    }

    /**
     * Gets the value of the isFinished property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsFinished() {
        return isFinished;
    }

    /**
     * Sets the value of the isFinished property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsFinished(String value) {
        this.isFinished = value;
    }

    /**
     * Gets the value of the finishedAt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFinishedAt() {
        return finishedAt;
    }

    /**
     * Sets the value of the finishedAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFinishedAt(XMLGregorianCalendar value) {
        this.finishedAt = value;
    }

    /**
     * Gets the value of the hasDeadHeatReduction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasDeadHeatReduction() {
        return hasDeadHeatReduction;
    }

    /**
     * Sets the value of the hasDeadHeatReduction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasDeadHeatReduction(String value) {
        this.hasDeadHeatReduction = value;
    }

}
