export enum TIME_SERVICE_ENUM {
    DATE_TIME_MONTH = 'HH:mm d MMM',
    DATE_TIME_MONTH_YEAR = 'HH:mm d MMMM y',
    FIVEASIDE_TIME_INTERVAL = 1000,
    DEFAULT_TIMER = '00:00',
    SKIP_SECONDS = '60',
    INITIAL_VALUE = 0
}
