-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgdgh11gSS+qK/XBE5
DUdICtQm9vbndvE5wi9KFH7DX0KgCgYIKoZIzj0DAQehRANCAARISOFjbTISfmAL
gueow8dH+LXOlOhFDWKv/7JTMi7LRq3HJ72aJuWHBvc0kjSHDrx/uctAsyxikuF+
2skj94gS
-----END PRIVATE KEY-----