cms:
  brand: bma
logging:
  level:
    com:
      amazonaws:
        request: INFO
promosandbox:
  distributed:
    prefix: HLV0
  topic:
    promo-config:
      concurrency: 1
      groupId: PROMO_CONFIG
      name: ${promosandbox.distributed.prefix}_promo-config-cr
