app:
    allowedOrigins: http://bm-tst1.coral.co.uk,https://bm-tst1.coral.co.uk,https://invictus.coral.co.uk,https://bm.coral.co.uk,https://bma-gn-tst2.coral.co.uk,https://bma-gn-stg2.coral.co.uk,https://bma-gn.coral.co.uk,https://bma-gn-hl.coral.co.uk,https://oxynative.coral.co.uk,https://bet-hl.coral.co.uk,https://new-invictus.coral.co.uk,https://connect-invictus.coral.co.uk,https://test-invictus.coral.co.uk,https://mustang-invictus.coral.co.uk,https://inplay-invictus.coral.co.uk,https://muckers-invictus.coral.co.uk,https://mustang-new-invictus.coral.co.uk,https://td-invictus.coral.co.uk,https://native-invictus.coral.co.uk,https://consul.service.local.coral.co.uk,https://korali-invictus.coral.co.uk,https://release-invictus.coral.co.uk,https://express.coral.co.uk,https://bet-stg2.coral.co.uk,https://bet-tst1.coral.co.uk,https://bet-tst2.coral.co.uk,https://bet-tst3.coral.co.uk,https://bet-tst4.coral.co.uk,https://bet.coral.co.uk,https://express-invictus.coral.co.uk,https://phoenix-invictus.coral.co.uk,https://korali2-invictus.coral.co.uk,https://muckers2-excalibur.ladbrokes.com,https://muckers2-invictus.coral.co.uk,https://connect-app.coral.co.uk,https://connect-app-tst1.coral.co.uk,https://connect-app-tst2.coral.co.uk,https://connect-app-stg2.coral.co.uk,https://fantom-invictus.coral.co.uk,https://fantom-excalibur.ladbrokes.com,https://desktop-invictus.coral.co.uk,https://muckers3-invictus.coral.co.uk,https://avengers-invictus.coral.co.uk,https://laffly-invictus.coral.co.uk,https://desktop-release-invictus.coral.co.uk,https://naughty-invictus.coral.co.uk,https://odds-invictus.coral.co.uk,https://hollow-invictus.coral.co.uk,https://graceful-invictus.coral.co.uk,https://grim-invictus.coral.co.uk,https://brave-invictus.coral.co.uk,https://silent-invictus.coral.co.uk,https://clumsy-invictus.coral.co.uk,https://amazing-invictus.coral.co.uk,https://cherry-excalibur.coral.co.uk,https://raspberry-excalibur.coral.co.uk,https://excalibur.coral.co.uk,https://nitro2-invictus.coral.co.uk,https://nitro2-excalibur.ladbrokes.com,https://beta2-sports.coral.co.uk,https://beta-sports.coral.co.uk/,https://beta2-sports.ladbrokes.com/,https://beta-sports.ladbrokes.com/
    name: ${spring.application.name}
aws:
    s3:
        bucket: promosandbox-coral-dev0
        region: eu-west-2
cms:
    brand: ladbrokes
dataCleanup:
    scheduler:
        cron: 0 0 */1 * * *
logging:
    level:
        com:
            entain:
                oxygen: INFO
        org:
            apache:
                kafka: ERROR
                spark: ERROR
            springframework:
                data:
                    mongodb:
                        repository:
                            query: INFO
                kafka: ERROR
        root: INFO
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            base-path: /actuator
            cors:
                allowed-origins: ${app.allowedOrigins}
            exposure:
                include: '*'
            path-mapping:
                health: /health
                info: /info
master:
    uri: local[*]
promosandbox:
    distributed:
        prefix: ${spring.profiles.active}
    kafka:
        admin:
            properties:
                bootstrap:
                    servers: ${promosandbox.kafka.bootstrap-servers}
        bootstrap-servers: localhost:9092
        consumer:
            auto-commit-interval: 1s
            auto-offset-reset: latest
            bootstrap-servers: ${promosandbox.kafka.bootstrap-servers}
            properties:
                partition:
                    assignment:
                        strategy: org.apache.kafka.clients.consumer.RoundRobinAssignor
    topic:
        promo-config:
            concurrency: 1
            groupId: PROMO_CONFIG
            name: ${promosandbox.distributed.prefix}_promo-config-cr

    mongodb:
        mongoUser: dev_user
        authSource: admin
        dbHosts: 10.152.50.232:27017,10.152.50.233:27017,10.152.50.234:27017
        dbName: promo-sandbox
        algorithm: DES
        passwordFile: mongodb/nonprod/promosandbox.bin
        passwordKeyfile: profilekey.pem
        replicaSet: coralpsbmongodb
    environments : DEV0,TST0,HLV0,HLV1,BTC2,BTL2,PRD0
    enableSecurity: false
retry:
    retryMaxAttempts: 3
server:
    port: 9090
spark:
    blockManager:
        port: 51811
    cores:
        max: 0
    driver:
        bindAddress: localhost
        host: localhost
        port: 51810
    executor:
        memory: 0
spring:
    application:
        name: promosandbox
    cloud:
        discovery:
            enabled: false
    config:
        discovery:
            enabled: false
    data:
        mongodb:
            auto-index-creation: true
            uri: mongodb://localhost:27017/promo-sandbox
    jackson:
        default-property-inclusion: NON_NULL
    profiles:
        active: LOCAL
springdoc:
    api-docs:
        path: /api-docs
    show-actuator: true
    swagger-ui:
        disable-swagger-default-url: true
        path: /index.html
update:
    promo:
        config:
            delay:
                scheduler: 45
time:
    zone: GMT
bpp:
    baseUrl: https://bpp.internal.tst.coral.co.uk/Proxy
    connectionTimeout: 10000
    maxConnections : 100
    acquireTimeout : 10
    readTimeout : 10
    writeTimeout: 10
