//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 09:52:26 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservice.authnReqApi.securityframework.sportsbook.openbet.com/authn", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.egalacoral.api.ws.authentication;
