export enum VANILLA_NATIVE_EVENTS {
  LOGIN_SCREEN_ACTIVE = 'Login_Screen_Active',
  LOGIN = 'LOGIN',
  LOGIN_FAILED = 'LOGIN_FAILED',
  AFTER_INITIAL_NAVIGATION = 'AFTER_INITIAL_NAVIGATION',
  LOGOUT = 'LOGOUT',
  OPEN_LOGIN_DIALOG = 'OPEN_LOGIN_DIALOG'
}
