export const EVENT_TYPES = {
  LIVE_EVENT: 'LIVE_EVENT',
  UPCOMING_EVENT: 'UPCOMING_EVENT',
  STREAM_EVENT: 'STREAM_EVENT',
  UPCOMING_STREAM_EVENT: 'UPCOMING_STREAM_EVENT'
};

export const EVENT_TYPES_BY_TOP_LEVEL = {
  LIVE_EVENT: 'livenow',
  UPCOMING_EVENT: 'upcoming',
  STREAM_EVENT: 'liveStream',
  UPCOMING_STREAM_EVENT: 'upcomingLiveStream'
};
