image: azul/zulu-openjdk:17.0.5

clone:
  depth: full

pipelines:

  default:
    - step:
        name: sonarqube (test, build)
        caches:
          - gradle
          - sonarcloud
        script:
          - ./gradlew test build sonarqube --scan 
            -Daudit.username='$OSSINDEX_USER'  
            -Daudit.password='$OSSINDEX_PASS'
            -Dsonarqube.gradle.plugin.version=4.2.1.3168

  pull-requests:
    '**':
      - step:
          caches:
            - gradle
            - sonarcloud
          script:
            - ./gradlew test build sonarqube
              -Daudit.username='$OSSINDEX_USER'  
              -Daudit.password='$OSSINDEX_PASS'
              -Dsonar.pullrequest.key=$BITBUCKET_PR_ID
              -Dsonar.pullrequest.base=$BITBUCKET_PR_DESTINATION_BRANCH
              -Dsonar.pullrequest.branch=$BITBUCKET_BRANCH

definitions:
  caches:
    sonarcloud: ~/.sonar/cache