from voltron.environments.constants.base.bet_finder import BetFinder


class LadbrokesBetFinder(BetFinder):
    RESET_FILTERS = 'Reset Filters'
    BF_HEADER_MESSAGE = 'Create your search below'
    BF_HEADER_TEXT_LADBROKES = 'Use the below filters to find the bet that suits you best. ' \
                               'Save your selections so you can quickly browse your runners in the future.'

    YOUR_TEAMS_INFO = 'Your Teams' + '\n' + BetFinder.SELECT_CRITERIA_FOR_TEAMS_TEXT
    THE_OPPOSITION_INFO = 'The Opposition' + '\n' + 'Select criteria for the teams you wish to bet against.'

    FB_BET_FILTER_PLAYING_AT_TEXT = BetFinder.FB_BET_FILTER_PLAYING_AT_TEXT.upper()
    FB_BET_FILTER_HOME = BetFinder.FB_BET_FILTER_HOME.title()
    FB_BET_FILTER_AWAY = BetFinder.FB_BET_FILTER_AWAY.title()
    FB_BET_FILTER_LAST_GAME_TEXT = BetFinder.FB_BET_FILTER_LAST_GAME_TEXT.upper()
    FB_BET_FILTER_WIN = BetFinder.FB_BET_FILTER_WIN.title()
    FB_BET_FILTER_DRAW = BetFinder.FB_BET_FILTER_DRAW.title()
    FB_BET_FILTER_LOSE = BetFinder.FB_BET_FILTER_LOSE.title()
    FB_BET_FILTER_LAST_GAMES_POINTS_TOTAL_TEXT = BetFinder.FB_BET_FILTER_LAST_GAMES_POINTS_TOTAL_TEXT.upper()
    FB_BET_FILTER_ZERO_SIX_POINTS = BetFinder.FB_BET_FILTER_ZERO_SIX_POINTS.title()
    FB_BET_FILTER_SEVEN_TWELVE_POINTS = BetFinder.FB_BET_FILTER_SEVEN_TWELVE_POINTS.title()
    FB_BET_FILTER_THIRTEEN_EIGHTEEN_POINTS = BetFinder.FB_BET_FILTER_THIRTEEN_EIGHTEEN_POINTS.title()
    FB_BET_FILTER_KEY_TRENDS_TEXT = BetFinder.FB_BET_FILTER_KEY_TRENDS_TEXT.upper()
    FB_BET_FILTER_HIGH_SCORING = BetFinder.FB_BET_FILTER_HIGH_SCORING.title()
    FB_BET_FILTER_MEAN_DEFENCE = BetFinder.FB_BET_FILTER_MEAN_DEFENCE.title()
    FB_BET_FILTER_CLEAN_SHEET_LAST_GAME = BetFinder.FB_BET_FILTER_CLEAN_SHEET_LAST_GAME.title()
    FB_BET_FILTER_LEAGUE_POSITIONS_TEXT = BetFinder.FB_BET_FILTER_LEAGUE_POSITIONS_TEXT.upper()
    FB_BET_FILTER_TOP_HALF = BetFinder.FB_BET_FILTER_TOP_HALF.title()
    FB_BET_FILTER_BOTTOM_HALF = BetFinder.FB_BET_FILTER_BOTTOM_HALF.title()
    FB_BET_FILTER_ABOVE_OPPOSITION = BetFinder.FB_BET_FILTER_ABOVE_OPPOSITION.title()
    FB_BET_FILTER_ODDS_TEXT = BetFinder.FB_BET_FILTER_ODDS_TEXT.upper()
    FB_BET_FILTER_FAVOURITE = BetFinder.FB_BET_FILTER_FAVOURITE.title()
    FB_BET_FILTER_OUTSIDER = BetFinder.FB_BET_FILTER_OUTSIDER.title()

    FB_BET_FILTER_LAST_GAME = BetFinder.FB_BET_FILTER_LAST_GAME.upper()
    FB_BET_FILTER_OPPOSITION_WIN = BetFinder.FB_BET_FILTER_OPPOSITION_WIN.title()
    FB_BET_FILTER_OPPOSITION_DRAW = BetFinder.FB_BET_FILTER_OPPOSITION_DRAW.title()
    FB_BET_FILTER_OPPOSITION_LOSE = BetFinder.FB_BET_FILTER_OPPOSITION_LOSE.title()
    FB_BET_FILTER_OPPOSITION_LAST_GAMES_POINTS_TOTAL_TEXT = BetFinder.FB_BET_FILTER_OPPOSITION_LAST_GAMES_POINTS_TOTAL_TEXT.upper()
    FB_BET_FILTER_OPPOSITION_ZERO_SIX_POINTS = BetFinder.FB_BET_FILTER_OPPOSITION_ZERO_SIX_POINTS.title()
    FB_BET_FILTER_OPPOSITION_SEVEN_TWELVE_POINTS = BetFinder.FB_BET_FILTER_OPPOSITION_SEVEN_TWELVE_POINTS.title()
    FB_BET_FILTER_OPPOSITION_THIRTEEN_EIGHTEEN_POINTS = BetFinder.FB_BET_FILTER_OPPOSITION_THIRTEEN_EIGHTEEN_POINTS.title()
    FB_BET_FILTER_OPPOSITION_KEY_TRENDS_TEXT = BetFinder.FB_BET_FILTER_OPPOSITION_KEY_TRENDS_TEXT.upper()
    FB_BET_FILTER_OPPOSITION_HIGH_SCORING = BetFinder.FB_BET_FILTER_OPPOSITION_HIGH_SCORING.title()
    FB_BET_FILTER_OPPOSITION_LEAKY_DEFENCE = BetFinder.FB_BET_FILTER_OPPOSITION_LEAKY_DEFENCE.title()
    FB_BET_FILTER_OPPOSITION_CONCEDED_LAST_GAMES = BetFinder.FB_BET_FILTER_OPPOSITION_CONCEDED_LAST_GAMES.title()
    FB_BET_FILTER_OPPOSITION_LEAGUE_POSITIONS_TEXT = BetFinder.FB_BET_FILTER_OPPOSITION_LEAGUE_POSITIONS_TEXT.upper()
    FB_BET_FILTER_OPPOSITION_TOP_HALF = BetFinder.FB_BET_FILTER_OPPOSITION_TOP_HALF.title()
    FB_BET_FILTER_OPPOSITION_BOTTOM_HALF = BetFinder.FB_BET_FILTER_OPPOSITION_BOTTOM_HALF.title()
    FB_BET_FILTER_OPPOSITION_BELOW_OPPOSITION = BetFinder.FB_BET_FILTER_OPPOSITION_BELOW_OPPOSITION.title()

    EXPECTED_EXPECTED_LIST_OF_YOUR_TEAMS_CATEGORIES = \
        [FB_BET_FILTER_PLAYING_AT_TEXT, FB_BET_FILTER_HOME, FB_BET_FILTER_AWAY, FB_BET_FILTER_LAST_GAME_TEXT,
         FB_BET_FILTER_WIN, FB_BET_FILTER_DRAW, FB_BET_FILTER_LOSE, FB_BET_FILTER_LAST_GAMES_POINTS_TOTAL_TEXT,
         FB_BET_FILTER_ZERO_SIX_POINTS, FB_BET_FILTER_SEVEN_TWELVE_POINTS, FB_BET_FILTER_THIRTEEN_EIGHTEEN_POINTS,
         FB_BET_FILTER_KEY_TRENDS_TEXT, FB_BET_FILTER_HIGH_SCORING, FB_BET_FILTER_MEAN_DEFENCE,
         FB_BET_FILTER_CLEAN_SHEET_LAST_GAME, FB_BET_FILTER_LEAGUE_POSITIONS_TEXT, FB_BET_FILTER_TOP_HALF,
         FB_BET_FILTER_BOTTOM_HALF, FB_BET_FILTER_ABOVE_OPPOSITION, FB_BET_FILTER_ODDS_TEXT,
         FB_BET_FILTER_FAVOURITE, FB_BET_FILTER_OUTSIDER]

    EXPECTED_LIST_OF_OPPOSITION_CATEGORIES = \
        [FB_BET_FILTER_LAST_GAME, FB_BET_FILTER_OPPOSITION_WIN, FB_BET_FILTER_OPPOSITION_DRAW,
         FB_BET_FILTER_OPPOSITION_LOSE,
         FB_BET_FILTER_OPPOSITION_LAST_GAMES_POINTS_TOTAL_TEXT, FB_BET_FILTER_OPPOSITION_ZERO_SIX_POINTS,
         FB_BET_FILTER_OPPOSITION_SEVEN_TWELVE_POINTS, FB_BET_FILTER_OPPOSITION_THIRTEEN_EIGHTEEN_POINTS,
         FB_BET_FILTER_OPPOSITION_KEY_TRENDS_TEXT, FB_BET_FILTER_OPPOSITION_HIGH_SCORING,
         FB_BET_FILTER_OPPOSITION_LEAKY_DEFENCE, FB_BET_FILTER_OPPOSITION_CONCEDED_LAST_GAMES,
         FB_BET_FILTER_OPPOSITION_LEAGUE_POSITIONS_TEXT, FB_BET_FILTER_OPPOSITION_TOP_HALF,
         FB_BET_FILTER_OPPOSITION_BOTTOM_HALF, FB_BET_FILTER_OPPOSITION_BELOW_OPPOSITION]

    BF_HEADER_TITLE = 'Bet Filter'
    BF_HEADER_TEXT = 'Use the below filters to find the bet that suits you best. ' \
                     'Save your selections so you can quickly browse your runners in future.'
    BF_HEADER_MESSAGE_HORSERACING = 'Create your search below:'
    NO_SELECTION = 'No selections found'
    ODDS_0 = BetFinder.ODDS_0.upper()
    ODDS_1 = BetFinder.ODDS_1.upper()
    ODDS_4 = BetFinder.ODDS_4.upper()
    ODDS_8 = BetFinder.ODDS_8.upper()
    ODDS_16 = BetFinder.ODDS_16.upper()
    ODDS_32 = BetFinder.ODDS_32.upper()
    ODDS_LIST = [ODDS_0, ODDS_1, ODDS_4, ODDS_8, ODDS_16, ODDS_32]
    ALL_MEETINGS = BetFinder.ALL_MEETINGS.upper()
