from voltron.environments.constants.base.racing import Racing


class LadbrokesRacing(Racing):
    """
    src/platforms/ladbrokesMobile/lazy-modules/locale/translations/en-US/lang.ts
    """
    RACING_POST_STAR_RATING = 'Racing Post STAR RATING'.upper()
    RACING_POST_TIPS = 'Racing Post Tips'.upper()
    INTERNATIONAL_TOTE_TITLE = 'International Tote'
    EXTRA_PLACE_TITLE = 'Extra Place Offers'.upper()
    MOST_TIPPED = 'Most Tipped'.upper()

    RACING_FEATURED_TAB_NAME = 'FEATURED'
    RACING_HIGHLIGHTS_TAB_NAME = 'HIGHLIGHTS'
    RACING_DEFAULT_TAB_NAME = 'MEETINGS'
    RACING_FUTURE_TAB_NAME = 'FUTURE'
    RACING_NEXT_RACES_NAME = 'NEXT RACES'
    RACING_SPECIALS_TAB_NAME = 'SPECIALS'
    RACING_YOURCALL_TAB_NAME = 'YOURCALL'
    RACING_TAB_NAMES = [RACING_DEFAULT_TAB_NAME, RACING_NEXT_RACES_NAME, RACING_FUTURE_TAB_NAME,
                        RACING_SPECIALS_TAB_NAME]
    RACING_ANTEPOST_SWITCHERS = ['FLAT', 'NATIONAL HUNT', 'INTERNATIONAL']
    UK_AND_IRE_TYPE_NAME = 'UK AND IRISH RACES'
    UK_TYPE_NAME = 'UK RACES'
    INTERNATIONAL_TYPE_NAME = 'INTERNATIONAL RACES'
    INTERNATIONAL_TOTE_NAME = 'INTERNATIONAL TOTE CAROUSEL'
    YC_SPECIALS = 'YOURCALL SPECIALS'
    LEGENDS_TYPE_NAME = 'LADBROKES LEGENDS'
    VIRTUAL_TYPE_NAME = 'VIRTUAL RACE CAROUSEL'
    AUSTRALIA_TYPE_NAME = 'AUSTRALIA RACES'
    SOUTH_AFRICA_TYPE_NAME = 'SOUTH AFRICA RACES'
    FRANCE_TYPE_NAME = 'FRANCE RACES'
    INDIA_TYPE_NAME = 'INDIA RACES'
    UAE_TYPE_NAME = 'UAE RACES'
    CHILE_TYPE_NAME = 'CHILE RACES'
    USA_TYPE_NAME = 'USA RACES'
    JOCKEY_TEXT = 'J: {jockey}'
    TRAINER_TEXT = 'T: {trainer}'
    JOCKEY_TRAINER_TEXT = f'{JOCKEY_TEXT} / {TRAINER_TEXT}'

    PRICE_SORTING_OPTION_SELECTED = 'PRICE'
    CARD_SORTING_OPTION_SELECTED = 'RACECARD'

    HORSE_RACING_TAB_NAME = 'HORSES'  # for some cases used property horse_racing_title from BaseRacing class
    OFFERS_AND_FEATURED_RACES = 'ENHANCED RACES'

    GREYHOUND_TODAY_TAB = 'TODAY'
    GREYHOUND_TOMORROW_TAB = 'TOMORROW'
    GREYHOUND_TAB_NAMES = [RACING_NEXT_RACES_NAME, GREYHOUND_TODAY_TAB, GREYHOUND_TOMORROW_TAB, RACING_FUTURE_TAB_NAME]
    uk_filter_name = "UK&IRE"

    FONT_FAMILY = 'Roboto'
