import pytest
from tests.base_test import vtest
from tests.Common import Common


@pytest.mark.tst2
@pytest.mark.stg2
# @pytest.mark.prod
# @pytest.mark.hl
@pytest.mark.medium
@pytest.mark.other
@vtest
class Test_C64594484_Verify_the_existing_functionality_of_the_Manual_SEO_page(Common):
    """
    TR_ID: C64594484
    NAME: Verify the existing functionality of the Manual SEO page.
    DESCRIPTION: Verify that Meta tittle and description creation functionality in the Manual SEO section in CMS.
    PRECONDITIONS: * Chose a competition page for which no template is set in manual SEO section.
    PRECONDITIONS: * Note: applicable only to mobile web.
    """
    keep_browser_open = True

    def test_001_log_into_cms_and_navigate_to_seo_gt_manual_page(self):
        """
        DESCRIPTION: Log into CMS and navigate to SEO &gt; Manual page.
        EXPECTED: Log in successful.
        """
        pass

    def test_002_create_a_competition_page_in_cms_gt_seo_gt_manual_section_with_meta_tittle_and_description_for_any_competition_which_is_not_preset(self):
        """
        DESCRIPTION: Create a competition page in CMS &gt; SEO &gt; Manual section with Meta tittle and description for any competition which is not preset.
        EXPECTED: SEO page created successfully.
        """
        pass

    def test_003_navigate_to_the_competition_for_which_tags_are_manually_set_in_the_front_end(self):
        """
        DESCRIPTION: Navigate to the Competition for which tags are manually set, in the front end.
        EXPECTED: Landed on to the competition page.
        """
        pass

    def test_004_hover_the_cursor_over_the_competition_browser_tabindexphpattachmentsget5b86b696_dfe9_42ab_9e36_a90f5169befe(self):
        """
        DESCRIPTION: Hover the cursor over the competition browser tab.
        DESCRIPTION: ![](index.php?/attachments/get/5b86b696-dfe9-42ab-9e36-a90f5169befe)
        EXPECTED: Manual Meta tittle is visible.
        """
        pass

    def test_005_check_for_the_meta_tittle_and_description_in_inspection_window_gt_elements_tab_under_header_head_callindexphpattachmentsgetdc153057_6e57_4c5e_b9cd_e8de636fb81f(self):
        """
        DESCRIPTION: Check for the meta tittle and description in Inspection Window &gt; Elements tab under header 'head' call.
        DESCRIPTION: ![](index.php?/attachments/get/dc153057-6e57-4c5e-b9cd-e8de636fb81f)
        EXPECTED: Manually given meta tittle and descriptions are displayed.
        """
        pass

    def test_006_update_the_existing_manual_seo_page_for_a_competition_in_cms(self):
        """
        DESCRIPTION: Update the existing Manual SEO page for a competition in CMS.
        EXPECTED: SEO page updated successfully.
        """
        pass

    def test_007_navigate_to_the_competition_for_which_tags_are_updated_in_the_front_end_hover_the_cursor_over_the_browser_tabindexphpattachmentsget157d5696_7fc6_41ad_b390_b21b1141f520(self):
        """
        DESCRIPTION: Navigate to the Competition for which tags are updated, in the front end. Hover the cursor over the browser tab.
        DESCRIPTION: ![](index.php?/attachments/get/157d5696-7fc6-41ad-b390-b21b1141f520)
        EXPECTED: Landed on to the competition page. The updated Meta tittle is displayed.
        """
        pass

    def test_008_check_for_the_meta_tittle_and_description_in_inspection_window_gt_elements_tab_under_header_head_callindexphpattachmentsgetf2e96e05_e83a_44ff_a5a5_fa1ec8f61e50(self):
        """
        DESCRIPTION: Check for the meta tittle and description in Inspection Window &gt; Elements tab under header 'head' call.
        DESCRIPTION: ![](index.php?/attachments/get/f2e96e05-e83a-44ff-a5a5-fa1ec8f61e50)
        EXPECTED: The updated meta tittle and descriptions are displayed.
        """
        pass

    def test_009_delete_or_remove_the_previously_created_competition_seo_page(self):
        """
        DESCRIPTION: Delete or remove the previously created competition SEO page.
        EXPECTED: Page successfully deleted from the CMS &gt; SEO &gt; Manual section.
        """
        pass

    def test_010_navigate_to_the_removed_competition_in_the_front_end(self):
        """
        DESCRIPTION: Navigate to the removed Competition in the front end.
        EXPECTED: Default or automated tags are displayed.
        """
        pass

    def test_011_hover_the_cursor_over_competition_browser_tab_for_which_manual_seo_page_is_removedindexphpattachmentsget6360d107_ec42_40c4_baec_4c48795e39e7(self):
        """
        DESCRIPTION: Hover the cursor over competition browser tab for which Manual SEO page is removed.
        DESCRIPTION: ![](index.php?/attachments/get/6360d107-ec42-40c4-baec-4c48795e39e7)
        EXPECTED: The default or autogenerated meta tittle is displayed.
        """
        pass

    def test_012_check_for_the_meta_tittle_and_description_for_the_removed_manual_seo_competition_page_in_inspection_window_gt_elements_tab_under_header_head_callindexphpattachmentsget5ed10ed3_87fb_4d77_a67a_57ad9320fc65(self):
        """
        DESCRIPTION: Check for the meta tittle and description for the removed manual SEO competition page in Inspection Window &gt; Elements tab under header 'head' call.
        DESCRIPTION: ![](index.php?/attachments/get/5ed10ed3-87fb-4d77-a67a-57ad9320fc65)
        EXPECTED: The default or autogenerated meta tags are displayed.
        """
        pass

    def test_013_set_the_manual_seo_page_for_a_competition_to_inactive(self):
        """
        DESCRIPTION: Set the Manual SEO page for a competition to inactive.
        EXPECTED: Manual SEO page is made inactive successfully.
        """
        pass

    def test_014_navigate_to_the_competition_page_in_the_front_end_for_which_seo_page_is_set_to_inactive_hover_the_cursor_over_the_competition_pageindexphpattachmentsgetb0134228_cfc5_44ec_a926_466bdac7d8be(self):
        """
        DESCRIPTION: Navigate to the Competition page in the front end for which SEO page is set to inactive. Hover the cursor over the competition page.
        DESCRIPTION: ![](index.php?/attachments/get/b0134228-cfc5-44ec-a926-466bdac7d8be)
        EXPECTED: Default or automated tittle is displayed.
        """
        pass

    def test_015_check_for_the_meta_tittle_and_description_for_the_inactive_competition_for_which_manual_seo_page_is_inactive_in_the_inspection_window_gt_elements_tab_under_header_head_callindexphpattachmentsget3eb6bf6f_2f5a_46d6_8913_6a476a9d6e34(self):
        """
        DESCRIPTION: Check for the meta tittle and description for the inactive competition for which manual SEO page is inactive in the Inspection Window &gt; Elements tab under header 'head' call.
        DESCRIPTION: ![](index.php?/attachments/get/3eb6bf6f-2f5a-46d6-8913-6a476a9d6e34)
        EXPECTED: The default or autogenerated meta tags are displayed.
        """
        pass
