export const eventMock = {
  id: 11818323,
  name: 'Chepstow',
  eventStatusCode: 'A',
  isActive: 'true',
  displayOrder: 960,
  eventSortCode: 'MTCH',
  startTime: 1540915200000,
  racingPostVerdict: {} as any,
  rawIsOffCode: 'N',
  classId: '223',
  typeId: '1909',
  sportId: '21',
  categoryId: '21',
  categoryCode: 'HORSE_RACING',
  categoryName: 'Horse Racing',
  categoryDisplayOrder: '-9971',
  className: 'Horse Racing - Live',
  classDisplayOrder: -9999,
  classSortCode: 'HR',
  classFlagCodes: 'UF,LI,',
  typeName: 'ChepstowTN',
  typeDisplayOrder: -31790,
  typeFlagCodes: 'UK,QL,AVA,',
  isOpenEvent: 'true',
  isNext24HourEvent: 'true',
  isLiveNowOrFutureEvent: 'true',
  isAvailable: 'true',
  liveServChannels: 'test',
  liveServChildrenChannels: 'test',
  mediaTypeCodes: 'VST,',
  drilldownTagNames: 'test',
  cashoutAvail: 'Y',
  responseCreationTime: '2018-10-30T11:56:33.201Z',
  externalKeys: {
    OBEvLinkTote: 11821716
  },
  localTime: '16:00',
  originalName: '16:00 Chepstow',
  isUS: false,
  markets: [{
    id: '275108045',
    eventId: '11818323',
    templateMarketId: '135693',
    templateMarketName: 'Win Only',
    collectionIds: '4335,',
    marketMeaningMajorCode: '-',
    marketMeaningMinorCode: 'XW',
    name: 'Win Only',
    isLpAvailable: 'true',
    displayOrder: 10,
    marketStatusCode: 'A',
    priceTypeCodes: 'LP,',
    isAvailable: 'true',
    maxAccumulators: '25',
    minAccumulators: '1',
    cashoutAvail: 'N',
    responseCreationTime: '2018-10-30T11:56:33.201Z',
    outcomes: [{
      id: '882480296',
      marketId: '275108045',
      name: 'Gaelic Flow',
      outcomeMeaningMajorCode: 'XW',
      runnerNumber: '15',
      displayOrder: 15,
      outcomeStatusCode: 'A',
      isActive: 'true',
      isAvailable: 'true',
      cashoutAvail: 'N',
      prices: [
        {
          id: '210',
          priceType: 'LP',
          priceNum: '4',
          priceDen: '1',
          priceDec: 5,
          isActive: 'true',
          displayOrder: '1',
          isDisplayed: true,
          liveShowTimer: {}
        }
      ],
      racingFormOutcome: {
        id: '107',
        refRecordType: 'outcome',
        refRecordId: '882480278',
        runnerNumber: '15',
        runnerId: '28639832',
        age: '7',
        trainer: 'C Down',
        daysSinceRun: '10',
        jockey: 'Bryony Frost',
        owner: 'The Jack High Racing Partnership',
        silkName: '203596.gif',
        formGuide: '494521',
        overview: 'test overview',
        weight: 'Pounds, 8  ',
        officialRating: '82',
        formProviderRating: '109',
        runnerStatusCode: 'S',
        colour: 'Chestnut',
        genderCode: 'gelding',
        going: 'G',
        responseCreationTime: '2018-10-30T11:56:33.201Z'
      },
      isValidRunnerNumber: false,
      isFavourite: false
    }]
  }],
  correctedDay: 'racing.dayTuesday',
  eventIsLive: false,
  liveEventOrder: 1,
  racingFormEvent: {
    id: '3',
    refRecordType: 'event',
    refRecordId: '11818323',
    raceNumber: '6',
    title: 'myracing.com For Daily Tips Handicap Hurdle (0-100) (5) 3yo+',
    overview: 'test overview',
    going: 'G',
    class: '5',
    prize: '3119.04',
    distance: ' 2m 3f 100y',
    isHandicap: 'true',
    responseCreationTime: '2018-10-30T11:56:33.201Z'
  },
  liveStreamAvailable: true,
  streamProviders: {
    RacingUK: false,
    Perform: false,
    AtTheRaces: true,
    IMG: false,
    RPGTV: false,
    iGameMedia: false
  },
  liveSimAvailable: false,
  isUKorIRE: true,
  uiClass: 'Class 5',
  sortedMarkets: [
    {
      id: '275108045',
      eventId: '11818323',
      templateMarketId: '135693',
      templateMarketName: 'Win Only',
      collectionIds: '4335,',
      collectionNames: 'Win Only,',
      marketMeaningMajorCode: '-',
      marketMeaningMinorCode: 'XW',
      name: 'Win Only',
      isLpAvailable: 'true',
      displayOrder: 10,
      marketStatusCode: 'A',
      isActive: 'true',
      siteChannels: 'P,Q,C,I,M,',
      liveServChannels: 'sEVMKT0275108045,',
      liveServChildrenChannels: 'SEVMKT0275108045,',
      priceTypeCodes: 'LP,',
      isAvailable: 'true',
      maxAccumulators: '25',
      minAccumulators: '1',
      cashoutAvail: 'N',
      outcomes: [
        {
          id: '882480296',
          marketId: '275108045',
          name: 'Gaelic Flow',
          outcomeMeaningMajorCode: 'XW',
          runnerNumber: '15',
          displayOrder: 15,
          outcomeStatusCode: 'A',
          isActive: 'true',
          isAvailable: 'true',
          cashoutAvail: 'N',
          prices: [
            {
              id: '210',
              priceType: 'LP',
              priceNum: '4',
              priceDen: '1',
              priceDec: 5,
              isActive: 'true',
              displayOrder: '1',
              isDisplayed: true,
              liveShowTimer: {}
            }
          ],
          racingFormOutcome: {
            id: '107',
            refRecordType: 'outcome',
            refRecordId: '882480278',
            runnerNumber: '15',
            runnerId: '28639832',
            age: '7',
            trainer: 'C Down',
            daysSinceRun: '10',
            jockey: 'Bryony Frost',
            owner: 'The Jack High Racing Partnership',
            silkName: '203596.gif',
            formGuide: '494521',
            overview: 'test overview',
            weight: 'Pounds,148',
            officialRating: '82',
            formProviderRating: '109',
            runnerStatusCode: 'S',
            colour: 'Chestnut',
            genderCode: 'gelding',
            going: 'G',
            responseCreationTime: '2018-10-30T11:56:33.201Z'
          },
          isValidRunnerNumber: false,
          isFavourite: false
        }
      ],
      customOrder: 1,
      terms: 'Each Way: undefined/undefined odds - places ',
      label: 'Win Only',
      path: 'win-only'
    }
  ],
  filteredTime: 'Tuesday 30th October'
} as any;

export const EDP_MARKETS = [
  {
    'id': '5e6f2f85c9e77c000118b4cc',
    'createdBy': '54905d04a49acf605d645271',
    'createdByUserName': null,
    'updatedBy': '54905d04a49acf605d645271',
    'updatedByUserName': null,
    'createdAt': '2020-03-16T07:49:25.414Z',
    'updatedAt': '2020-03-16T07:49:54.220Z',
    'name': 'Win or Each Way',
    'lang': '',
    'brand': 'ladbrokes',
    'description': 'S1: Pick the finishing order of the first two runnersPick the finishing order of the first two runners',
    'isHR': true,
    'isGH': true,
    'isNew': false
  },
  {
    'id': '5e6f2f85c9e77c000118b4cd',
    'createdBy': '54905d04a49acf605d645271',
    'createdByUserName': null,
    'updatedBy': '54905d04a49acf605d645271',
    'updatedByUserName': null,
    'createdAt': '2020-03-16T07:49:25.414Z',
    'updatedAt': '2020-03-16T07:49:54.220Z',
    'name': 'Tricast',
    'lang': '',
    'brand': 'ladbrokes',
    'description': 'S2: Pick the finishing order of the first two runnersPick the finishing order of the first two runners',
    'isHR': false,
    'isGH': true,
    'isNew': true
  },
  {
    'id': '5e6f2f85c9e77c000118b4ce',
    'createdBy': '54905d04a49acf605d645271',
    'createdByUserName': null,
    'updatedBy': '54905d04a49acf605d645271',
    'updatedByUserName': null,
    'createdAt': '2020-03-16T07:49:25.414Z',
    'updatedAt': '2020-03-16T07:49:54.220Z',
    'name': 'Win Only',
    'lang': '',
    'brand': 'ladbrokes',
    'description': 'S3: Pick the finishing order of the first two runnersPick the finishing order of the first two runners',
    'isHR': true,
    'isGH': false,
    'isNew': false
  },
  {
    'id': '5e6f2f85c9e77c000118b4cf',
    'createdBy': '54905d04a49acf605d645271',
    'createdByUserName': null,
    'updatedBy': '54905d04a49acf605d645271',
    'updatedByUserName': null,
    'createdAt': '2020-03-16T07:49:25.414Z',
    'updatedAt': '2020-03-16T07:49:54.220Z',
    'name': 'Forecast',
    'lang': '',
    'brand': 'ladbrokes',
    'description': '',
    'isHR': undefined,
    'isGH': undefined,
    'isNew': undefined
  },
  {
    'id': '5e6f2f85c9e77c000118b4cf',
    'createdBy': '54905d04a49acf605d645271',
    'createdByUserName': null,
    'updatedBy': '54905d04a49acf605d645271',
    'updatedByUserName': null,
    'createdAt': '2020-03-16T07:49:25.414Z',
    'updatedAt': '2020-03-16T07:49:54.220Z',
    'name': 'Insurance - Place 2',
    'lang': '',
    'brand': 'ladbrokes',
    'description': 'S5: Pick the finishing order of the first two runnersPick the finishing order of the first two runners',
    'isHR': true,
    'isGH': false,
    'isNew': true
  },
  {
    'id': '5e6f2f85c9e77c000118b4cf',
    'createdBy': '54905d04a49acf605d645271',
    'createdByUserName': null,
    'updatedBy': '54905d04a49acf605d645271',
    'updatedByUserName': null,
    'createdAt': '2020-03-16T07:49:25.414Z',
    'updatedAt': '2020-03-16T07:49:54.220Z',
    'name': 'Top Finish',
    'lang': '',
    'brand': 'ladbrokes',
    'description': 'S7: Pick the finishing order of the first two runnersPick the finishing order of the first two runners',
    'isHR': true,
    'isGH': false,
    'isNew': true
  }
];

export const mockMarket = {
  cashoutAvail: '',
  correctPriceTypeCode: '',
  dispSortName: '',
  eachWayFactorNum: '',
  eachWayFactorDen: '',
  eachWayPlaces: '',
  id: '',
  isGpAvailable: false,
  isLpAvailable: false,
  isMarketBetInRun: false,
  isSpAvailable: false,
  liveServChannels: '',
  isEachWayAvailable: false,
  liveServChildrenChannels: '',
  marketsNames: '',
  marketStatusCode: '',
  name: 'testName',
  nextScore: 1,
  outcomes: [],
  periods: [],
  priceTypeCodes: '',
  terms: '',
  templateMarketId: 1,
  templateMarketName: '',
  viewType: '',
  label: '',
  isTopFinish: false,
  isToFinish: false,
  insuranceMarkets: false,
  isOther: false,
  isWO: false,
  header: ['1', '2', '3'],
  markets: [
    {
      id: '1'
    },
    {
      id: '2'
    },
    {
      id: '3'
    }
  ]
};
export const mockEvent = {
  cashoutAvail: '',
  categoryCode: '',
  categoryId: '',
  categoryName: '',
  comments: {
    teams: {},
  },
  displayOrder: 1,
  drilldownTagNames: '',
  eventIsLive: false,
  eventSortCode: '',
  eventStatusCode: '',
  groupedLimit: 1,
  id: 1,
  isStarted: false,
  isUS: false,
  liveServChannels: '',
  liveServChildrenChannels: '',
  liveStreamAvailable: false,
  markets: [mockMarket],
  marketsCount: 1,
  name: '',
  originalName: '',
  responseCreationTime: '',
  racingFormEvent: {
    class: ''
  },
  startTime: '',
  streamProviders: {
    ATR: false,
    IMG: false,
    Perform: false,
    RPGTV: false,
    RacingUK: false,
    iGameMedia: false
  },
  svgId: '',
  typeId: '',
  typeName: '',
  outcomeId: 1,
  sortedMarkets: [mockMarket]
};

export const horseRacingGATrackingMock = {
  categoryID: '21',
  event: "trackEvent",
  eventAction: "race card",
  eventCategory: "horse racing",
  eventID: 11818323,
  eventLabel: "show more",
  typeID: '1909'
}

export const horseRacingGATrackingMockwithshowless = {
  categoryID: '21',
  event: "trackEvent",
  eventAction: "race card",
  eventCategory: "horse racing",
  eventID: 11818323,
  eventLabel: "show less",
  typeID: '1909'
}

export const greyhoundsGATrackingMock = {
  categoryID: '21',
  event: "trackEvent",
  eventAction: "race card",
  eventCategory: "greyhounds",
  eventID: 11818323,
  eventLabel: "show more",
  typeID: '1909'
}

