application:
  allowedOrigins:
    - https://bm-tst1.coral.co.uk
    - https://bm-tst1.coral.co.uk:4200
    - http://bm-tst1.coral.co.uk
    - http://bm-tst1.coral.co.uk:4200
    - http://cms-localhost.coral.co.uk:4200
    - https://cms-localhost.coral.co.uk:4200
    - https://coral-cms-dev0.symphony-solutions.eu
    - https://coral-cms-dev1.symphony-solutions.eu
    - https://coral-cms-tst2.symphony-solutions.eu
    - https://coral-cms-stg2.symphony-solutions.eu
    - https://coral-cms-hl.symphony-solutions.eu
    - https://coral-cms.symphony-solutions.eu
    - https://coral-cms-api-dev.symphony-solutions.eu
    - https://invictus.coral.co.uk
    - https://oxynative.coral.co.uk
    - https://bet-hl.coral.co.uk
    - https://new-invictus.coral.co.uk
    - https://connect-invictus.coral.co.uk
    - https://test-invictus.coral.co.uk
    - https://mustang-invictus.coral.co.uk
    - https://inplay-invictus.coral.co.uk
    - https://muckers-invictus.coral.co.uk
    - https://mustang-new-invictus.coral.co.uk
    - https://td-invictus.coral.co.uk
    - https://native-invictus.coral.co.uk
    - https://consul.service.local.coral.co.uk
    - https://korali-invictus.coral.co.uk
    - https://release-invictus.coral.co.uk
    - https://express.coral.co.uk
    - https://bet-stg2.coral.co.uk
    - https://bet-tst1.coral.co.uk
    - https://bet-tst2.coral.co.uk
    - https://bet-tst3.coral.co.uk
    - https://bet-tst4.coral.co.uk
    - https://bet.coral.co.uk
    - https://express-invictus.coral.co.uk
    - https://phoenix-invictus.coral.co.uk
    - https://korali2-invictus.coral.co.uk
    - https://muckers2-invictus.coral.co.uk
    - https://connect-app.coral.co.uk
    - https://connect-app-tst1.coral.co.uk
    - https://connect-app-tst2.coral.co.uk
    - https://connect-app-stg2.coral.co.uk
    - https://fantom-invictus.coral.co.uk
    - https://fantom-invictus.coral.co.uk
    - https://desktop-invictus.coral.co.uk
    - https://muckers3-invictus.coral.co.uk
    - https://avengers-invictus.coral.co.uk
    - https://affly-invictus.coral.co.uk
    - https://desktop-release-invictus.coral.co.uk
    - https://dev.coralbettracker.co.uk
    - https://tst1.coralbettracker.co.uk
    - https://tst2.coralbettracker.co.uk
    - https://stg.coralbettracker.co.uk
    - https://coralbettracker.co.uk
    - https://dev.coralbettracker.co.uk:3000
    - https://sports.coral.co.uk
    - https://sports-hl.coral.co.uk
    - https://sports-stg2.coral.co.uk
    - https://sports-tst1.coral.co.uk
    - https://sports-tst2.coral.co.uk
    - https://sports-tst3.coral.co.uk
    - https://sports-tst4.coral.co.uk
    - https://naughty-invictus.coral.co.uk
    - https://odds-invictus.coral.co.uk
    - https://hollow-invictus.coral.co.uk
    - https://graceful-invictus.coral.co.uk
    - https://grim-invictus.coral.co.uk
    - https://brave-invictus.coral.co.uk
    - https://silent-invictus.coral.co.uk
    - https://clumsy-invictus.coral.co.uk
    - https://amazing-invictus.coral.co.uk
    - https://cherry-excalibur.coral.co.uk
    - https://raspberry-excalibur.coral.co.uk
    - https://excalibur.coral.co.uk
    - https://exoticfalcon-invictus.coral.co.uk
    - https://gentleviper-invictus.coral.co.uk
    - https://hellishlion-invictus.coral.co.uk
    - https://sparklingcat-invictus.coral.co.uk
    - https://talentedfish-invictus.coral.co.uk
