import { Fanzone, ClubPromo } from '@root/app/client/private/models/fanzone.model';

export const FANZONE_MOCK_DATA: Fanzone[] = [
    {
        id: '2',
        brand: '',
        active: true,
        launchBannerUrl: 'https://scmedia.itsfogo.com/$-$/1a8eff3bab3e46cd96e1acc5d0ac5fdf.jpg',
        name: 'Everton',
        teamId: '22456',
        openBetID: '986553',
        fanzoneBanner: 'https://scmedia.itsfogo.com/$-$/1a8eff3bab3e46cd96e1acc5d0ac5fdf.jpg',
        assetManagementLink: 'Liverpool',
        primaryCompetitionId: '234,345,887',
        secondaryCompetitionId: '234,345,887',
        clubIds: '990,991,992',
        location: 'Goodison Park, Liverpool',
        fanzoneConfiguration: {
            showNowNext: true,
            showStats: true,
            showClubs: true,
            sportsRibbon: true,
            atozMenu: true,
            homePage: true,
            footballHome: true,
            launchBannerUrlDesktop: 'https://scmedia.itsfogo.com/$-$/1a8eff3bab3e46cd96e1acc5d0ac5fdf.jpg',
            fanzoneBannerDesktop: 'https://scmedia.itsfogo.com/$-$/1a8eff3bab3e46cd96e1acc5d0ac5fdf.jpg',
        },
        createdBy: '5645b8a220bd9e0800afdc57',
        createdByUserName: 'ozoneqa@ivycomptech.com',
        updatedBy: '5645b8a220bd9e0800afdc57',
        updatedByUserName: 'ozoneqa@ivycomptech.com',
        createdAt: '2021-10-01T06:34:11.559Z',
        updatedAt: '2021-10-01T06:34:56.744Z',
    },
    {
        id: '1',
        brand: '',
        active: true,
        launchBannerUrl: 'https://scmedia.itsfogo.com/$-$/1a8eff3bab3e46cd96e1acc5d0ac5fdf.jpg',
        name: 'Everton',
        teamId: '22456',
        openBetID: '986553',
        fanzoneBanner: 'https://scmedia.itsfogo.com/$-$/1a8eff3bab3e46cd96e1acc5d0ac5fdf.jpg',
        assetManagementLink: 'Liverpool',
        primaryCompetitionId: '234,345,887',
        secondaryCompetitionId: '234,345,887',
        clubIds: '990,991,992',
        location: 'Goodison Park, Liverpool',
        fanzoneConfiguration: {
            showNowNext: true,
            showStats: true,
            showClubs: true,
            sportsRibbon: true,
            atozMenu: true,
            homePage: true,
            footballHome: true,
            launchBannerUrlDesktop: 'https://scmedia.itsfogo.com/$-$/1a8eff3bab3e46cd96e1acc5d0ac5fdf.jpg',
            fanzoneBannerDesktop: 'https://scmedia.itsfogo.com/$-$/1a8eff3bab3e46cd96e1acc5d0ac5fdf.jpg',
        },
        createdBy: '5645b8a220bd9e0800afdc57',
        createdByUserName: 'ozoneqa@ivycomptech.com',
        updatedBy: '5645b8a220bd9e0800afdc57',
        updatedByUserName: 'ozoneqa@ivycomptech.com',
        createdAt: '2021-10-01T06:34:11.559Z',
        updatedAt: '2021-10-01T06:34:56.744Z',
    }
];
export const FZ: Fanzone =
{
    id: '',
    brand: '',
    active: true,
    launchBannerUrl: 'https://scmedia.itsfogo.com/$-$/1a8eff3bab3e46cd96e1acc5d0ac5fdf.jpg',
    name: 'Everton',
    teamId: '22456',
    openBetID: '986553',
    fanzoneBanner: 'https://scmedia.itsfogo.com/$-$/1a8eff3bab3e46cd96e1acc5d0ac5fdf.jpg',
    assetManagementLink: 'Liverpool',
    primaryCompetitionId: '234,345,887',
    secondaryCompetitionId: '234,345,887',
    clubIds: '990,991,992',
    location: 'Goodison Park, Liverpool',
    fanzoneConfiguration: {
        showNowNext: true,
        showStats: true,
        showClubs: true,
        sportsRibbon: true,
        atozMenu: true,
        homePage: true,
        footballHome: true,
        launchBannerUrlDesktop: 'https://scmedia.itsfogo.com/$-$/1a8eff3bab3e46cd96e1acc5d0ac5fdf.jpg',
        fanzoneBannerDesktop: 'https://scmedia.itsfogo.com/$-$/1a8eff3bab3e46cd96e1acc5d0ac5fdf.jpg',
    },
    createdBy: '5645b8a220bd9e0800afdc57',
    createdByUserName: 'ozoneqa@ivycomptech.com',
    updatedBy: '5645b8a220bd9e0800afdc57',
    updatedByUserName: 'ozoneqa@ivycomptech.com',
    createdAt: '2021-10-01T06:34:11.559Z',
    updatedAt: '2021-10-01T06:34:56.744Z',
};
export const CLUB: ClubPromo = {
    id: '',
    brand: 'bma',
    active: true,
    title: '',
    bannerLink: '',
    description: '',
    validityPeriodStart: '',
    validityPeriodEnd: '',
    createdBy: '',
    createdByUserName: '',
    updatedBy: '',
    updatedByUserName: '',
    createdAt: '',
    updatedAt: '',
};
export const CLUB_UPDATED_DATE: ClubPromo = {
    id: '',
    brand: 'bma',
    active: true,
    title: '',
    bannerLink: '',
    description: '',
    validityPeriodStart: '10-10-2020',
    validityPeriodEnd: '12-10-2020',
    createdBy: '',
    createdByUserName: '',
    updatedBy: '',
    updatedByUserName: '',
    createdAt: '',
    updatedAt: '',
};
export const CLUB_UPDATED_DESC: ClubPromo = {
    id: '',
    brand: 'bma',
    active: true,
    title: '',
    bannerLink: '',
    description: 'updated desc',
    validityPeriodStart: '',
    validityPeriodEnd: '',
    createdBy: '',
    createdByUserName: '',
    updatedBy: '',
    updatedByUserName: '',
    createdAt: '',
    updatedAt: '',
};
export const FZPreferences = { id: '', brand: 'bma', createdBy: '', createdByUserName: '', updatedBy: '', updatedByUserName: '', createdAt: '', updatedAt: '', active: true, pcDescription: '', pcKeys: [{ name: '', key: '' }], ctaText: '', subscribeText: '', confirmText: '', confirmCTA: '', exitCTA: '', notificationPopupTitle: '', unsubscribeTitle: '', notificationDescriptionDesktop: '', unsubscribeDescription: '', pushPreferenceCentreTitle: '', optInCTA: '', noThanksCTA: '' }
export const FZPreferencesWithData = { id: '123', brand: 'bma', createdBy: '', createdByUserName: '', updatedBy: '', updatedByUserName: '', createdAt: '', updatedAt: '', active: true, pcDescription: 'pcDescription', pcKeys: [], ctaText: 'ok', subscribeText: 'test', confirmText: 'confirm', confirmCTA: 'confirm', exitCTA: 'exit', notificationPopupTitle: 'test', unsubscribeTitle: 'test', notificationDescriptionDesktop: 'test', unsubscribeDescription: 'test', pushPreferenceCentreTitle: 'test', optInCTA: 'test', noThanksCTA: 'test' }
export const FZPreferencesWithInvalidData = { id: '123', brand: 'bma', createdBy: '', createdByUserName: '', updatedBy: '', updatedByUserName: '', createdAt: '', updatedAt: '', active: true, pcDescription: '', pcKeys: [], ctaText: 'ok', subscribeText: 'test', confirmText: 'confirm', confirmCTA: 'confirm', exitCTA: 'exit', notificationPopupTitle: 'test', unsubscribeTitle: 'test', notificationDescriptionDesktop: 'test', unsubscribeDescription: 'test', pushPreferenceCentreTitle: 'test', optInCTA: 'test', noThanksCTA: 'test' }
export const FANZONE_CLUB_MOCK_DATA = {
    "id": "62b19f885314de5a97f2ce1d",
    "createdBy": "54905d04a49acf605d645271",
    "createdByUserName": "ozoneqa@ivycomptech.com",
    "updatedBy": "5645b8a220bd9e0800afdc57",
    "updatedByUserName": "ozoneqa@ivycomptech.com",
    "createdAt": "2022-06-21T10:38:00.886Z",
    "updatedAt": "2022-06-27T10:15:29.342Z",
    "pageName": null,
    "brand": "ladbrokes",
    "active": true,
    "validityPeriodStart": "2022-05-11T12:03:41.774Z",
    "validityPeriodEnd": "2022-08-20T12:03:41Z",
    "title": "PK Club Fanzone Promo",
    "bannerLink": "{5B93FBB1-DD9D-470A-A745-1413FDCB23A5}",
    "description": "<h3 style=\"text-align: center;\"><strong>This is another Test from PK</strong></h3>\n<p>This is anothet test club to handle all the scenarios like tables and headers and section</p>\n<p> </p>\n<p> </p>\n<p> </p>\n<p> </p>\n<p> </p>\n<div id=\"textarea\" contenteditable=\"true\">\n<p> Test DPB Button</p>\n</div>\n<p><button id=\"dynamicbtn-165710625\" class=\"btn dynamic-btn-style .btn\">165710625 - N/A</button></p>\n<p id=\"empty\"> </p>\n<p> </p>\n<div class=\"accordion-element-js\">\n<section class=\"page-container no-header is-expanded\"><header class=\"container-header sub-header\">\n<div class=\"left-side-element-js\"><span class=\"left-title-text\">TESTING PROMO</span></div>\n</header>\n<article class=\"container-content text-section\">\n<div class=\"container-inside-text\"> </div>\n</article>\n</section>\n</div>"
};

export const FANZONE_CLUB_LIST_MOCK_DATA = [
    {
        "id": "1",
        "createdBy": "54905d04a49acf605d645271",
        "createdByUserName": "ozoneqa@ivycomptech.com",
        "updatedBy": "5645b8a220bd9e0800afdc57",
        "updatedByUserName": "ozoneqa@ivycomptech.com",
        "createdAt": "2022-06-21T10:38:00.886Z",
        "updatedAt": "2022-06-27T10:15:29.342Z",
        "pageName": null,
        "brand": "ladbrokes",
        "active": true,
        "validityPeriodStart": "2022-05-11T12:03:41.774Z",
        "validityPeriodEnd": "2022-08-20T12:03:41Z",
        "title": "PK Club Fanzone Promo",
        "bannerLink": "{5B93FBB1-DD9D-470A-A745-1413FDCB23A5}",
        "description": "<h3 style=\"text-align: center;\"><strong>This is another Test from PK</strong></h3>\n<p>This is anothet test club to handle all the scenarios like tables and headers and section</p>\n<p> </p>\n<p> </p>\n<p> </p>\n<p> </p>\n<p> </p>\n<div id=\"textarea\" contenteditable=\"true\">\n<p> Test DPB Button</p>\n</div>\n<p><button id=\"dynamicbtn-165710625\" class=\"btn dynamic-btn-style .btn\">165710625 - N/A</button></p>\n<p id=\"empty\"> </p>\n<p> </p>\n<div class=\"accordion-element-js\">\n<section class=\"page-container no-header is-expanded\"><header class=\"container-header sub-header\">\n<div class=\"left-side-element-js\"><span class=\"left-title-text\">TESTING PROMO</span></div>\n</header>\n<article class=\"container-content text-section\">\n<div class=\"container-inside-text\"> </div>\n</article>\n</section>\n</div>"
    },
    {
        "id": "2",
        "createdBy": "54905d04a49acf605d645271",
        "createdByUserName": "test.admin@coral.co.uk",
        "updatedBy": "54905d04a49acf605d645271",
        "updatedByUserName": "test.admin@coral.co.uk",
        "createdAt": "2022-06-21T10:38:25.278Z",
        "updatedAt": "2022-06-21T10:38:25.278Z",
        "pageName": null,
        "brand": "ladbrokes",
        "active": false,
        "validityPeriodStart": "2022-06-01T06:55:12Z",
        "validityPeriodEnd": "2022-06-02T10:00:12Z",
        "title": "Fanzone_club",
        "bannerLink": "https://banners-cms-assets.ladbrokes.com/is/image/ladbrokescoral/272872_5ASide_From12102020?$terms_and_conditions_container_visible=0&$ladbrokes-mobile-tablet-width$",
        "description": "<p>This is to test Fanzone clubs</p>\n<div class=\"accordion-element-js\">\n<section class=\"page-container no-header is-expanded\"><header class=\"container-header toggle-header\">\n<div class=\"left-side-element-js\"><span class=\"left-title-text\">Collapse-expand panel</span></div>\n</header>\n<article class=\"container-content text-section\">\n<div class=\"container-inside-text\"> </div>\n</article>\n</section>\n</div>\n<div class=\"accordion-element-js\">\n<section class=\"page-container no-header is-expanded\"><header class=\"container-header \">\n<div class=\"left-side-element-js\"><span class=\"left-title-text\">Simple panel</span></div>\n</header>\n<article class=\"container-content text-section\">\n<div class=\"container-inside-text\"> </div>\n</article>\n</section>\n</div>\n<div class=\"accordion-element-js\">\n<section class=\"page-container no-header is-expanded\"><header class=\"container-header sub-header\">\n<div class=\"left-side-element-js\"><span class=\"left-title-text\">Section Header</span></div>\n</header>\n<article class=\"container-content text-section\">\n<div class=\"container-inside-text\"> </div>\n</article>\n</section>\n</div>\n<p><a class=\"btn btn-style1 full-width\" href=\"https://test.sports.ladbrokes.com/sport/football/matches/today\" target=\"\">GreenFull</a></p>\n<p><a class=\"btn btn-style2 full-width\" href=\"https://test.sports.ladbrokes.com/horse-racing/featured\" target=\"\">Blue Full</a></p>\n<p style=\"text-align: right;\"><a class=\"btn btn-style1 half-width\" href=\"https://test.sports.ladbrokes.com/in-play/football\" target=\"\">Green half</a></p>\n<p><a class=\"btn btn-style2 half-width\" href=\"https://test.sports.ladbrokes.com/sport/tennis/matches/today\" target=\"_blank\">Green Blue</a></p>\n<div class=\"item-panel\">border section</div>\n<p> </p>\n<p>This is lineBreak</p>\n<p> </p>\n<hr />\n<p> </p>\n<p> </p>\n<table style=\"width: 100%;\">\n<tbody>\n<tr class=\"table-header hightlight-row\">\n<td>Team</td>\n<td>P</td>\n<td>W</td>\n<td>D</td>\n<td>L</td>\n<td>GD</td>\n<td>PTS</td>\n</tr>\n<tr class=\"table-header\">\n<td>Manchester City</td>\n<td>33</td>\n<td>25</td>\n<td>5</td>\n<td>3</td>\n<td>59</td>\n<td>80</td>\n</tr>\n<tr class=\"table-header\">\n<td>Liverpool FC</td>\n<td>33</td>\n<td>24</td>\n<td>7</td>\n<td>2</td>\n<td>63</td>\n<td>79</td>\n</tr>\n<tr class=\"table-header\">\n<td>Chelsea FC</td>\n<td>32</td>\n<td>19</td>\n<td>8</td>\n<td>5</td>\n<td>40</td>\n<td>65</td>\n</tr>\n<tr class=\"table-header\">\n<td>Arsenal FC</td>\n<td>33</td>\n<td>19</td>\n<td>3</td>\n<td>11</td>\n<td>12</td>\n<td>60</td>\n</tr>\n<tr class=\"table-header\">\n<td>Tottenham Hotspur</td>\n<td>33</td>\n<td>18</td>\n<td>4</td>\n<td>11</td>\n<td>18</td>\n<td>58</td>\n</tr>\n<tr class=\"table-header hightlight-row\">\n<td>Manchester United</td>\n<td>34</td>\n<td>15</td>\n<td>9</td>\n<td>10</td>\n<td>2</td>\n<td>54</td>\n</tr>\n<tr class=\"table-header\">\n<td>West Ham United</td>\n<td>34</td>\n<td>15</td>\n<td>7</td>\n<td>12</td>\n<td>8</td>\n<td>52</td>\n</tr>\n<tr class=\"table-header\">\n<td>Wolverhampton Wanderers</td>\n<td>33</td>\n<td>15</td>\n<td>4</td>\n<td>14</td>\n<td>4</td>\n<td>49</td>\n</tr>\n<tr class=\"table-header\">\n<td>Newcastle United</td>\n<td>34</td>\n<td>11</td>\n<td>10</td>\n<td>13</td>\n<td>-15</td>\n<td>43</td>\n</tr>\n<tr class=\"table-header\">\n<td>Leicester City</td>\n<td>32</td>\n<td>11</td>\n<td>9</td>\n<td>12</td>\n<td>-4</td>\n<td>42</td>\n</tr>\n</tbody>\n</table>\n<hr />\n<table style=\"width: 100%;\" border=\"0\">\n<tbody>\n<tr>\n<td>Name</td>\n<td>A</td>\n<td>B</td>\n<td>C</td>\n</tr>\n<tr>\n<td>Man City</td>\n<td>30</td>\n<td>15</td>\n<td>15</td>\n</tr>\n<tr>\n<td>Arsenal</td>\n<td>30</td>\n<td>15</td>\n<td>15</td>\n</tr>\n</tbody>\n</table>\n<p style=\"padding-left: 60px;\"> </p>\n<p style=\"padding-left: 60px;\"> </p>\n<p style=\"padding-left: 60px;\"> </p>\n<p> </p>\n<div id=\"textarea\" contenteditable=\"true\">\n<p>|Aston Villa| |vs| |Burnley| ------ 2217527</p>\n<p><span style=\"font-size: 14px;\">|Aston Villa FC|</span></p>\n</div>\n<p><button id=\"dynamicbtn-1171262555\" class=\"btn dynamic-btn-style .btn\">1171262555 - N/A</button></p>\n<p id=\"empty\"> </p>\n<p> </p>\n<p> </p>\n<p style=\"padding-left: 90px;\"><strong><span style=\"font-size: 14px;\">WHO QUALIFIES FOR THIS SPORTS PROMOTION</span></strong></p>\n<p><span style=\"color: #993366;\"><strong>WHO QUALIFIES FOR THIS SPORTS PROMOTION</strong></span></p>\n<ul>\n<li><span style=\"font-size: 14px; font-family: Arial, Helvetica, sans-serif;\">2. This Sports Promotion is not available to customers who open NEW accounts &amp; depositing funds with Prepaid Cards, Moneybookers, Paypal, Paysafe, Neteller or Skrill.</span></li>\n<li><span style=\"font-size: 14px; font-family: Lato;\">3. This Sports Promotion is open to new (excluded deposit methods listed in term 2) and existing Online, Mobile &amp; Telephone real money customers aged 18 years or over betting in either &pound;/&euro; currency whose betting accounts are registered in the UK &amp; Republic of Ireland that are eligible to receive sports promotions from us.</span></li>\n<li><span style=\"font-size: 14px; font-family: HelveticaNeue;\">4. Employees of the Promoter, any advertising agency or web company connected with the promoter or any such person's agents or members of their families or households, are not eligible to participate in this Sports Promotion. The Promoter reserves the right to verify the eligibility of all participants.</span></li>\n</ul>\n<p> </p>\n<p><span style=\"color: #ff6600;\"><em><span style=\"font-size: 14px;\">WHO QUALIFIES FOR THIS SPORTS PROMOTION</span></em></span></p>\n<p style=\"text-align: center;\"><span style=\"font-size: 14px;\">2. This Sports Promotion is not available to customers who open NEW accounts &amp; depositing funds with Prepaid Cards, Moneybookers, Paypal, Paysafe, Neteller or Skrill.</span></p>\n<p style=\"text-align: right;\"><span style=\"font-size: 14px;\">3. This Sports Promotion is open to new (excluded deposit methods listed in term 2) and existing Online, Mobile &amp; Telephone real money customers aged 18 years or over betting in either &pound;/&euro; currency whose betting accounts are registered in the UK &amp; Republic of Ireland that are eligible to receive sports promotions from us.</span></p>\n<p style=\"text-align: left;\"><span style=\"font-size: 14px;\">4. Employees of the Promoter, any advertising agency or web company connected with the promoter or any such person's agents or members of their families or households, are not eligible to participate in this Sports Promotion. The Promoter reserves the right to verify the eligibility of all participants.</span></p>\n<p> </p>\n<p> </p>\n<p> </p>\n<p> </p>\n<p> </p>\n<p> </p>\n<p> </p>\n<p> </p>"
    }
];

export const CLUB_MOCK: ClubPromo = {
    "id": "1",
    "createdBy": "54905d04a49acf605d645271",
    "createdByUserName": "ozoneqa@ivycomptech.com",
    "updatedBy": "5645b8a220bd9e0800afdc57",
    "updatedByUserName": "ozoneqa@ivycomptech.com",
    "createdAt": "2022-06-21T10:38:00.886Z",
    "updatedAt": "2022-06-27T10:15:29.342Z",
    "pageName": null,
    "brand": "ladbrokes",
    "active": true,
    "validityPeriodStart": "2022-05-11T12:03:41.774Z",
    "validityPeriodEnd": "2022-08-20T12:03:41Z",
    "title": "PK Club Fanzone Promo",
    "bannerLink": "{5B93FBB1-DD9D-470A-A745-1413FDCB23A5}",
    "description": "<h3 style=\"text-align: center;\"><strong>This is another Test from PK</strong></h3>\n<p>This is anothet test club to handle all the scenarios like tables and headers and section</p>\n<p> </p>\n<p> </p>\n<p> </p>\n<p> </p>\n<p> </p>\n<div id=\"textarea\" contenteditable=\"true\">\n<p> Test DPB Button</p>\n</div>\n<p><button id=\"dynamicbtn-165710625\" class=\"btn dynamic-btn-style .btn\">165710625 - N/A</button></p>\n<p id=\"empty\"> </p>\n<p> </p>\n<div class=\"accordion-element-js\">\n<section class=\"page-container no-header is-expanded\"><header class=\"container-header sub-header\">\n<div class=\"left-side-element-js\"><span class=\"left-title-text\">TESTING PROMO</span></div>\n</header>\n<article class=\"container-content text-section\">\n<div class=\"container-inside-text\"> </div>\n</article>\n</section>\n</div>"
};