clone:
  depth: full
pipelines:

  default:
    - step:
        name: build
        image: azul/zulu-openjdk:17.0.5
        caches:
          - gradle
          - gradlewrapper
        script:
          - ./gradlew test build
    - step:
        name: test
        image: azul/zulu-openjdk:17.0.5
        caches:
          - sonarcloud
        script:
          - ./gradlew test sonarqube --watch-fs

  pull-requests:
    '**':
      - step:
          name: build
          image: azul/zulu-openjdk:17.0.5
          script:
            - ./gradlew test build

      - step:
          name: test
          image: azul/zulu-openjdk:17.0.5
          script:
            - ./gradlew test sonarqube --watch-fs
              -Dsonar.pullrequest.key=$BITBUCKET_PR_ID
              -Dsonar.pullrequest.base=$BITBUCKET_PR_DESTINATION_BRANCH
              -Dsonar.pullrequest.branch=$BITBUCKET_BRANCH

definitions:
  caches:
    sonarcloud: ~/.sonar/cache
    gradlewrapper: ~/.gradle/wrapper
