#$ gradle bootBuildImage && docker-compose up | tee boot.log

version: '3.8'

services:

  zookeeper:
    container_name: liveserve_zoo
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: liveserve_kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    # volumes:
      # - /var/run/docker.sock:/var/run/docker.sock

  redis:
    container_name: liveserve_redis
    image: redis
    ports:
     - "6379:6379"
    # volumes:
    #  - $PWD/redis-data:/var/lib/redis
    #  - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    # environment:
    #  - REDIS_REPLICATION_MODE=master

  liveserve:
    container_name: liveserve
    # build: .
    image: liveserve-microservice:latest
    depends_on:
      - kafka
    ports:
      - "9090:9090"
    environment:
      spring.profiles.active: LOCAL
      kafka.bootstrap-servers: kafka:9092
      # df.kafka.bootstrap-servers: kafka:9092
      spring.redis.host: redis
      logging.level.root: info
      logging.level.org.apache.kafka: error
