import { IWelcomeOverlay } from '@app/five-a-side-showdown/models/welcome-overlay';

export const WELCOME_OVERLAY_DEFAULT_VALUS: IWelcomeOverlay = {
    id: '',
    updatedBy: '',
    updatedAt: '',
    createdBy: '',
    createdAt: '',
    updatedByUserName: '',
    createdByUserName: '',
    brand: null,
    headerTitle: null,
    videoURL: null,
    sectionTitle: null,
    previewTitle: null,
    plWelcomeTitle: null,
    plWelcomeContent: null,
    plWelcomeFooter: null,
    plPrizePoolInfo: null,
    plRulesEntryInfo: null,
    plBuildTeamInfo: null,
    plBuildAnotherTeamInfo: null,
    plBuildAnotherTeamHeader: null,
    plBuildAnotherTeamContent: null,
    plBulesButtonInfo: null,
    lobbyWelcomeHeader: null,
    lobbyWelcome1: null,
    lobbyWelcome2: null,
    lobbyWelcome3: null,
    lobbySignPostingsInfo: null,
    lobbyEntryInfo: null,
    lobbyShowdownCardInfo: null,
    overlayEnabled: true,
    liveHeaderTitle: null,
    liveSectionTitle: null,
    liveFooterTitle: null,
    liveMainPageHeaderTitle: null,
    liveMainPageSectionTitle: null,
    liveEntryTitle: null,
    liveStatTitle: null,
    liveProgressHeaderTitle:null,
    liveProgressFooterTitle:null,
    liveLeaderBoardEntriesTitle:null
};

export const welcome_overlay = {
    showdown: 'Showdown Overlay',
    headerLabel: 'Welcome Overlay',
    headerTitle: 'Header Title',
    sectionTitle: 'Section Title',
    videoURL: 'Video URL',
    previewTitle: 'Preview Title',
    plHeaderLabel: 'Pre Event Overlay',
    welcomeTitle: 'Welcome Page Title',
    welcomeContent: 'Welcome Page Content',
    welcomeFooter: 'Welcome Page Footer',
    prizePoolInfo: 'Prize Pool Information',
    rulesEntryInfo: 'Rules Entry Information',
    buildTeamInfo: 'Build Team Information',
    buildAnotherTeamInfo: 'Build Another Team Information',
    buildAnotherTeamHeader: 'Build Another Team Header',
    buildAnotherTeamContent: 'Build Another Team content',
    rulesButtonInfo: 'Rules Button Info',
    welcomeTitlePL: 'Enter Welcome title',
    welcomeContentPL: 'Enter Welcome Content',
    welcomeFooterPL: 'Enter Welcome Footer',
    prizePoolInfoPL: 'Enter Prize Pool Information',
    rulesEntryInfoPL: 'Enter Rules Entry Information',
    buildTeamInfoPL: 'Enter Build Team Information',
    buildAnotherTeamInfoPL: 'Enter Build Another Team Information',
    buildAnotherTeamHeaderPL: 'Enter Build Another Team Header',
    buildAnotherTeamContentPL: 'Enter Build Another Team Content',
    rulesButtonInfoPL: 'Enter Rules Button Information'
};

export const lobby_overlay = {
    headerLabel: 'Lobby Overlay',
    welcomeHeader: 'Welcome Header',
    welcome1: 'Welcome Line 1',
    welcome2: 'Welcome Line 2',
    welcome3: 'Welcome Line 3',
    signPostingsInfo: 'Signpostings Title',
    entryInfo: 'Entry Info Title',
    showdownCardInfo: 'Showdown Card Title'
};

export const live_leader_board = {
    liveLeadeBoard: 'Live Leader Board',
    liveHeaderLabel: 'Live page Header',
    liveSectionLabel: 'Live page Section',
    liveFooterLabel: 'Live page Footer',
    liveMainPageHeader: 'Live Main page Header',
    liveMainPageSection: 'Live Main page Section',
    liveEntryLabel: 'Live page Entry',
    liveStatLabel: 'Live page Stat',
    liveProgressHeaderLabel:'Live page Progress Header',
    liveProgressFooterLabel:'Live page Progress Footer',
    liveLeaderBoardEntries:'Live page LeaderBoard Entries'
};
