import { IFanzoneSyc } from "@app/lazy-modules/fanzone/models/fanzone-syc.model";

export const SYC_DATA:IFanzoneSyc = {
    "pageName": "FanzoneSyc",
    "createdBy": '',
    "createdAt": '',
    "updatedBy": '',
    "updatedAt": '',
    "updatedByUserName": '',
    "createdByUserName": '',
    "id": '',
    "brand": "ladbrokes",
    "sycTitle": "Show us your colours",
    "sycPopUpTitle": "show your colors",
    "sycDescription": "The final spot in next season’s Premier League will be decided tonight. Tell us your favourtie club and earn a free bet.",
    "sycPopUpDescription": "The final spot in next season’s Premier League will be decided tonight. Tell us your favourtie club and earn a free bet.",
    "sycImage": "fanzone-syc",
    "okCTA": "I'M IN",
    "remindLater": "Remind Me Later",
    "remindLaterHideDays": "12",
    "dontShowAgain": "DON’T SHOW ME THIS AGAIN",
    "seasonStartDate": "20/11/2021",
    "seasonEndDate": "31/12/2021",
    "customTeamNameText": "Manchester",
    "sycCTA": "OK",
    "sycChangeCTA": "change team",
    "sycExitCTA": "exit",
    "thankYouMsg": "Thank you for your custome selec",
    "changeTeamTimePeriodMsg": "You can't change team for 30 days of your previous selection",
    "daysToChangeTeam": 15
};