export const ONE_TWO_FREE_EVENTS = {
    DESTROY_ONE_TWO_FREE: 'DESTROY_ONE_TWO_FREE',
    BOOTSTRAP_ONE_TWO_FREE: 'BOOTSTRAP_ONE_TWO_FREE',
    ADD_TO_BETSLIP: 'ADD_TO_BETSLIP',
    GO_TO_BETTING: 'GO_TO_BETTING',
    ADD_TO_BETSLIP_FINISHED: 'ADD_TO_BETSLIP_FINISHED',
    OTF_NEW_RELIC: 'OTF_NEW_RELIC',
    F2P_ACTIVATE: 'F2P_ACTIVATE'
};
