//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.21 at 03:30:49 PM CEST 
//


package com.cora.siteserv;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DrilldownNode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DrilldownNode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://schema.openbet.com/SiteServer/2.15/SSResponse.xsd}error" minOccurs="0"/>
 *         &lt;sequence>
 *           &lt;choice maxOccurs="unbounded" minOccurs="0">
 *             &lt;element ref="{http://schema.openbet.com/SiteServer/2.15/SSResponse.xsd}sport"/>
 *             &lt;element ref="{http://schema.openbet.com/SiteServer/2.15/SSResponse.xsd}category"/>
 *             &lt;element ref="{http://schema.openbet.com/SiteServer/2.15/SSResponse.xsd}class"/>
 *             &lt;element ref="{http://schema.openbet.com/SiteServer/2.15/SSResponse.xsd}type"/>
 *             &lt;element ref="{http://schema.openbet.com/SiteServer/2.15/SSResponse.xsd}subType"/>
 *             &lt;element ref="{http://schema.openbet.com/SiteServer/2.15/SSResponse.xsd}event"/>
 *             &lt;element ref="{http://schema.openbet.com/SiteServer/2.15/SSResponse.xsd}coupon"/>
 *             &lt;element ref="{http://schema.openbet.com/SiteServer/2.15/SSResponse.xsd}drilldownTag"/>
 *             &lt;element ref="{http://schema.openbet.com/SiteServer/2.15/SSResponse.xsd}drilldownNode"/>
 *             &lt;element ref="{http://schema.openbet.com/SiteServer/2.15/SSResponse.xsd}team"/>
 *             &lt;element ref="{http://schema.openbet.com/SiteServer/2.15/SSResponse.xsd}player"/>
 *             &lt;element ref="{http://schema.openbet.com/SiteServer/2.15/SSResponse.xsd}templateMarket"/>
 *             &lt;element ref="{http://schema.openbet.com/SiteServer/2.15/SSResponse.xsd}market"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *       &lt;/choice>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="parentDrilldownNodeId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="levelNumber" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="drilldownNodeIsDisplayed" type="{http://schema.openbet.com/SiteServer/2.15/SSResponse.xsd}obBoolean" />
 *       &lt;attribute name="displayOrder" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="siteChannels" type="{http://schema.openbet.com/SiteServer/2.15/SSResponse.xsd}obSetOfStrings" />
 *       &lt;attribute name="refRecordType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="refRecordId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="seoUrl" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DrilldownNode", propOrder = {
    "error",
    "sportOrCategoryOrClazz"
})
public class DrilldownNode {

    protected Error error;
    @XmlElements({
        @XmlElement(name = "sport", type = Sport.class),
        @XmlElement(name = "category", type = Category.class),
        @XmlElement(name = "class", type = Class.class),
        @XmlElement(name = "type", type = Type.class),
        @XmlElement(name = "subType", type = SubType.class),
        @XmlElement(name = "event", type = Event.class),
        @XmlElement(name = "coupon", type = Coupon.class),
        @XmlElement(name = "drilldownTag", type = DrilldownTag.class),
        @XmlElement(name = "drilldownNode", type = DrilldownNode.class),
        @XmlElement(name = "team", type = Team.class),
        @XmlElement(name = "player", type = Player.class),
        @XmlElement(name = "templateMarket", type = TemplateMarket.class),
        @XmlElement(name = "market", type = Market.class)
    })
    protected List<Object> sportOrCategoryOrClazz;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "parentDrilldownNodeId")
    protected String parentDrilldownNodeId;
    @XmlAttribute(name = "levelNumber")
    protected BigInteger levelNumber;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "drilldownNodeIsDisplayed")
    protected String drilldownNodeIsDisplayed;
    @XmlAttribute(name = "displayOrder")
    protected BigInteger displayOrder;
    @XmlAttribute(name = "siteChannels")
    protected String siteChannels;
    @XmlAttribute(name = "refRecordType")
    protected String refRecordType;
    @XmlAttribute(name = "refRecordId")
    protected String refRecordId;
    @XmlAttribute(name = "seoUrl")
    protected String seoUrl;

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link Error }
     *     
     */
    public Error getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link Error }
     *     
     */
    public void setError(Error value) {
        this.error = value;
    }

    /**
     * Gets the value of the sportOrCategoryOrClazz property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sportOrCategoryOrClazz property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSportOrCategoryOrClazz().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sport }
     * {@link Category }
     * {@link Class }
     * {@link Type }
     * {@link SubType }
     * {@link Event }
     * {@link Coupon }
     * {@link DrilldownTag }
     * {@link DrilldownNode }
     * {@link Team }
     * {@link Player }
     * {@link TemplateMarket }
     * {@link Market }
     * 
     * 
     */
    public List<Object> getSportOrCategoryOrClazz() {
        if (sportOrCategoryOrClazz == null) {
            sportOrCategoryOrClazz = new ArrayList<Object>();
        }
        return this.sportOrCategoryOrClazz;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the parentDrilldownNodeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentDrilldownNodeId() {
        return parentDrilldownNodeId;
    }

    /**
     * Sets the value of the parentDrilldownNodeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentDrilldownNodeId(String value) {
        this.parentDrilldownNodeId = value;
    }

    /**
     * Gets the value of the levelNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLevelNumber() {
        return levelNumber;
    }

    /**
     * Sets the value of the levelNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLevelNumber(BigInteger value) {
        this.levelNumber = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the drilldownNodeIsDisplayed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrilldownNodeIsDisplayed() {
        return drilldownNodeIsDisplayed;
    }

    /**
     * Sets the value of the drilldownNodeIsDisplayed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrilldownNodeIsDisplayed(String value) {
        this.drilldownNodeIsDisplayed = value;
    }

    /**
     * Gets the value of the displayOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDisplayOrder() {
        return displayOrder;
    }

    /**
     * Sets the value of the displayOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDisplayOrder(BigInteger value) {
        this.displayOrder = value;
    }

    /**
     * Gets the value of the siteChannels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteChannels() {
        return siteChannels;
    }

    /**
     * Sets the value of the siteChannels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteChannels(String value) {
        this.siteChannels = value;
    }

    /**
     * Gets the value of the refRecordType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefRecordType() {
        return refRecordType;
    }

    /**
     * Sets the value of the refRecordType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefRecordType(String value) {
        this.refRecordType = value;
    }

    /**
     * Gets the value of the refRecordId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefRecordId() {
        return refRecordId;
    }

    /**
     * Sets the value of the refRecordId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefRecordId(String value) {
        this.refRecordId = value;
    }

    /**
     * Gets the value of the seoUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeoUrl() {
        return seoUrl;
    }

    /**
     * Sets the value of the seoUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeoUrl(String value) {
        this.seoUrl = value;
    }

}
