//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.21 at 03:30:49 PM CEST 
//


package com.cora.siteserv;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExternalKeys complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExternalKeys">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="externalKeyTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="refRecordType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mappings" type="{http://schema.openbet.com/SiteServer/2.15/SSResponse.xsd}obListOfStrings" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExternalKeys")
public class ExternalKeys {

    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "externalKeyTypeCode")
    protected String externalKeyTypeCode;
    @XmlAttribute(name = "refRecordType")
    protected String refRecordType;
    @XmlAttribute(name = "mappings")
    protected String mappings;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the externalKeyTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalKeyTypeCode() {
        return externalKeyTypeCode;
    }

    /**
     * Sets the value of the externalKeyTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalKeyTypeCode(String value) {
        this.externalKeyTypeCode = value;
    }

    /**
     * Gets the value of the refRecordType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefRecordType() {
        return refRecordType;
    }

    /**
     * Sets the value of the refRecordType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefRecordType(String value) {
        this.refRecordType = value;
    }

    /**
     * Gets the value of the mappings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMappings() {
        return mappings;
    }

    /**
     * Sets the value of the mappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMappings(String value) {
        this.mappings = value;
    }

}
