package com.ladbrokescoral.oxygen.cms.api.entity;

import com.coral.oxygen.df.model.Horse;
import com.coral.oxygen.df.model.Keystat;
import com.coral.oxygen.df.model.Newspaper;
import com.coral.oxygen.df.model.Runner;
import com.coral.oxygen.df.model.Trend;
import com.egalacoral.spark.siteserver.model.Market;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import lombok.Data;

@Data
public class NextRace {

  private String id;
  private String name;
  private String eventStatusCode;
  private Boolean isActive;
  private Boolean isDisplayed;
  private Integer displayOrder;
  private String siteChannels;
  private String eventSortCode;
  private String startTime;
  private String suspendAtTime;
  private String rawIsOffCode;
  private Boolean isStarted;
  private Boolean isResulted;
  private Boolean isFinished;
  private String classId;
  private String typeId;
  private String subTypeId;
  private String sportId;
  private Integer raceNumber;
  private String streamAvailableInCountries;
  private String liveServChannels;
  private String liveServChildrenChannels;
  private String liveServLastMsgId;
  private String categoryId;
  private String categoryCode;
  private String categoryName;
  private String className;
  private Integer classDisplayOrder;
  private String classSortCode;
  private String classFlagCodes;
  private String typeName;
  private Integer typeDisplayOrder;
  private String typeFlagCodes;
  private String subTypeName;
  private Integer subTypeDisplayOrder;
  private Boolean isOpenEvent;
  private Boolean isNext24HourEvent;
  private Boolean isLiveNowEvent;
  private Boolean isLiveNowOrFutureEvent;
  private String drilldownTagNames;
  private Boolean isAvailable;
  private String mediaTypeCodes;
  private String venue;
  private String cashoutAvail;
  private String raceStage;
  private String responseCreationTime;
  private List<Market> markets;

  private String diomed;
  private String courseName;
  private String goingCode;
  private String going;
  private String obStartTime;
  private Integer rpCourseId;
  private String courseGraphicsLadbrokes;
  private List<Horse> horses = new ArrayList();
  private String courseGraphicsCoral;
  private String raceName;
  private Integer yards;
  private String distance;
  private List<Newspaper> newspapers = new ArrayList();
  private Integer raceNo;
  private String verdict;
  private String time;
  private Integer rpRaceId;
  private Boolean isAllWeather;
  private Boolean isHandicap;
  private String flatOrJump;
  private String raceType;
  private String tv;
  private Integer raceClass;
  private String agesAllowed;
  private String ageLimitation;
  private String openAgeRace;
  private Integer runnerCount;
  private Integer thoroughbredRaceNo;
  private Integer trackFences;
  private Double prize1;
  private Double prize2;
  private Double prize3;
  private Double prize4;
  private Double prize5;
  private Double prize6;
  private List<Trend> trends = new ArrayList();
  private List<Keystat> keystat = new ArrayList();
  private List<Integer> ladbrokesRetailEventId = null;
  private List<Integer> coralRetailEventId = null;
  private String bags;
  private String postPick;
  private String grade;
  private Integer rpTrackId;
  private String prize;
  private String abandoned;
  private List<Runner> runners = new ArrayList();
  private String fileType;
  private Map<String, Object> additionalProperties = new HashMap();
}
