package com.ladbrokescoral.oxygen.cms.api.entity;

public enum SportModuleType {
  FEATURED,
  QUICK_LINK,
  HIGHLIGHTS_CAROUSEL,
  SUPPER_BUTTON,
  SURFACE_BET,
  INPLAY,
  RECENTLY_PLAYED_GAMES,
  AEM_BANNERS,
  RACING_MODULE,
  UNGROUPED_FEATURED,
  VIRTUAL_NEXT_EVENTS,
  BETS_BASED_ON_YOUR_TEAM,
  BETS_BASED_ON_OTHER_FANS,

  POPULAR_BETS,
  BYB_WIDGET,
  LUCKY_DIP,
  SUPER_BUTTON,
  POPULAR_ACCA;
}
