clone:
  depth: full
pipelines:

  default:
    - step:
        name: build
        image: azul/zulu-openjdk:17.0.5
        caches:
          - gradle
          - gradlewrapper
        script:
          - chmod +x ./gradlew
          - ./gradlew spotlessApply
          - ./gradlew test build -x audit
    - step:
        name: test
        image: azul/zulu-openjdk:17.0.5
        caches:
          - sonarcloud
        script:
          - chmod +x ./gradlew
          - ./gradlew spotlessApply
          - ./gradlew test sonarqube --watch-fs
            -Dsonar.coverage.exclusions=app-pojos/src/main/java/com/coral/oxygen/middleware/pojos/model/output/*,app-pojos/src/main/java/com/coral/oxygen/middleware/pojos/model/output/featured/*.java,app-pojos/src/main/java/com/coral/oxygen/middleware/pojos/model/output/inplay/*.java
              -Dsonar.coverage.exclusions=src/main/java/com/coral/oxygen/middleware/pojos/model/**/*.java,common/src/main/java/com/coral/oxygen/middleware/common/configuration/cfcache/AWSCredentialsProviderConfig.java,common/src/main/java/com/coral/oxygen/middleware/common/configuration/cfcache/S3BrandProperties.java,common/src/main/java/com/coral/oxygen/middleware/common/service/ChangeDetector.java


  pull-requests:
    '**':
      - step:
          name: build
          image: azul/zulu-openjdk:17.0.5
          script:
            - chmod +x ./gradlew
            - ./gradlew spotlessApply
            - ./gradlew test build -x audit

      - step:
          name: test
          image: azul/zulu-openjdk:17.0.5
          script:
            - chmod +x ./gradlew
            - ./gradlew spotlessApply
            - ./gradlew test sonarqube --watch-fs
              -Dsonar.pullrequest.key=$BITBUCKET_PR_ID
              -Dsonar.pullrequest.base=$BITBUCKET_PR_DESTINATION_BRANCH
              -Dsonar.pullrequest.branch=$BITBUCKET_BRANCH
              -Dsonar.coverage.exclusions=app-pojos/src/main/java/com/coral/oxygen/middleware/pojos/model/output/*,app-pojos/src/main/java/com/coral/oxygen/middleware/pojos/model/output/featured/*.java,app-pojos/src/main/java/com/coral/oxygen/middleware/pojos/model/output/inplay/*.java
              -Dsonar.coverage.exclusions=src/main/java/com/coral/oxygen/middleware/pojos/model/**/*.java,common/src/main/java/com/coral/oxygen/middleware/common/configuration/cfcache/AWSCredentialsProviderConfig.java,common/src/main/java/com/coral/oxygen/middleware/common/configuration/cfcache/S3BrandProperties.java,common/src/main/java/com/coral/oxygen/middleware/common/service/ChangeDetector.java,src/main/java/com/coral/oxygen/middleware/Application.java

definitions:
  caches:
    sonarcloud: ~/.sonar/cache
    gradlewrapper: ~/.gradle/wrapper
