homeModule:
  removeExpired:
    cron: 0 0/5 * 1/1 * ?
dashboard:
  removeExpired:
    cron: 0 0/5 * 1/1 * ?

siteserver:
  base:
    url: https://ss-aka-ori-gib.coral.co.uk/

stats:
  center:
    url: https://stats-centre.coral.co.uk/

api:
  buildyourbet:
    ladbrokes:
      url: https://buildyourbet-hlv0.ladbrokesoxygen.nonprod.cloud.ladbrokescoral.com/
    bma:
      url: https://buildyourbet-hlv0.coralsports.nonprod.cloud.ladbrokescoral.com/

masterlock:
  aws:
    dynamo:
      url: https://dynamodb.eu-west-2.amazonaws.com
      lock-table-name: CR-MSLOCKTABLE-NONPROD

akamai:
  scheduled:
    enabled: false


df:
  base:
    url: https://sb-api.coral.co.uk
  api:
    key: CD9eed783e6f474d2c9a0bfd5a627ebd5a

google-cloud:
  big-query:
    entriesTableId: Entries_HLV
    timelineChangelogTableId: Change_Log_HLV

specialpages:
  specialpageConfig:
    ladbrokes:
      url: https://bpp-hlv1.ladbrokesoxygen.nonprod.cloud.ladbrokescoral.com/Proxy/specialpage
      secret: export MAINTENANCE_KEY=VALUE
    bma:
      url: https://bpp-hlv1.coralsports.nonprod.cloud.ladbrokescoral.com/Proxy/specialpage
      secret: export MAINTENANCE_KEY=VALUE

# always last few seconds should be sync with featured.cron.expression
last.view.seconds: 5

cfcache:
  tags:
    bma: CSP-hlv1-coral
    ladbrokes : CSP-hlv1-ladbrokes


magicurl:
  longurl: https://load-sports.ladbrokes.com/5-a-side/leaderboard/

showdown:
  base:
    url: https://showdown2.internal.stress.ladbrokes.com/showdown/api/

topic:
  bet-pack:
    prefix: HLV1
  lads:
    cms-push:
      prefix: HLV1-LB
      partitions: 4
      replicaFactor: 4
  coral:
    cms-push:
      prefix: HLV1-CR
      partitions: 4
      replicaFactor: 4

coral:
  kafka:
    admin:
      properties:
        bootstrap:
          servers: ${coral.kafka.bootstrap-servers}
    bootstrap-servers:
      10.153.48.67:9092,10.153.48.68:9092,10.153.48.69:9092,10.153.48.74:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: ${coral.kafka.bootstrap-servers}
      ssl:
        key-store-location: classpath:ssl/stress/coral/ozone-publisher.keystore.jks
        trust-store-location: classpath:ssl/stress/coral/ozone-publisher.truststore.jks
        key-store-password: changeit
        key-password: changeit
        trust-store-password: changeit
        trust-store-type: JKS
        key-store-type: JKS
      security:
        protocol: SSL
    properties:
      security:
        protocol: SSL
    topic:
      ladbrokes: timeline
      coral: timeline-cr
    partitions: 2
    replicaFactor: 3
  topic:
    timeline: timeline
    active-bet-packs: ${topic.bet-pack.prefix}__active-bet-packs-topic
    partitions: 2
    replicaFactor: 3

ladbrokes:
  kafka:
    bootstrap-servers: 10.153.49.56:9092,10.153.49.57:9092,10.153.49.58:9092,10.153.49.59:9092
    admin:
      properties:
        bootstrap:
          servers: ${ladbrokes.kafka.bootstrap-servers}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: ${ladbrokes.kafka.bootstrap-servers}
      ssl:
        key-store-location: classpath:ssl/stress/ladbrokes/ozone-publisher.keystore.jks
        trust-store-location: classpath:ssl/stress/ladbrokes/ozone-publisher.truststore.jks
        key-store-password: changeit
        key-password: changeit
        trust-store-password: changeit
        trust-store-type: JKS
        key-store-type: JKS
      security:
        protocol: SSL
    properties:
      security:
        protocol: SSL
    topic:
      leaderboard-contest: ${distributed.prefix}-LDRBRD-leaderboard-contest
    partitions: 1
    replicaFactor: 1
  topic:
    timeline: timeline
